/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
	"reflect"
)

// Linger please
var (
	_ _context.Context
)

type DetachedSavepointsApi interface {

	/*
	CreateDetachedSavepoint Creates a new detached savepoint.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @return ApiCreateDetachedSavepointRequest
	*/
	CreateDetachedSavepoint(ctx _context.Context) ApiCreateDetachedSavepointRequest

	// CreateDetachedSavepointExecute executes the request
	//  @return Savepoint
	CreateDetachedSavepointExecute(r ApiCreateDetachedSavepointRequest) (Savepoint, *_nethttp.Response, error)

	/*
	DeleteDetachedSavepoint Deletes the Detached Savepoint of the given name.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param detachedSavepointName Name of the Detached Savepoint
	 @return ApiDeleteDetachedSavepointRequest
	*/
	DeleteDetachedSavepoint(ctx _context.Context, detachedSavepointName string) ApiDeleteDetachedSavepointRequest

	// DeleteDetachedSavepointExecute executes the request
	DeleteDetachedSavepointExecute(r ApiDeleteDetachedSavepointRequest) (*_nethttp.Response, error)

	/*
	GetDetachedSavepoint Retrieve the Detached Savepoint of the given name.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @param detachedSavepointName Name of the Detached Savepoint
	 @return ApiGetDetachedSavepointRequest
	*/
	GetDetachedSavepoint(ctx _context.Context, detachedSavepointName string) ApiGetDetachedSavepointRequest

	// GetDetachedSavepointExecute executes the request
	//  @return Savepoint
	GetDetachedSavepointExecute(r ApiGetDetachedSavepointRequest) (Savepoint, *_nethttp.Response, error)

	/*
	ListDetachedSavepoints Retrieve a paginated list of all Detached Savepoints.

	 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 @return ApiListDetachedSavepointsRequest
	*/
	ListDetachedSavepoints(ctx _context.Context) ApiListDetachedSavepointsRequest

	// ListDetachedSavepointsExecute executes the request
	//  @return SavepointsPage
	ListDetachedSavepointsExecute(r ApiListDetachedSavepointsRequest) (SavepointsPage, *_nethttp.Response, error)
}

// DetachedSavepointsApiService DetachedSavepointsApi service
type DetachedSavepointsApiService service

type ApiCreateDetachedSavepointRequest struct {
	ctx _context.Context
	ApiService DetachedSavepointsApi
	savepoint *Savepoint
}

func (r ApiCreateDetachedSavepointRequest) Savepoint(savepoint Savepoint) ApiCreateDetachedSavepointRequest {
	r.savepoint = &savepoint
	return r
}

func (r ApiCreateDetachedSavepointRequest) Execute() (Savepoint, *_nethttp.Response, error) {
	return r.ApiService.CreateDetachedSavepointExecute(r)
}

/*
CreateDetachedSavepoint Creates a new detached savepoint.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateDetachedSavepointRequest
*/
func (a *DetachedSavepointsApiService) CreateDetachedSavepoint(ctx _context.Context) ApiCreateDetachedSavepointRequest {
	return ApiCreateDetachedSavepointRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Savepoint
func (a *DetachedSavepointsApiService) CreateDetachedSavepointExecute(r ApiCreateDetachedSavepointRequest) (Savepoint, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Savepoint
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DetachedSavepointsApiService.CreateDetachedSavepoint")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/cmf/api/v1/detached-savepoints"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/yaml"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/yaml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.savepoint
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v RestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v RestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v RestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteDetachedSavepointRequest struct {
	ctx _context.Context
	ApiService DetachedSavepointsApi
	detachedSavepointName string
}


func (r ApiDeleteDetachedSavepointRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.DeleteDetachedSavepointExecute(r)
}

/*
DeleteDetachedSavepoint Deletes the Detached Savepoint of the given name.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param detachedSavepointName Name of the Detached Savepoint
 @return ApiDeleteDetachedSavepointRequest
*/
func (a *DetachedSavepointsApiService) DeleteDetachedSavepoint(ctx _context.Context, detachedSavepointName string) ApiDeleteDetachedSavepointRequest {
	return ApiDeleteDetachedSavepointRequest{
		ApiService: a,
		ctx: ctx,
		detachedSavepointName: detachedSavepointName,
	}
}

// Execute executes the request
func (a *DetachedSavepointsApiService) DeleteDetachedSavepointExecute(r ApiDeleteDetachedSavepointRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodDelete
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DetachedSavepointsApiService.DeleteDetachedSavepoint")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/cmf/api/v1/detached-savepoints/{detachedSavepointName}"
	localVarPath = strings.Replace(localVarPath, "{"+"detachedSavepointName"+"}", _neturl.PathEscape(parameterToString(r.detachedSavepointName, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/yaml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v RestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetDetachedSavepointRequest struct {
	ctx _context.Context
	ApiService DetachedSavepointsApi
	detachedSavepointName string
}


func (r ApiGetDetachedSavepointRequest) Execute() (Savepoint, *_nethttp.Response, error) {
	return r.ApiService.GetDetachedSavepointExecute(r)
}

/*
GetDetachedSavepoint Retrieve the Detached Savepoint of the given name.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param detachedSavepointName Name of the Detached Savepoint
 @return ApiGetDetachedSavepointRequest
*/
func (a *DetachedSavepointsApiService) GetDetachedSavepoint(ctx _context.Context, detachedSavepointName string) ApiGetDetachedSavepointRequest {
	return ApiGetDetachedSavepointRequest{
		ApiService: a,
		ctx: ctx,
		detachedSavepointName: detachedSavepointName,
	}
}

// Execute executes the request
//  @return Savepoint
func (a *DetachedSavepointsApiService) GetDetachedSavepointExecute(r ApiGetDetachedSavepointRequest) (Savepoint, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Savepoint
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DetachedSavepointsApiService.GetDetachedSavepoint")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/cmf/api/v1/detached-savepoints/{detachedSavepointName}"
	localVarPath = strings.Replace(localVarPath, "{"+"detachedSavepointName"+"}", _neturl.PathEscape(parameterToString(r.detachedSavepointName, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/yaml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v RestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v RestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListDetachedSavepointsRequest struct {
	ctx _context.Context
	ApiService DetachedSavepointsApi
	page *int32
	size *int32
	sort *[]string
	name *string
}

// Zero-based page index (0..N)
func (r ApiListDetachedSavepointsRequest) Page(page int32) ApiListDetachedSavepointsRequest {
	r.page = &page
	return r
}
// The size of the page to be returned
func (r ApiListDetachedSavepointsRequest) Size(size int32) ApiListDetachedSavepointsRequest {
	r.size = &size
	return r
}
// Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
func (r ApiListDetachedSavepointsRequest) Sort(sort []string) ApiListDetachedSavepointsRequest {
	r.sort = &sort
	return r
}
// Filter by detached savepoint name prefix (e.g. ?name&#x3D;abc)
func (r ApiListDetachedSavepointsRequest) Name(name string) ApiListDetachedSavepointsRequest {
	r.name = &name
	return r
}

func (r ApiListDetachedSavepointsRequest) Execute() (SavepointsPage, *_nethttp.Response, error) {
	return r.ApiService.ListDetachedSavepointsExecute(r)
}

/*
ListDetachedSavepoints Retrieve a paginated list of all Detached Savepoints.

 @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListDetachedSavepointsRequest
*/
func (a *DetachedSavepointsApiService) ListDetachedSavepoints(ctx _context.Context) ApiListDetachedSavepointsRequest {
	return ApiListDetachedSavepointsRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SavepointsPage
func (a *DetachedSavepointsApiService) ListDetachedSavepointsExecute(r ApiListDetachedSavepointsRequest) (SavepointsPage, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  SavepointsPage
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DetachedSavepointsApiService.ListDetachedSavepoints")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/cmf/api/v1/detached-savepoints"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}

	if r.page != nil {
		localVarQueryParams.Add("page", parameterToString(*r.page, ""))
	}
	if r.size != nil {
		localVarQueryParams.Add("size", parameterToString(*r.size, ""))
	}
	if r.sort != nil {
		t := *r.sort
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				localVarQueryParams.Add("sort", parameterToString(s.Index(i), "multi"))
			}
		} else {
			localVarQueryParams.Add("sort", parameterToString(t, "multi"))
		}
	}
	if r.name != nil {
		localVarQueryParams.Add("name", parameterToString(*r.name, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/yaml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v RestError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
