/*
 * Confluent Manager for Apache Flink / CMF
 *
 * Apache Flink job lifecycle management component for Confluent Platform.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1
// Sort struct for Sort
type Sort struct {
	Sorted bool `json:"sorted,omitempty"`
	Unsorted bool `json:"unsorted,omitempty"`
	Empty bool `json:"empty,omitempty"`
}
