/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// EventDataReasonMessage struct for EventDataReasonMessage
type EventDataReasonMessage struct {
	// The FKO event reason (e.g., ValidationError, CrashLoopBackOff, Missing, ScalingReport, AutoscalerError). The event category is conveyed by status.type.
	Reason *string `json:"reason,omitempty"`
	// The full raw K8s event message content
	Message *string `json:"message,omitempty"`
}

// NewEventDataReasonMessage instantiates a new EventDataReasonMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventDataReasonMessage() *EventDataReasonMessage {
	this := EventDataReasonMessage{}
	return &this
}

// NewEventDataReasonMessageWithDefaults instantiates a new EventDataReasonMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventDataReasonMessageWithDefaults() *EventDataReasonMessage {
	this := EventDataReasonMessage{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *EventDataReasonMessage) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDataReasonMessage) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *EventDataReasonMessage) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *EventDataReasonMessage) SetReason(v string) {
	o.Reason = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *EventDataReasonMessage) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDataReasonMessage) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *EventDataReasonMessage) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *EventDataReasonMessage) SetMessage(v string) {
	o.Message = &v
}

func (o EventDataReasonMessage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableEventDataReasonMessage struct {
	value *EventDataReasonMessage
	isSet bool
}

func (v NullableEventDataReasonMessage) Get() *EventDataReasonMessage {
	return v.value
}

func (v *NullableEventDataReasonMessage) Set(val *EventDataReasonMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableEventDataReasonMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableEventDataReasonMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventDataReasonMessage(val *EventDataReasonMessage) *NullableEventDataReasonMessage {
	return &NullableEventDataReasonMessage{value: val, isSet: true}
}

func (v NullableEventDataReasonMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventDataReasonMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


