/*
 * Confluent Manager for Apache Flink / CMF
 *
 * Apache Flink job lifecycle management component for Confluent Platform.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1
// EnvironmentsPage struct for EnvironmentsPage
type EnvironmentsPage struct {
	Pageable Pageable `json:"pageable,omitempty"`
	Metadata EnvironmentsPageMetadata `json:"metadata,omitempty"`
	Items []Environment `json:"items,omitempty"`
}
