/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// KafkaCatalogStatus Status for Kafka Catalog
type KafkaCatalogStatus struct {
	// Environments with access to the Kafka Catalog
	EnvironmentsWithAccess *[]string `json:"environmentsWithAccess,omitempty"`
}

// NewKafkaCatalogStatus instantiates a new KafkaCatalogStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaCatalogStatus() *KafkaCatalogStatus {
	this := KafkaCatalogStatus{}
	return &this
}

// NewKafkaCatalogStatusWithDefaults instantiates a new KafkaCatalogStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaCatalogStatusWithDefaults() *KafkaCatalogStatus {
	this := KafkaCatalogStatus{}
	return &this
}

// GetEnvironmentsWithAccess returns the EnvironmentsWithAccess field value if set, zero value otherwise.
func (o *KafkaCatalogStatus) GetEnvironmentsWithAccess() []string {
	if o == nil || o.EnvironmentsWithAccess == nil {
		var ret []string
		return ret
	}
	return *o.EnvironmentsWithAccess
}

// GetEnvironmentsWithAccessOk returns a tuple with the EnvironmentsWithAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaCatalogStatus) GetEnvironmentsWithAccessOk() (*[]string, bool) {
	if o == nil || o.EnvironmentsWithAccess == nil {
		return nil, false
	}
	return o.EnvironmentsWithAccess, true
}

// HasEnvironmentsWithAccess returns a boolean if a field has been set.
func (o *KafkaCatalogStatus) HasEnvironmentsWithAccess() bool {
	if o != nil && o.EnvironmentsWithAccess != nil {
		return true
	}

	return false
}

// SetEnvironmentsWithAccess gets a reference to the given []string and assigns it to the EnvironmentsWithAccess field.
func (o *KafkaCatalogStatus) SetEnvironmentsWithAccess(v []string) {
	o.EnvironmentsWithAccess = &v
}

func (o KafkaCatalogStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EnvironmentsWithAccess != nil {
		toSerialize["environmentsWithAccess"] = o.EnvironmentsWithAccess
	}
	return json.Marshal(toSerialize)
}

type NullableKafkaCatalogStatus struct {
	value *KafkaCatalogStatus
	isSet bool
}

func (v NullableKafkaCatalogStatus) Get() *KafkaCatalogStatus {
	return v.value
}

func (v *NullableKafkaCatalogStatus) Set(val *KafkaCatalogStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaCatalogStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaCatalogStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaCatalogStatus(val *KafkaCatalogStatus) *NullableKafkaCatalogStatus {
	return &NullableKafkaCatalogStatus{value: val, isSet: true}
}

func (v NullableKafkaCatalogStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaCatalogStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


