/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// KafkaDatabasesPage struct for KafkaDatabasesPage
type KafkaDatabasesPage struct {
	Pageable *Pageable `json:"pageable,omitempty"`
	Metadata *DatabasePageMetadata `json:"metadata,omitempty"`
	Items *[]KafkaDatabase `json:"items,omitempty"`
}

// NewKafkaDatabasesPage instantiates a new KafkaDatabasesPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaDatabasesPage() *KafkaDatabasesPage {
	this := KafkaDatabasesPage{}
	return &this
}

// NewKafkaDatabasesPageWithDefaults instantiates a new KafkaDatabasesPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaDatabasesPageWithDefaults() *KafkaDatabasesPage {
	this := KafkaDatabasesPage{}
	return &this
}

// GetPageable returns the Pageable field value if set, zero value otherwise.
func (o *KafkaDatabasesPage) GetPageable() Pageable {
	if o == nil || o.Pageable == nil {
		var ret Pageable
		return ret
	}
	return *o.Pageable
}

// GetPageableOk returns a tuple with the Pageable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaDatabasesPage) GetPageableOk() (*Pageable, bool) {
	if o == nil || o.Pageable == nil {
		return nil, false
	}
	return o.Pageable, true
}

// HasPageable returns a boolean if a field has been set.
func (o *KafkaDatabasesPage) HasPageable() bool {
	if o != nil && o.Pageable != nil {
		return true
	}

	return false
}

// SetPageable gets a reference to the given Pageable and assigns it to the Pageable field.
func (o *KafkaDatabasesPage) SetPageable(v Pageable) {
	o.Pageable = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *KafkaDatabasesPage) GetMetadata() DatabasePageMetadata {
	if o == nil || o.Metadata == nil {
		var ret DatabasePageMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaDatabasesPage) GetMetadataOk() (*DatabasePageMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *KafkaDatabasesPage) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given DatabasePageMetadata and assigns it to the Metadata field.
func (o *KafkaDatabasesPage) SetMetadata(v DatabasePageMetadata) {
	o.Metadata = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *KafkaDatabasesPage) GetItems() []KafkaDatabase {
	if o == nil || o.Items == nil {
		var ret []KafkaDatabase
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaDatabasesPage) GetItemsOk() (*[]KafkaDatabase, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *KafkaDatabasesPage) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []KafkaDatabase and assigns it to the Items field.
func (o *KafkaDatabasesPage) SetItems(v []KafkaDatabase) {
	o.Items = &v
}

func (o KafkaDatabasesPage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pageable != nil {
		toSerialize["pageable"] = o.Pageable
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableKafkaDatabasesPage struct {
	value *KafkaDatabasesPage
	isSet bool
}

func (v NullableKafkaDatabasesPage) Get() *KafkaDatabasesPage {
	return v.value
}

func (v *NullableKafkaDatabasesPage) Set(val *KafkaDatabasesPage) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaDatabasesPage) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaDatabasesPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaDatabasesPage(val *KafkaDatabasesPage) *NullableKafkaDatabasesPage {
	return &NullableKafkaDatabasesPage{value: val, isSet: true}
}

func (v NullableKafkaDatabasesPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaDatabasesPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


