/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// StatementsPage struct for StatementsPage
type StatementsPage struct {
	Pageable *Pageable `json:"pageable,omitempty"`
	Metadata *StatementPageMetadata `json:"metadata,omitempty"`
	Items *[]Statement `json:"items,omitempty"`
}

// NewStatementsPage instantiates a new StatementsPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatementsPage() *StatementsPage {
	this := StatementsPage{}
	return &this
}

// NewStatementsPageWithDefaults instantiates a new StatementsPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatementsPageWithDefaults() *StatementsPage {
	this := StatementsPage{}
	return &this
}

// GetPageable returns the Pageable field value if set, zero value otherwise.
func (o *StatementsPage) GetPageable() Pageable {
	if o == nil || o.Pageable == nil {
		var ret Pageable
		return ret
	}
	return *o.Pageable
}

// GetPageableOk returns a tuple with the Pageable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementsPage) GetPageableOk() (*Pageable, bool) {
	if o == nil || o.Pageable == nil {
		return nil, false
	}
	return o.Pageable, true
}

// HasPageable returns a boolean if a field has been set.
func (o *StatementsPage) HasPageable() bool {
	if o != nil && o.Pageable != nil {
		return true
	}

	return false
}

// SetPageable gets a reference to the given Pageable and assigns it to the Pageable field.
func (o *StatementsPage) SetPageable(v Pageable) {
	o.Pageable = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *StatementsPage) GetMetadata() StatementPageMetadata {
	if o == nil || o.Metadata == nil {
		var ret StatementPageMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementsPage) GetMetadataOk() (*StatementPageMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *StatementsPage) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given StatementPageMetadata and assigns it to the Metadata field.
func (o *StatementsPage) SetMetadata(v StatementPageMetadata) {
	o.Metadata = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *StatementsPage) GetItems() []Statement {
	if o == nil || o.Items == nil {
		var ret []Statement
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementsPage) GetItemsOk() (*[]Statement, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *StatementsPage) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Statement and assigns it to the Items field.
func (o *StatementsPage) SetItems(v []Statement) {
	o.Items = &v
}

func (o StatementsPage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pageable != nil {
		toSerialize["pageable"] = o.Pageable
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableStatementsPage struct {
	value *StatementsPage
	isSet bool
}

func (v NullableStatementsPage) Get() *StatementsPage {
	return v.value
}

func (v *NullableStatementsPage) Set(val *StatementsPage) {
	v.value = val
	v.isSet = true
}

func (v NullableStatementsPage) IsSet() bool {
	return v.isSet
}

func (v *NullableStatementsPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatementsPage(val *StatementsPage) *NullableStatementsPage {
	return &NullableStatementsPage{value: val, isSet: true}
}

func (v NullableStatementsPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatementsPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


