/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// EnvironmentSecretMappingMetadata Metadata about the environment secret mapping
type EnvironmentSecretMappingMetadata struct {
	// Name of the Connection Secret ID
	Name *string `json:"name,omitempty"`
	// Unique identifier of the EnvironmentSecretMapping
	Uid *string `json:"uid,omitempty"`
	// Timestamp when the EnvironmentSecretMapping was created
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`
	// Timestamp when the EnvironmentSecretMapping was last updated
	UpdateTimestamp *string `json:"updateTimestamp,omitempty"`
	// Labels of the EnvironmentSecretMapping
	Labels *map[string]string `json:"labels,omitempty"`
	// Annotations of the EnvironmentSecretMapping
	Annotations *map[string]string `json:"annotations,omitempty"`
}

// NewEnvironmentSecretMappingMetadata instantiates a new EnvironmentSecretMappingMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentSecretMappingMetadata() *EnvironmentSecretMappingMetadata {
	this := EnvironmentSecretMappingMetadata{}
	return &this
}

// NewEnvironmentSecretMappingMetadataWithDefaults instantiates a new EnvironmentSecretMappingMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentSecretMappingMetadataWithDefaults() *EnvironmentSecretMappingMetadata {
	this := EnvironmentSecretMappingMetadata{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EnvironmentSecretMappingMetadata) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentSecretMappingMetadata) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EnvironmentSecretMappingMetadata) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EnvironmentSecretMappingMetadata) SetName(v string) {
	o.Name = &v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *EnvironmentSecretMappingMetadata) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentSecretMappingMetadata) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *EnvironmentSecretMappingMetadata) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *EnvironmentSecretMappingMetadata) SetUid(v string) {
	o.Uid = &v
}

// GetCreationTimestamp returns the CreationTimestamp field value if set, zero value otherwise.
func (o *EnvironmentSecretMappingMetadata) GetCreationTimestamp() string {
	if o == nil || o.CreationTimestamp == nil {
		var ret string
		return ret
	}
	return *o.CreationTimestamp
}

// GetCreationTimestampOk returns a tuple with the CreationTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentSecretMappingMetadata) GetCreationTimestampOk() (*string, bool) {
	if o == nil || o.CreationTimestamp == nil {
		return nil, false
	}
	return o.CreationTimestamp, true
}

// HasCreationTimestamp returns a boolean if a field has been set.
func (o *EnvironmentSecretMappingMetadata) HasCreationTimestamp() bool {
	if o != nil && o.CreationTimestamp != nil {
		return true
	}

	return false
}

// SetCreationTimestamp gets a reference to the given string and assigns it to the CreationTimestamp field.
func (o *EnvironmentSecretMappingMetadata) SetCreationTimestamp(v string) {
	o.CreationTimestamp = &v
}

// GetUpdateTimestamp returns the UpdateTimestamp field value if set, zero value otherwise.
func (o *EnvironmentSecretMappingMetadata) GetUpdateTimestamp() string {
	if o == nil || o.UpdateTimestamp == nil {
		var ret string
		return ret
	}
	return *o.UpdateTimestamp
}

// GetUpdateTimestampOk returns a tuple with the UpdateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentSecretMappingMetadata) GetUpdateTimestampOk() (*string, bool) {
	if o == nil || o.UpdateTimestamp == nil {
		return nil, false
	}
	return o.UpdateTimestamp, true
}

// HasUpdateTimestamp returns a boolean if a field has been set.
func (o *EnvironmentSecretMappingMetadata) HasUpdateTimestamp() bool {
	if o != nil && o.UpdateTimestamp != nil {
		return true
	}

	return false
}

// SetUpdateTimestamp gets a reference to the given string and assigns it to the UpdateTimestamp field.
func (o *EnvironmentSecretMappingMetadata) SetUpdateTimestamp(v string) {
	o.UpdateTimestamp = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *EnvironmentSecretMappingMetadata) GetLabels() map[string]string {
	if o == nil || o.Labels == nil {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentSecretMappingMetadata) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *EnvironmentSecretMappingMetadata) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *EnvironmentSecretMappingMetadata) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *EnvironmentSecretMappingMetadata) GetAnnotations() map[string]string {
	if o == nil || o.Annotations == nil {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentSecretMappingMetadata) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || o.Annotations == nil {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *EnvironmentSecretMappingMetadata) HasAnnotations() bool {
	if o != nil && o.Annotations != nil {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *EnvironmentSecretMappingMetadata) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

func (o EnvironmentSecretMappingMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if o.CreationTimestamp != nil {
		toSerialize["creationTimestamp"] = o.CreationTimestamp
	}
	if o.UpdateTimestamp != nil {
		toSerialize["updateTimestamp"] = o.UpdateTimestamp
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Annotations != nil {
		toSerialize["annotations"] = o.Annotations
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentSecretMappingMetadata struct {
	value *EnvironmentSecretMappingMetadata
	isSet bool
}

func (v NullableEnvironmentSecretMappingMetadata) Get() *EnvironmentSecretMappingMetadata {
	return v.value
}

func (v *NullableEnvironmentSecretMappingMetadata) Set(val *EnvironmentSecretMappingMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentSecretMappingMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentSecretMappingMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentSecretMappingMetadata(val *EnvironmentSecretMappingMetadata) *NullableEnvironmentSecretMappingMetadata {
	return &NullableEnvironmentSecretMappingMetadata{value: val, isSet: true}
}

func (v NullableEnvironmentSecretMappingMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentSecretMappingMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


