/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// EnvironmentSecretMappingsPageAllOf struct for EnvironmentSecretMappingsPageAllOf
type EnvironmentSecretMappingsPageAllOf struct {
	Metadata *EnvironmentSecretMappingsPageMetadata `json:"metadata,omitempty"`
	Items *[]EnvironmentSecretMapping `json:"items,omitempty"`
}

// NewEnvironmentSecretMappingsPageAllOf instantiates a new EnvironmentSecretMappingsPageAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentSecretMappingsPageAllOf() *EnvironmentSecretMappingsPageAllOf {
	this := EnvironmentSecretMappingsPageAllOf{}
	return &this
}

// NewEnvironmentSecretMappingsPageAllOfWithDefaults instantiates a new EnvironmentSecretMappingsPageAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentSecretMappingsPageAllOfWithDefaults() *EnvironmentSecretMappingsPageAllOf {
	this := EnvironmentSecretMappingsPageAllOf{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *EnvironmentSecretMappingsPageAllOf) GetMetadata() EnvironmentSecretMappingsPageMetadata {
	if o == nil || o.Metadata == nil {
		var ret EnvironmentSecretMappingsPageMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentSecretMappingsPageAllOf) GetMetadataOk() (*EnvironmentSecretMappingsPageMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *EnvironmentSecretMappingsPageAllOf) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given EnvironmentSecretMappingsPageMetadata and assigns it to the Metadata field.
func (o *EnvironmentSecretMappingsPageAllOf) SetMetadata(v EnvironmentSecretMappingsPageMetadata) {
	o.Metadata = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *EnvironmentSecretMappingsPageAllOf) GetItems() []EnvironmentSecretMapping {
	if o == nil || o.Items == nil {
		var ret []EnvironmentSecretMapping
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentSecretMappingsPageAllOf) GetItemsOk() (*[]EnvironmentSecretMapping, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *EnvironmentSecretMappingsPageAllOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []EnvironmentSecretMapping and assigns it to the Items field.
func (o *EnvironmentSecretMappingsPageAllOf) SetItems(v []EnvironmentSecretMapping) {
	o.Items = &v
}

func (o EnvironmentSecretMappingsPageAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentSecretMappingsPageAllOf struct {
	value *EnvironmentSecretMappingsPageAllOf
	isSet bool
}

func (v NullableEnvironmentSecretMappingsPageAllOf) Get() *EnvironmentSecretMappingsPageAllOf {
	return v.value
}

func (v *NullableEnvironmentSecretMappingsPageAllOf) Set(val *EnvironmentSecretMappingsPageAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentSecretMappingsPageAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentSecretMappingsPageAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentSecretMappingsPageAllOf(val *EnvironmentSecretMappingsPageAllOf) *NullableEnvironmentSecretMappingsPageAllOf {
	return &NullableEnvironmentSecretMappingsPageAllOf{value: val, isSet: true}
}

func (v NullableEnvironmentSecretMappingsPageAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentSecretMappingsPageAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


