/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// ApplicationsPageAllOf struct for ApplicationsPageAllOf
type ApplicationsPageAllOf struct {
	Metadata *ApplicationPageMetadata `json:"metadata,omitempty"`
	Items *[]FlinkApplication `json:"items,omitempty"`
}

// NewApplicationsPageAllOf instantiates a new ApplicationsPageAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationsPageAllOf() *ApplicationsPageAllOf {
	this := ApplicationsPageAllOf{}
	return &this
}

// NewApplicationsPageAllOfWithDefaults instantiates a new ApplicationsPageAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationsPageAllOfWithDefaults() *ApplicationsPageAllOf {
	this := ApplicationsPageAllOf{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ApplicationsPageAllOf) GetMetadata() ApplicationPageMetadata {
	if o == nil || o.Metadata == nil {
		var ret ApplicationPageMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationsPageAllOf) GetMetadataOk() (*ApplicationPageMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ApplicationsPageAllOf) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ApplicationPageMetadata and assigns it to the Metadata field.
func (o *ApplicationsPageAllOf) SetMetadata(v ApplicationPageMetadata) {
	o.Metadata = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ApplicationsPageAllOf) GetItems() []FlinkApplication {
	if o == nil || o.Items == nil {
		var ret []FlinkApplication
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationsPageAllOf) GetItemsOk() (*[]FlinkApplication, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ApplicationsPageAllOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []FlinkApplication and assigns it to the Items field.
func (o *ApplicationsPageAllOf) SetItems(v []FlinkApplication) {
	o.Items = &v
}

func (o ApplicationsPageAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableApplicationsPageAllOf struct {
	value *ApplicationsPageAllOf
	isSet bool
}

func (v NullableApplicationsPageAllOf) Get() *ApplicationsPageAllOf {
	return v.value
}

func (v *NullableApplicationsPageAllOf) Set(val *ApplicationsPageAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationsPageAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationsPageAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationsPageAllOf(val *ApplicationsPageAllOf) *NullableApplicationsPageAllOf {
	return &NullableApplicationsPageAllOf{value: val, isSet: true}
}

func (v NullableApplicationsPageAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationsPageAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


