/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// ResourcesByStatusAndTypeSummary Summary of resources by status and type
type ResourcesByStatusAndTypeSummary struct {
	Applications *ApplicationsByStatusSummary `json:"applications,omitempty"`
	Statements *StatementsByStatusSummary `json:"statements,omitempty"`
}

// NewResourcesByStatusAndTypeSummary instantiates a new ResourcesByStatusAndTypeSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourcesByStatusAndTypeSummary() *ResourcesByStatusAndTypeSummary {
	this := ResourcesByStatusAndTypeSummary{}
	return &this
}

// NewResourcesByStatusAndTypeSummaryWithDefaults instantiates a new ResourcesByStatusAndTypeSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourcesByStatusAndTypeSummaryWithDefaults() *ResourcesByStatusAndTypeSummary {
	this := ResourcesByStatusAndTypeSummary{}
	return &this
}

// GetApplications returns the Applications field value if set, zero value otherwise.
func (o *ResourcesByStatusAndTypeSummary) GetApplications() ApplicationsByStatusSummary {
	if o == nil || o.Applications == nil {
		var ret ApplicationsByStatusSummary
		return ret
	}
	return *o.Applications
}

// GetApplicationsOk returns a tuple with the Applications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourcesByStatusAndTypeSummary) GetApplicationsOk() (*ApplicationsByStatusSummary, bool) {
	if o == nil || o.Applications == nil {
		return nil, false
	}
	return o.Applications, true
}

// HasApplications returns a boolean if a field has been set.
func (o *ResourcesByStatusAndTypeSummary) HasApplications() bool {
	if o != nil && o.Applications != nil {
		return true
	}

	return false
}

// SetApplications gets a reference to the given ApplicationsByStatusSummary and assigns it to the Applications field.
func (o *ResourcesByStatusAndTypeSummary) SetApplications(v ApplicationsByStatusSummary) {
	o.Applications = &v
}

// GetStatements returns the Statements field value if set, zero value otherwise.
func (o *ResourcesByStatusAndTypeSummary) GetStatements() StatementsByStatusSummary {
	if o == nil || o.Statements == nil {
		var ret StatementsByStatusSummary
		return ret
	}
	return *o.Statements
}

// GetStatementsOk returns a tuple with the Statements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourcesByStatusAndTypeSummary) GetStatementsOk() (*StatementsByStatusSummary, bool) {
	if o == nil || o.Statements == nil {
		return nil, false
	}
	return o.Statements, true
}

// HasStatements returns a boolean if a field has been set.
func (o *ResourcesByStatusAndTypeSummary) HasStatements() bool {
	if o != nil && o.Statements != nil {
		return true
	}

	return false
}

// SetStatements gets a reference to the given StatementsByStatusSummary and assigns it to the Statements field.
func (o *ResourcesByStatusAndTypeSummary) SetStatements(v StatementsByStatusSummary) {
	o.Statements = &v
}

func (o ResourcesByStatusAndTypeSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Applications != nil {
		toSerialize["applications"] = o.Applications
	}
	if o.Statements != nil {
		toSerialize["statements"] = o.Statements
	}
	return json.Marshal(toSerialize)
}

type NullableResourcesByStatusAndTypeSummary struct {
	value *ResourcesByStatusAndTypeSummary
	isSet bool
}

func (v NullableResourcesByStatusAndTypeSummary) Get() *ResourcesByStatusAndTypeSummary {
	return v.value
}

func (v *NullableResourcesByStatusAndTypeSummary) Set(val *ResourcesByStatusAndTypeSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableResourcesByStatusAndTypeSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableResourcesByStatusAndTypeSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourcesByStatusAndTypeSummary(val *ResourcesByStatusAndTypeSummary) *NullableResourcesByStatusAndTypeSummary {
	return &NullableResourcesByStatusAndTypeSummary{value: val, isSet: true}
}

func (v NullableResourcesByStatusAndTypeSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourcesByStatusAndTypeSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


