/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// Savepoint Represents a Savepoint for a Flink Application or Statement
type Savepoint struct {
	// API version for spec
	ApiVersion string `json:"apiVersion"`
	// Kind of resource - set to resource type
	Kind string `json:"kind"`
	Metadata SavepointMetadata `json:"metadata"`
	Spec SavepointSpec `json:"spec"`
	Status *SavepointStatus `json:"status,omitempty"`
}

// NewSavepoint instantiates a new Savepoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSavepoint(apiVersion string, kind string, metadata SavepointMetadata, spec SavepointSpec) *Savepoint {
	this := Savepoint{}
	this.ApiVersion = apiVersion
	this.Kind = kind
	this.Metadata = metadata
	this.Spec = spec
	return &this
}

// NewSavepointWithDefaults instantiates a new Savepoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSavepointWithDefaults() *Savepoint {
	this := Savepoint{}
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *Savepoint) GetApiVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *Savepoint) GetApiVersionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *Savepoint) SetApiVersion(v string) {
	o.ApiVersion = v
}

// GetKind returns the Kind field value
func (o *Savepoint) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *Savepoint) GetKindOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *Savepoint) SetKind(v string) {
	o.Kind = v
}

// GetMetadata returns the Metadata field value
func (o *Savepoint) GetMetadata() SavepointMetadata {
	if o == nil {
		var ret SavepointMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *Savepoint) GetMetadataOk() (*SavepointMetadata, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *Savepoint) SetMetadata(v SavepointMetadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value
func (o *Savepoint) GetSpec() SavepointSpec {
	if o == nil {
		var ret SavepointSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *Savepoint) GetSpecOk() (*SavepointSpec, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *Savepoint) SetSpec(v SavepointSpec) {
	o.Spec = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Savepoint) GetStatus() SavepointStatus {
	if o == nil || o.Status == nil {
		var ret SavepointStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Savepoint) GetStatusOk() (*SavepointStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Savepoint) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given SavepointStatus and assigns it to the Status field.
func (o *Savepoint) SetStatus(v SavepointStatus) {
	o.Status = &v
}

func (o Savepoint) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["metadata"] = o.Metadata
	}
	if true {
		toSerialize["spec"] = o.Spec
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableSavepoint struct {
	value *Savepoint
	isSet bool
}

func (v NullableSavepoint) Get() *Savepoint {
	return v.value
}

func (v *NullableSavepoint) Set(val *Savepoint) {
	v.value = val
	v.isSet = true
}

func (v NullableSavepoint) IsSet() bool {
	return v.isSet
}

func (v *NullableSavepoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSavepoint(val *Savepoint) *NullableSavepoint {
	return &NullableSavepoint{value: val, isSet: true}
}

func (v NullableSavepoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSavepoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


