/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// KubernetesClusterAllOf struct for KubernetesClusterAllOf
type KubernetesClusterAllOf struct {
	Metadata KubernetesClusterMetadata `json:"metadata"`
	Spec KubernetesClusterSpec `json:"spec"`
	Status *KubernetesClusterStatus `json:"status,omitempty"`
}

// NewKubernetesClusterAllOf instantiates a new KubernetesClusterAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubernetesClusterAllOf(metadata KubernetesClusterMetadata, spec KubernetesClusterSpec) *KubernetesClusterAllOf {
	this := KubernetesClusterAllOf{}
	this.Metadata = metadata
	this.Spec = spec
	return &this
}

// NewKubernetesClusterAllOfWithDefaults instantiates a new KubernetesClusterAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubernetesClusterAllOfWithDefaults() *KubernetesClusterAllOf {
	this := KubernetesClusterAllOf{}
	return &this
}

// GetMetadata returns the Metadata field value
func (o *KubernetesClusterAllOf) GetMetadata() KubernetesClusterMetadata {
	if o == nil {
		var ret KubernetesClusterMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *KubernetesClusterAllOf) GetMetadataOk() (*KubernetesClusterMetadata, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *KubernetesClusterAllOf) SetMetadata(v KubernetesClusterMetadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value
func (o *KubernetesClusterAllOf) GetSpec() KubernetesClusterSpec {
	if o == nil {
		var ret KubernetesClusterSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *KubernetesClusterAllOf) GetSpecOk() (*KubernetesClusterSpec, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *KubernetesClusterAllOf) SetSpec(v KubernetesClusterSpec) {
	o.Spec = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *KubernetesClusterAllOf) GetStatus() KubernetesClusterStatus {
	if o == nil || o.Status == nil {
		var ret KubernetesClusterStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesClusterAllOf) GetStatusOk() (*KubernetesClusterStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *KubernetesClusterAllOf) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given KubernetesClusterStatus and assigns it to the Status field.
func (o *KubernetesClusterAllOf) SetStatus(v KubernetesClusterStatus) {
	o.Status = &v
}

func (o KubernetesClusterAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["metadata"] = o.Metadata
	}
	if true {
		toSerialize["spec"] = o.Spec
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableKubernetesClusterAllOf struct {
	value *KubernetesClusterAllOf
	isSet bool
}

func (v NullableKubernetesClusterAllOf) Get() *KubernetesClusterAllOf {
	return v.value
}

func (v *NullableKubernetesClusterAllOf) Set(val *KubernetesClusterAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableKubernetesClusterAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableKubernetesClusterAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubernetesClusterAllOf(val *KubernetesClusterAllOf) *NullableKubernetesClusterAllOf {
	return &NullableKubernetesClusterAllOf{value: val, isSet: true}
}

func (v NullableKubernetesClusterAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubernetesClusterAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


