/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// ServiceAccountAllowlistEntryMetadata Metadata about the allowlist entry.
type ServiceAccountAllowlistEntryMetadata struct {
	// The name of the permitted service account.
	Name string `json:"name"`
	// Timestamp at which the entry was added to the allowlist.
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`
}

// NewServiceAccountAllowlistEntryMetadata instantiates a new ServiceAccountAllowlistEntryMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountAllowlistEntryMetadata(name string) *ServiceAccountAllowlistEntryMetadata {
	this := ServiceAccountAllowlistEntryMetadata{}
	this.Name = name
	return &this
}

// NewServiceAccountAllowlistEntryMetadataWithDefaults instantiates a new ServiceAccountAllowlistEntryMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountAllowlistEntryMetadataWithDefaults() *ServiceAccountAllowlistEntryMetadata {
	this := ServiceAccountAllowlistEntryMetadata{}
	return &this
}

// GetName returns the Name field value
func (o *ServiceAccountAllowlistEntryMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServiceAccountAllowlistEntryMetadata) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServiceAccountAllowlistEntryMetadata) SetName(v string) {
	o.Name = v
}

// GetCreationTimestamp returns the CreationTimestamp field value if set, zero value otherwise.
func (o *ServiceAccountAllowlistEntryMetadata) GetCreationTimestamp() string {
	if o == nil || o.CreationTimestamp == nil {
		var ret string
		return ret
	}
	return *o.CreationTimestamp
}

// GetCreationTimestampOk returns a tuple with the CreationTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountAllowlistEntryMetadata) GetCreationTimestampOk() (*string, bool) {
	if o == nil || o.CreationTimestamp == nil {
		return nil, false
	}
	return o.CreationTimestamp, true
}

// HasCreationTimestamp returns a boolean if a field has been set.
func (o *ServiceAccountAllowlistEntryMetadata) HasCreationTimestamp() bool {
	if o != nil && o.CreationTimestamp != nil {
		return true
	}

	return false
}

// SetCreationTimestamp gets a reference to the given string and assigns it to the CreationTimestamp field.
func (o *ServiceAccountAllowlistEntryMetadata) SetCreationTimestamp(v string) {
	o.CreationTimestamp = &v
}

func (o ServiceAccountAllowlistEntryMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.CreationTimestamp != nil {
		toSerialize["creationTimestamp"] = o.CreationTimestamp
	}
	return json.Marshal(toSerialize)
}

type NullableServiceAccountAllowlistEntryMetadata struct {
	value *ServiceAccountAllowlistEntryMetadata
	isSet bool
}

func (v NullableServiceAccountAllowlistEntryMetadata) Get() *ServiceAccountAllowlistEntryMetadata {
	return v.value
}

func (v *NullableServiceAccountAllowlistEntryMetadata) Set(val *ServiceAccountAllowlistEntryMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountAllowlistEntryMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountAllowlistEntryMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountAllowlistEntryMetadata(val *ServiceAccountAllowlistEntryMetadata) *NullableServiceAccountAllowlistEntryMetadata {
	return &NullableServiceAccountAllowlistEntryMetadata{value: val, isSet: true}
}

func (v NullableServiceAccountAllowlistEntryMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountAllowlistEntryMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


