/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// WhoAmi The principal CMF authenticated the current request as, for the cmf-ui SPA to display (e.g. in the top-bar user menu).
type WhoAmi struct {
	// The authenticated principal name -- the JWT subject for token/OIDC/Basic logins, or the mTLS client-certificate subject mapped to a principal. Null when the request is not authenticated (authentication disabled).
	Principal NullableString `json:"principal,omitempty"`
	// How the request was authenticated: \"certificate\" when the identity came from the TLS client certificate, \"token\" when it came from an HTTP credential (a bearer token, a session cookie, or basic credentials). Null when the request is not authenticated. In deployments that combine mTLS with token authentication, a request carrying a token authenticates as the token's principal and reports \"token\"; the client certificate then only secures the transport.
	AuthMethod NullableString `json:"authMethod,omitempty"`
}

// NewWhoAmi instantiates a new WhoAmi object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhoAmi() *WhoAmi {
	this := WhoAmi{}
	return &this
}

// NewWhoAmiWithDefaults instantiates a new WhoAmi object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhoAmiWithDefaults() *WhoAmi {
	this := WhoAmi{}
	return &this
}

// GetPrincipal returns the Principal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WhoAmi) GetPrincipal() string {
	if o == nil || o.Principal.Get() == nil {
		var ret string
		return ret
	}
	return *o.Principal.Get()
}

// GetPrincipalOk returns a tuple with the Principal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WhoAmi) GetPrincipalOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Principal.Get(), o.Principal.IsSet()
}

// HasPrincipal returns a boolean if a field has been set.
func (o *WhoAmi) HasPrincipal() bool {
	if o != nil && o.Principal.IsSet() {
		return true
	}

	return false
}

// SetPrincipal gets a reference to the given NullableString and assigns it to the Principal field.
func (o *WhoAmi) SetPrincipal(v string) {
	o.Principal.Set(&v)
}
// SetPrincipalNil sets the value for Principal to be an explicit nil
func (o *WhoAmi) SetPrincipalNil() {
	o.Principal.Set(nil)
}

// UnsetPrincipal ensures that no value is present for Principal, not even an explicit nil
func (o *WhoAmi) UnsetPrincipal() {
	o.Principal.Unset()
}

// GetAuthMethod returns the AuthMethod field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WhoAmi) GetAuthMethod() string {
	if o == nil || o.AuthMethod.Get() == nil {
		var ret string
		return ret
	}
	return *o.AuthMethod.Get()
}

// GetAuthMethodOk returns a tuple with the AuthMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WhoAmi) GetAuthMethodOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.AuthMethod.Get(), o.AuthMethod.IsSet()
}

// HasAuthMethod returns a boolean if a field has been set.
func (o *WhoAmi) HasAuthMethod() bool {
	if o != nil && o.AuthMethod.IsSet() {
		return true
	}

	return false
}

// SetAuthMethod gets a reference to the given NullableString and assigns it to the AuthMethod field.
func (o *WhoAmi) SetAuthMethod(v string) {
	o.AuthMethod.Set(&v)
}
// SetAuthMethodNil sets the value for AuthMethod to be an explicit nil
func (o *WhoAmi) SetAuthMethodNil() {
	o.AuthMethod.Set(nil)
}

// UnsetAuthMethod ensures that no value is present for AuthMethod, not even an explicit nil
func (o *WhoAmi) UnsetAuthMethod() {
	o.AuthMethod.Unset()
}

func (o WhoAmi) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Principal.IsSet() {
		toSerialize["principal"] = o.Principal.Get()
	}
	if o.AuthMethod.IsSet() {
		toSerialize["authMethod"] = o.AuthMethod.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableWhoAmi struct {
	value *WhoAmi
	isSet bool
}

func (v NullableWhoAmi) Get() *WhoAmi {
	return v.value
}

func (v *NullableWhoAmi) Set(val *WhoAmi) {
	v.value = val
	v.isSet = true
}

func (v NullableWhoAmi) IsSet() bool {
	return v.isSet
}

func (v *NullableWhoAmi) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhoAmi(val *WhoAmi) *NullableWhoAmi {
	return &NullableWhoAmi{value: val, isSet: true}
}

func (v NullableWhoAmi) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhoAmi) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


