/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// Sort struct for Sort
type Sort struct {
	// Whether the results are sorted.
	Sorted *bool `json:"sorted,omitempty"`
	// Whether the results are unsorted.
	Unsorted *bool `json:"unsorted,omitempty"`
	Empty *bool `json:"empty,omitempty"`
}

// NewSort instantiates a new Sort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSort() *Sort {
	this := Sort{}
	return &this
}

// NewSortWithDefaults instantiates a new Sort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSortWithDefaults() *Sort {
	this := Sort{}
	return &this
}

// GetSorted returns the Sorted field value if set, zero value otherwise.
func (o *Sort) GetSorted() bool {
	if o == nil || o.Sorted == nil {
		var ret bool
		return ret
	}
	return *o.Sorted
}

// GetSortedOk returns a tuple with the Sorted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sort) GetSortedOk() (*bool, bool) {
	if o == nil || o.Sorted == nil {
		return nil, false
	}
	return o.Sorted, true
}

// HasSorted returns a boolean if a field has been set.
func (o *Sort) HasSorted() bool {
	if o != nil && o.Sorted != nil {
		return true
	}

	return false
}

// SetSorted gets a reference to the given bool and assigns it to the Sorted field.
func (o *Sort) SetSorted(v bool) {
	o.Sorted = &v
}

// GetUnsorted returns the Unsorted field value if set, zero value otherwise.
func (o *Sort) GetUnsorted() bool {
	if o == nil || o.Unsorted == nil {
		var ret bool
		return ret
	}
	return *o.Unsorted
}

// GetUnsortedOk returns a tuple with the Unsorted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sort) GetUnsortedOk() (*bool, bool) {
	if o == nil || o.Unsorted == nil {
		return nil, false
	}
	return o.Unsorted, true
}

// HasUnsorted returns a boolean if a field has been set.
func (o *Sort) HasUnsorted() bool {
	if o != nil && o.Unsorted != nil {
		return true
	}

	return false
}

// SetUnsorted gets a reference to the given bool and assigns it to the Unsorted field.
func (o *Sort) SetUnsorted(v bool) {
	o.Unsorted = &v
}

// GetEmpty returns the Empty field value if set, zero value otherwise.
func (o *Sort) GetEmpty() bool {
	if o == nil || o.Empty == nil {
		var ret bool
		return ret
	}
	return *o.Empty
}

// GetEmptyOk returns a tuple with the Empty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Sort) GetEmptyOk() (*bool, bool) {
	if o == nil || o.Empty == nil {
		return nil, false
	}
	return o.Empty, true
}

// HasEmpty returns a boolean if a field has been set.
func (o *Sort) HasEmpty() bool {
	if o != nil && o.Empty != nil {
		return true
	}

	return false
}

// SetEmpty gets a reference to the given bool and assigns it to the Empty field.
func (o *Sort) SetEmpty(v bool) {
	o.Empty = &v
}

func (o Sort) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Sorted != nil {
		toSerialize["sorted"] = o.Sorted
	}
	if o.Unsorted != nil {
		toSerialize["unsorted"] = o.Unsorted
	}
	if o.Empty != nil {
		toSerialize["empty"] = o.Empty
	}
	return json.Marshal(toSerialize)
}

type NullableSort struct {
	value *Sort
	isSet bool
}

func (v NullableSort) Get() *Sort {
	return v.value
}

func (v *NullableSort) Set(val *Sort) {
	v.value = val
	v.isSet = true
}

func (v NullableSort) IsSet() bool {
	return v.isSet
}

func (v *NullableSort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSort(val *Sort) *NullableSort {
	return &NullableSort{value: val, isSet: true}
}

func (v NullableSort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


