/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// ApplicationInstanceMetadata Metadata about the instance
type ApplicationInstanceMetadata struct {
	// Name of the Instance - a uuid.
	Name *string `json:"name,omitempty"`
	// Unique identifier of the instance. Identical to name.
	Uid *string `json:"uid,omitempty"`
	// Timestamp when the Instance was created
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`
	// Timestamp when the Instance status was last updated
	UpdateTimestamp *string `json:"updateTimestamp,omitempty"`
	// Labels of the instance
	Labels *map[string]string `json:"labels,omitempty"`
	// Annotations of the instance
	Annotations *map[string]string `json:"annotations,omitempty"`
}

// NewApplicationInstanceMetadata instantiates a new ApplicationInstanceMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationInstanceMetadata() *ApplicationInstanceMetadata {
	this := ApplicationInstanceMetadata{}
	return &this
}

// NewApplicationInstanceMetadataWithDefaults instantiates a new ApplicationInstanceMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationInstanceMetadataWithDefaults() *ApplicationInstanceMetadata {
	this := ApplicationInstanceMetadata{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApplicationInstanceMetadata) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceMetadata) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApplicationInstanceMetadata) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApplicationInstanceMetadata) SetName(v string) {
	o.Name = &v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *ApplicationInstanceMetadata) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceMetadata) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *ApplicationInstanceMetadata) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *ApplicationInstanceMetadata) SetUid(v string) {
	o.Uid = &v
}

// GetCreationTimestamp returns the CreationTimestamp field value if set, zero value otherwise.
func (o *ApplicationInstanceMetadata) GetCreationTimestamp() string {
	if o == nil || o.CreationTimestamp == nil {
		var ret string
		return ret
	}
	return *o.CreationTimestamp
}

// GetCreationTimestampOk returns a tuple with the CreationTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceMetadata) GetCreationTimestampOk() (*string, bool) {
	if o == nil || o.CreationTimestamp == nil {
		return nil, false
	}
	return o.CreationTimestamp, true
}

// HasCreationTimestamp returns a boolean if a field has been set.
func (o *ApplicationInstanceMetadata) HasCreationTimestamp() bool {
	if o != nil && o.CreationTimestamp != nil {
		return true
	}

	return false
}

// SetCreationTimestamp gets a reference to the given string and assigns it to the CreationTimestamp field.
func (o *ApplicationInstanceMetadata) SetCreationTimestamp(v string) {
	o.CreationTimestamp = &v
}

// GetUpdateTimestamp returns the UpdateTimestamp field value if set, zero value otherwise.
func (o *ApplicationInstanceMetadata) GetUpdateTimestamp() string {
	if o == nil || o.UpdateTimestamp == nil {
		var ret string
		return ret
	}
	return *o.UpdateTimestamp
}

// GetUpdateTimestampOk returns a tuple with the UpdateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceMetadata) GetUpdateTimestampOk() (*string, bool) {
	if o == nil || o.UpdateTimestamp == nil {
		return nil, false
	}
	return o.UpdateTimestamp, true
}

// HasUpdateTimestamp returns a boolean if a field has been set.
func (o *ApplicationInstanceMetadata) HasUpdateTimestamp() bool {
	if o != nil && o.UpdateTimestamp != nil {
		return true
	}

	return false
}

// SetUpdateTimestamp gets a reference to the given string and assigns it to the UpdateTimestamp field.
func (o *ApplicationInstanceMetadata) SetUpdateTimestamp(v string) {
	o.UpdateTimestamp = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ApplicationInstanceMetadata) GetLabels() map[string]string {
	if o == nil || o.Labels == nil {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceMetadata) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ApplicationInstanceMetadata) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ApplicationInstanceMetadata) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *ApplicationInstanceMetadata) GetAnnotations() map[string]string {
	if o == nil || o.Annotations == nil {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplicationInstanceMetadata) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || o.Annotations == nil {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *ApplicationInstanceMetadata) HasAnnotations() bool {
	if o != nil && o.Annotations != nil {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *ApplicationInstanceMetadata) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

func (o ApplicationInstanceMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if o.CreationTimestamp != nil {
		toSerialize["creationTimestamp"] = o.CreationTimestamp
	}
	if o.UpdateTimestamp != nil {
		toSerialize["updateTimestamp"] = o.UpdateTimestamp
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Annotations != nil {
		toSerialize["annotations"] = o.Annotations
	}
	return json.Marshal(toSerialize)
}

type NullableApplicationInstanceMetadata struct {
	value *ApplicationInstanceMetadata
	isSet bool
}

func (v NullableApplicationInstanceMetadata) Get() *ApplicationInstanceMetadata {
	return v.value
}

func (v *NullableApplicationInstanceMetadata) Set(val *ApplicationInstanceMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationInstanceMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationInstanceMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationInstanceMetadata(val *ApplicationInstanceMetadata) *NullableApplicationInstanceMetadata {
	return &NullableApplicationInstanceMetadata{value: val, isSet: true}
}

func (v NullableApplicationInstanceMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationInstanceMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


