/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// CatalogPageMetadata struct for CatalogPageMetadata
type CatalogPageMetadata struct {
	Size *int64 `json:"size,omitempty"`
}

// NewCatalogPageMetadata instantiates a new CatalogPageMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCatalogPageMetadata() *CatalogPageMetadata {
	this := CatalogPageMetadata{}
	var size int64 = 0
	this.Size = &size
	return &this
}

// NewCatalogPageMetadataWithDefaults instantiates a new CatalogPageMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCatalogPageMetadataWithDefaults() *CatalogPageMetadata {
	this := CatalogPageMetadata{}
	var size int64 = 0
	this.Size = &size
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *CatalogPageMetadata) GetSize() int64 {
	if o == nil || o.Size == nil {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CatalogPageMetadata) GetSizeOk() (*int64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *CatalogPageMetadata) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *CatalogPageMetadata) SetSize(v int64) {
	o.Size = &v
}

func (o CatalogPageMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	return json.Marshal(toSerialize)
}

type NullableCatalogPageMetadata struct {
	value *CatalogPageMetadata
	isSet bool
}

func (v NullableCatalogPageMetadata) Get() *CatalogPageMetadata {
	return v.value
}

func (v *NullableCatalogPageMetadata) Set(val *CatalogPageMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableCatalogPageMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableCatalogPageMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCatalogPageMetadata(val *CatalogPageMetadata) *NullableCatalogPageMetadata {
	return &NullableCatalogPageMetadata{value: val, isSet: true}
}

func (v NullableCatalogPageMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCatalogPageMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


