/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// StatementsByStatusSummary Summary of statements by status
type StatementsByStatusSummary struct {
}

// NewStatementsByStatusSummary instantiates a new StatementsByStatusSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatementsByStatusSummary() *StatementsByStatusSummary {
	this := StatementsByStatusSummary{}
	return &this
}

// NewStatementsByStatusSummaryWithDefaults instantiates a new StatementsByStatusSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatementsByStatusSummaryWithDefaults() *StatementsByStatusSummary {
	this := StatementsByStatusSummary{}
	return &this
}

func (o StatementsByStatusSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableStatementsByStatusSummary struct {
	value *StatementsByStatusSummary
	isSet bool
}

func (v NullableStatementsByStatusSummary) Get() *StatementsByStatusSummary {
	return v.value
}

func (v *NullableStatementsByStatusSummary) Set(val *StatementsByStatusSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableStatementsByStatusSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableStatementsByStatusSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatementsByStatusSummary(val *StatementsByStatusSummary) *NullableStatementsByStatusSummary {
	return &NullableStatementsByStatusSummary{value: val, isSet: true}
}

func (v NullableStatementsByStatusSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatementsByStatusSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


