/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// KubernetesClusterSpec Specification for the Kubernetes cluster.
type KubernetesClusterSpec struct {
	// The desired lifecycle state of the cluster.
	LifecycleState *string `json:"lifecycleState,omitempty"`
}

// NewKubernetesClusterSpec instantiates a new KubernetesClusterSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubernetesClusterSpec() *KubernetesClusterSpec {
	this := KubernetesClusterSpec{}
	return &this
}

// NewKubernetesClusterSpecWithDefaults instantiates a new KubernetesClusterSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubernetesClusterSpecWithDefaults() *KubernetesClusterSpec {
	this := KubernetesClusterSpec{}
	return &this
}

// GetLifecycleState returns the LifecycleState field value if set, zero value otherwise.
func (o *KubernetesClusterSpec) GetLifecycleState() string {
	if o == nil || o.LifecycleState == nil {
		var ret string
		return ret
	}
	return *o.LifecycleState
}

// GetLifecycleStateOk returns a tuple with the LifecycleState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesClusterSpec) GetLifecycleStateOk() (*string, bool) {
	if o == nil || o.LifecycleState == nil {
		return nil, false
	}
	return o.LifecycleState, true
}

// HasLifecycleState returns a boolean if a field has been set.
func (o *KubernetesClusterSpec) HasLifecycleState() bool {
	if o != nil && o.LifecycleState != nil {
		return true
	}

	return false
}

// SetLifecycleState gets a reference to the given string and assigns it to the LifecycleState field.
func (o *KubernetesClusterSpec) SetLifecycleState(v string) {
	o.LifecycleState = &v
}

func (o KubernetesClusterSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.LifecycleState != nil {
		toSerialize["lifecycleState"] = o.LifecycleState
	}
	return json.Marshal(toSerialize)
}

type NullableKubernetesClusterSpec struct {
	value *KubernetesClusterSpec
	isSet bool
}

func (v NullableKubernetesClusterSpec) Get() *KubernetesClusterSpec {
	return v.value
}

func (v *NullableKubernetesClusterSpec) Set(val *KubernetesClusterSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableKubernetesClusterSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableKubernetesClusterSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubernetesClusterSpec(val *KubernetesClusterSpec) *NullableKubernetesClusterSpec {
	return &NullableKubernetesClusterSpec{value: val, isSet: true}
}

func (v NullableKubernetesClusterSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubernetesClusterSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


