/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// KafkaCatalogsPageAllOf struct for KafkaCatalogsPageAllOf
type KafkaCatalogsPageAllOf struct {
	Metadata *CatalogPageMetadata `json:"metadata,omitempty"`
	Items *[]KafkaCatalog `json:"items,omitempty"`
}

// NewKafkaCatalogsPageAllOf instantiates a new KafkaCatalogsPageAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaCatalogsPageAllOf() *KafkaCatalogsPageAllOf {
	this := KafkaCatalogsPageAllOf{}
	return &this
}

// NewKafkaCatalogsPageAllOfWithDefaults instantiates a new KafkaCatalogsPageAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaCatalogsPageAllOfWithDefaults() *KafkaCatalogsPageAllOf {
	this := KafkaCatalogsPageAllOf{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *KafkaCatalogsPageAllOf) GetMetadata() CatalogPageMetadata {
	if o == nil || o.Metadata == nil {
		var ret CatalogPageMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaCatalogsPageAllOf) GetMetadataOk() (*CatalogPageMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *KafkaCatalogsPageAllOf) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given CatalogPageMetadata and assigns it to the Metadata field.
func (o *KafkaCatalogsPageAllOf) SetMetadata(v CatalogPageMetadata) {
	o.Metadata = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *KafkaCatalogsPageAllOf) GetItems() []KafkaCatalog {
	if o == nil || o.Items == nil {
		var ret []KafkaCatalog
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaCatalogsPageAllOf) GetItemsOk() (*[]KafkaCatalog, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *KafkaCatalogsPageAllOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []KafkaCatalog and assigns it to the Items field.
func (o *KafkaCatalogsPageAllOf) SetItems(v []KafkaCatalog) {
	o.Items = &v
}

func (o KafkaCatalogsPageAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableKafkaCatalogsPageAllOf struct {
	value *KafkaCatalogsPageAllOf
	isSet bool
}

func (v NullableKafkaCatalogsPageAllOf) Get() *KafkaCatalogsPageAllOf {
	return v.value
}

func (v *NullableKafkaCatalogsPageAllOf) Set(val *KafkaCatalogsPageAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaCatalogsPageAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaCatalogsPageAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaCatalogsPageAllOf(val *KafkaCatalogsPageAllOf) *NullableKafkaCatalogsPageAllOf {
	return &NullableKafkaCatalogsPageAllOf{value: val, isSet: true}
}

func (v NullableKafkaCatalogsPageAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaCatalogsPageAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


