/*
 * Confluent Manager for Apache Flink / CMF
 *
 * Apache Flink job lifecycle management component for Confluent Platform.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1
// ApplicationsPage struct for ApplicationsPage
type ApplicationsPage struct {
	Pageable Pageable `json:"pageable,omitempty"`
	Metadata ApplicationPageMetadata `json:"metadata,omitempty"`
	Items []Application `json:"items,omitempty"`
}
