/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// StatementsPageAllOf struct for StatementsPageAllOf
type StatementsPageAllOf struct {
	Metadata *StatementPageMetadata `json:"metadata,omitempty"`
	Items *[]Statement `json:"items,omitempty"`
}

// NewStatementsPageAllOf instantiates a new StatementsPageAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatementsPageAllOf() *StatementsPageAllOf {
	this := StatementsPageAllOf{}
	return &this
}

// NewStatementsPageAllOfWithDefaults instantiates a new StatementsPageAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatementsPageAllOfWithDefaults() *StatementsPageAllOf {
	this := StatementsPageAllOf{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *StatementsPageAllOf) GetMetadata() StatementPageMetadata {
	if o == nil || o.Metadata == nil {
		var ret StatementPageMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementsPageAllOf) GetMetadataOk() (*StatementPageMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *StatementsPageAllOf) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given StatementPageMetadata and assigns it to the Metadata field.
func (o *StatementsPageAllOf) SetMetadata(v StatementPageMetadata) {
	o.Metadata = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *StatementsPageAllOf) GetItems() []Statement {
	if o == nil || o.Items == nil {
		var ret []Statement
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementsPageAllOf) GetItemsOk() (*[]Statement, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *StatementsPageAllOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Statement and assigns it to the Items field.
func (o *StatementsPageAllOf) SetItems(v []Statement) {
	o.Items = &v
}

func (o StatementsPageAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableStatementsPageAllOf struct {
	value *StatementsPageAllOf
	isSet bool
}

func (v NullableStatementsPageAllOf) Get() *StatementsPageAllOf {
	return v.value
}

func (v *NullableStatementsPageAllOf) Set(val *StatementsPageAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableStatementsPageAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableStatementsPageAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatementsPageAllOf(val *StatementsPageAllOf) *NullableStatementsPageAllOf {
	return &NullableStatementsPageAllOf{value: val, isSet: true}
}

func (v NullableStatementsPageAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatementsPageAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


