/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// AuthConfig Authentication/authorization configuration advertised to the cmf-ui SPA so it can decide whether and how to log in before it holds a token.
type AuthConfig struct {
	// Whether incoming requests are authenticated by CMF.
	AuthnEnabled *bool `json:"authnEnabled,omitempty"`
	// Whether CMF enforces fine-grained Flink authorization (RBAC).
	AuthzEnabled *bool `json:"authzEnabled,omitempty"`
	// Whether an OIDC/SSO login flow is available, advertised so the SPA shows the SSO login affordance. Set via cmf.ui.auth.sso-enabled; only meaningful when authnEnabled is true.
	SsoEnabled *bool `json:"ssoEnabled,omitempty"`
	// Whether a Basic username/password login flow is available, advertised so the SPA shows the username/password form. Set via cmf.ui.auth.basic-auth-enabled; only meaningful when authnEnabled is true.
	BasicAuthEnabled *bool `json:"basicAuthEnabled,omitempty"`
	// Maximum lifetime, in seconds, of a token issued by the login flow, used to schedule client-side refresh. Sourced from cmf.ui.auth.token-max-life-seconds; null until then.
	TokenMaxLifeSeconds *int64 `json:"tokenMaxLifeSeconds,omitempty"`
}

// NewAuthConfig instantiates a new AuthConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthConfig() *AuthConfig {
	this := AuthConfig{}
	return &this
}

// NewAuthConfigWithDefaults instantiates a new AuthConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthConfigWithDefaults() *AuthConfig {
	this := AuthConfig{}
	return &this
}

// GetAuthnEnabled returns the AuthnEnabled field value if set, zero value otherwise.
func (o *AuthConfig) GetAuthnEnabled() bool {
	if o == nil || o.AuthnEnabled == nil {
		var ret bool
		return ret
	}
	return *o.AuthnEnabled
}

// GetAuthnEnabledOk returns a tuple with the AuthnEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfig) GetAuthnEnabledOk() (*bool, bool) {
	if o == nil || o.AuthnEnabled == nil {
		return nil, false
	}
	return o.AuthnEnabled, true
}

// HasAuthnEnabled returns a boolean if a field has been set.
func (o *AuthConfig) HasAuthnEnabled() bool {
	if o != nil && o.AuthnEnabled != nil {
		return true
	}

	return false
}

// SetAuthnEnabled gets a reference to the given bool and assigns it to the AuthnEnabled field.
func (o *AuthConfig) SetAuthnEnabled(v bool) {
	o.AuthnEnabled = &v
}

// GetAuthzEnabled returns the AuthzEnabled field value if set, zero value otherwise.
func (o *AuthConfig) GetAuthzEnabled() bool {
	if o == nil || o.AuthzEnabled == nil {
		var ret bool
		return ret
	}
	return *o.AuthzEnabled
}

// GetAuthzEnabledOk returns a tuple with the AuthzEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfig) GetAuthzEnabledOk() (*bool, bool) {
	if o == nil || o.AuthzEnabled == nil {
		return nil, false
	}
	return o.AuthzEnabled, true
}

// HasAuthzEnabled returns a boolean if a field has been set.
func (o *AuthConfig) HasAuthzEnabled() bool {
	if o != nil && o.AuthzEnabled != nil {
		return true
	}

	return false
}

// SetAuthzEnabled gets a reference to the given bool and assigns it to the AuthzEnabled field.
func (o *AuthConfig) SetAuthzEnabled(v bool) {
	o.AuthzEnabled = &v
}

// GetSsoEnabled returns the SsoEnabled field value if set, zero value otherwise.
func (o *AuthConfig) GetSsoEnabled() bool {
	if o == nil || o.SsoEnabled == nil {
		var ret bool
		return ret
	}
	return *o.SsoEnabled
}

// GetSsoEnabledOk returns a tuple with the SsoEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfig) GetSsoEnabledOk() (*bool, bool) {
	if o == nil || o.SsoEnabled == nil {
		return nil, false
	}
	return o.SsoEnabled, true
}

// HasSsoEnabled returns a boolean if a field has been set.
func (o *AuthConfig) HasSsoEnabled() bool {
	if o != nil && o.SsoEnabled != nil {
		return true
	}

	return false
}

// SetSsoEnabled gets a reference to the given bool and assigns it to the SsoEnabled field.
func (o *AuthConfig) SetSsoEnabled(v bool) {
	o.SsoEnabled = &v
}

// GetBasicAuthEnabled returns the BasicAuthEnabled field value if set, zero value otherwise.
func (o *AuthConfig) GetBasicAuthEnabled() bool {
	if o == nil || o.BasicAuthEnabled == nil {
		var ret bool
		return ret
	}
	return *o.BasicAuthEnabled
}

// GetBasicAuthEnabledOk returns a tuple with the BasicAuthEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfig) GetBasicAuthEnabledOk() (*bool, bool) {
	if o == nil || o.BasicAuthEnabled == nil {
		return nil, false
	}
	return o.BasicAuthEnabled, true
}

// HasBasicAuthEnabled returns a boolean if a field has been set.
func (o *AuthConfig) HasBasicAuthEnabled() bool {
	if o != nil && o.BasicAuthEnabled != nil {
		return true
	}

	return false
}

// SetBasicAuthEnabled gets a reference to the given bool and assigns it to the BasicAuthEnabled field.
func (o *AuthConfig) SetBasicAuthEnabled(v bool) {
	o.BasicAuthEnabled = &v
}

// GetTokenMaxLifeSeconds returns the TokenMaxLifeSeconds field value if set, zero value otherwise.
func (o *AuthConfig) GetTokenMaxLifeSeconds() int64 {
	if o == nil || o.TokenMaxLifeSeconds == nil {
		var ret int64
		return ret
	}
	return *o.TokenMaxLifeSeconds
}

// GetTokenMaxLifeSecondsOk returns a tuple with the TokenMaxLifeSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfig) GetTokenMaxLifeSecondsOk() (*int64, bool) {
	if o == nil || o.TokenMaxLifeSeconds == nil {
		return nil, false
	}
	return o.TokenMaxLifeSeconds, true
}

// HasTokenMaxLifeSeconds returns a boolean if a field has been set.
func (o *AuthConfig) HasTokenMaxLifeSeconds() bool {
	if o != nil && o.TokenMaxLifeSeconds != nil {
		return true
	}

	return false
}

// SetTokenMaxLifeSeconds gets a reference to the given int64 and assigns it to the TokenMaxLifeSeconds field.
func (o *AuthConfig) SetTokenMaxLifeSeconds(v int64) {
	o.TokenMaxLifeSeconds = &v
}

func (o AuthConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AuthnEnabled != nil {
		toSerialize["authnEnabled"] = o.AuthnEnabled
	}
	if o.AuthzEnabled != nil {
		toSerialize["authzEnabled"] = o.AuthzEnabled
	}
	if o.SsoEnabled != nil {
		toSerialize["ssoEnabled"] = o.SsoEnabled
	}
	if o.BasicAuthEnabled != nil {
		toSerialize["basicAuthEnabled"] = o.BasicAuthEnabled
	}
	if o.TokenMaxLifeSeconds != nil {
		toSerialize["tokenMaxLifeSeconds"] = o.TokenMaxLifeSeconds
	}
	return json.Marshal(toSerialize)
}

type NullableAuthConfig struct {
	value *AuthConfig
	isSet bool
}

func (v NullableAuthConfig) Get() *AuthConfig {
	return v.value
}

func (v *NullableAuthConfig) Set(val *AuthConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthConfig(val *AuthConfig) *NullableAuthConfig {
	return &NullableAuthConfig{value: val, isSet: true}
}

func (v NullableAuthConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


