/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// SecretSpec Spec for secret
type SecretSpec struct {
	// Data of the secret
	Data *map[string]string `json:"data,omitempty"`
}

// NewSecretSpec instantiates a new SecretSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretSpec() *SecretSpec {
	this := SecretSpec{}
	return &this
}

// NewSecretSpecWithDefaults instantiates a new SecretSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretSpecWithDefaults() *SecretSpec {
	this := SecretSpec{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *SecretSpec) GetData() map[string]string {
	if o == nil || o.Data == nil {
		var ret map[string]string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretSpec) GetDataOk() (*map[string]string, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *SecretSpec) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]string and assigns it to the Data field.
func (o *SecretSpec) SetData(v map[string]string) {
	o.Data = &v
}

func (o SecretSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableSecretSpec struct {
	value *SecretSpec
	isSet bool
}

func (v NullableSecretSpec) Get() *SecretSpec {
	return v.value
}

func (v *NullableSecretSpec) Set(val *SecretSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretSpec(val *SecretSpec) *NullableSecretSpec {
	return &NullableSecretSpec{value: val, isSet: true}
}

func (v NullableSecretSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


