/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// EnvironmentMetadata Metadata about the Environment
type EnvironmentMetadata struct {
	// Name of the Environment
	Name string `json:"name"`
	// Timestamp when the Environment was created
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`
	// Timestamp when the Environment was updated the last time
	UpdateTimestamp *string `json:"updateTimestamp,omitempty"`
	// Labels of the Environment
	Labels *map[string]string `json:"labels,omitempty"`
	// Annotations of the Environment
	Annotations *map[string]string `json:"annotations,omitempty"`
}

// NewEnvironmentMetadata instantiates a new EnvironmentMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentMetadata(name string) *EnvironmentMetadata {
	this := EnvironmentMetadata{}
	this.Name = name
	return &this
}

// NewEnvironmentMetadataWithDefaults instantiates a new EnvironmentMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentMetadataWithDefaults() *EnvironmentMetadata {
	this := EnvironmentMetadata{}
	return &this
}

// GetName returns the Name field value
func (o *EnvironmentMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EnvironmentMetadata) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EnvironmentMetadata) SetName(v string) {
	o.Name = v
}

// GetCreationTimestamp returns the CreationTimestamp field value if set, zero value otherwise.
func (o *EnvironmentMetadata) GetCreationTimestamp() string {
	if o == nil || o.CreationTimestamp == nil {
		var ret string
		return ret
	}
	return *o.CreationTimestamp
}

// GetCreationTimestampOk returns a tuple with the CreationTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentMetadata) GetCreationTimestampOk() (*string, bool) {
	if o == nil || o.CreationTimestamp == nil {
		return nil, false
	}
	return o.CreationTimestamp, true
}

// HasCreationTimestamp returns a boolean if a field has been set.
func (o *EnvironmentMetadata) HasCreationTimestamp() bool {
	if o != nil && o.CreationTimestamp != nil {
		return true
	}

	return false
}

// SetCreationTimestamp gets a reference to the given string and assigns it to the CreationTimestamp field.
func (o *EnvironmentMetadata) SetCreationTimestamp(v string) {
	o.CreationTimestamp = &v
}

// GetUpdateTimestamp returns the UpdateTimestamp field value if set, zero value otherwise.
func (o *EnvironmentMetadata) GetUpdateTimestamp() string {
	if o == nil || o.UpdateTimestamp == nil {
		var ret string
		return ret
	}
	return *o.UpdateTimestamp
}

// GetUpdateTimestampOk returns a tuple with the UpdateTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentMetadata) GetUpdateTimestampOk() (*string, bool) {
	if o == nil || o.UpdateTimestamp == nil {
		return nil, false
	}
	return o.UpdateTimestamp, true
}

// HasUpdateTimestamp returns a boolean if a field has been set.
func (o *EnvironmentMetadata) HasUpdateTimestamp() bool {
	if o != nil && o.UpdateTimestamp != nil {
		return true
	}

	return false
}

// SetUpdateTimestamp gets a reference to the given string and assigns it to the UpdateTimestamp field.
func (o *EnvironmentMetadata) SetUpdateTimestamp(v string) {
	o.UpdateTimestamp = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *EnvironmentMetadata) GetLabels() map[string]string {
	if o == nil || o.Labels == nil {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentMetadata) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || o.Labels == nil {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *EnvironmentMetadata) HasLabels() bool {
	if o != nil && o.Labels != nil {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *EnvironmentMetadata) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *EnvironmentMetadata) GetAnnotations() map[string]string {
	if o == nil || o.Annotations == nil {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentMetadata) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || o.Annotations == nil {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *EnvironmentMetadata) HasAnnotations() bool {
	if o != nil && o.Annotations != nil {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *EnvironmentMetadata) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

func (o EnvironmentMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.CreationTimestamp != nil {
		toSerialize["creationTimestamp"] = o.CreationTimestamp
	}
	if o.UpdateTimestamp != nil {
		toSerialize["updateTimestamp"] = o.UpdateTimestamp
	}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Annotations != nil {
		toSerialize["annotations"] = o.Annotations
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentMetadata struct {
	value *EnvironmentMetadata
	isSet bool
}

func (v NullableEnvironmentMetadata) Get() *EnvironmentMetadata {
	return v.value
}

func (v *NullableEnvironmentMetadata) Set(val *EnvironmentMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentMetadata(val *EnvironmentMetadata) *NullableEnvironmentMetadata {
	return &NullableEnvironmentMetadata{value: val, isSet: true}
}

func (v NullableEnvironmentMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


