/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// ServiceAccountAllowlistEntriesPageAllOf struct for ServiceAccountAllowlistEntriesPageAllOf
type ServiceAccountAllowlistEntriesPageAllOf struct {
	Metadata *ServiceAccountAllowlistEntriesPageMetadata `json:"metadata,omitempty"`
	Items *[]ServiceAccountAllowlistEntry `json:"items,omitempty"`
}

// NewServiceAccountAllowlistEntriesPageAllOf instantiates a new ServiceAccountAllowlistEntriesPageAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceAccountAllowlistEntriesPageAllOf() *ServiceAccountAllowlistEntriesPageAllOf {
	this := ServiceAccountAllowlistEntriesPageAllOf{}
	return &this
}

// NewServiceAccountAllowlistEntriesPageAllOfWithDefaults instantiates a new ServiceAccountAllowlistEntriesPageAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceAccountAllowlistEntriesPageAllOfWithDefaults() *ServiceAccountAllowlistEntriesPageAllOf {
	this := ServiceAccountAllowlistEntriesPageAllOf{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ServiceAccountAllowlistEntriesPageAllOf) GetMetadata() ServiceAccountAllowlistEntriesPageMetadata {
	if o == nil || o.Metadata == nil {
		var ret ServiceAccountAllowlistEntriesPageMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountAllowlistEntriesPageAllOf) GetMetadataOk() (*ServiceAccountAllowlistEntriesPageMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ServiceAccountAllowlistEntriesPageAllOf) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ServiceAccountAllowlistEntriesPageMetadata and assigns it to the Metadata field.
func (o *ServiceAccountAllowlistEntriesPageAllOf) SetMetadata(v ServiceAccountAllowlistEntriesPageMetadata) {
	o.Metadata = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *ServiceAccountAllowlistEntriesPageAllOf) GetItems() []ServiceAccountAllowlistEntry {
	if o == nil || o.Items == nil {
		var ret []ServiceAccountAllowlistEntry
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceAccountAllowlistEntriesPageAllOf) GetItemsOk() (*[]ServiceAccountAllowlistEntry, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *ServiceAccountAllowlistEntriesPageAllOf) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []ServiceAccountAllowlistEntry and assigns it to the Items field.
func (o *ServiceAccountAllowlistEntriesPageAllOf) SetItems(v []ServiceAccountAllowlistEntry) {
	o.Items = &v
}

func (o ServiceAccountAllowlistEntriesPageAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableServiceAccountAllowlistEntriesPageAllOf struct {
	value *ServiceAccountAllowlistEntriesPageAllOf
	isSet bool
}

func (v NullableServiceAccountAllowlistEntriesPageAllOf) Get() *ServiceAccountAllowlistEntriesPageAllOf {
	return v.value
}

func (v *NullableServiceAccountAllowlistEntriesPageAllOf) Set(val *ServiceAccountAllowlistEntriesPageAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceAccountAllowlistEntriesPageAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceAccountAllowlistEntriesPageAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceAccountAllowlistEntriesPageAllOf(val *ServiceAccountAllowlistEntriesPageAllOf) *NullableServiceAccountAllowlistEntriesPageAllOf {
	return &NullableServiceAccountAllowlistEntriesPageAllOf{value: val, isSet: true}
}

func (v NullableServiceAccountAllowlistEntriesPageAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceAccountAllowlistEntriesPageAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


