/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
)

// KubernetesClusterStatus Status of the Kubernetes cluster.
type KubernetesClusterStatus struct {
	// The effective state of the cluster. CONNECTED when the cluster is reachable, DISCONNECTED when unreachable, or DECOMMISSIONED when intentionally taken offline.
	State *string `json:"state,omitempty"`
	// A human-readable message providing details about the current state (e.g., connection error details).
	Message *string `json:"message,omitempty"`
	// Timestamp of the last successful heartbeat check.
	LastHeartbeatTimestamp *time.Time `json:"lastHeartbeatTimestamp,omitempty"`
	// The Kubernetes server version reported by the cluster (e.g., \"v1.28.3\"). Only available when the cluster is CONNECTED.
	KubernetesVersion *string `json:"kubernetesVersion,omitempty"`
}

// NewKubernetesClusterStatus instantiates a new KubernetesClusterStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubernetesClusterStatus() *KubernetesClusterStatus {
	this := KubernetesClusterStatus{}
	return &this
}

// NewKubernetesClusterStatusWithDefaults instantiates a new KubernetesClusterStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubernetesClusterStatusWithDefaults() *KubernetesClusterStatus {
	this := KubernetesClusterStatus{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *KubernetesClusterStatus) GetState() string {
	if o == nil || o.State == nil {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesClusterStatus) GetStateOk() (*string, bool) {
	if o == nil || o.State == nil {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *KubernetesClusterStatus) HasState() bool {
	if o != nil && o.State != nil {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *KubernetesClusterStatus) SetState(v string) {
	o.State = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *KubernetesClusterStatus) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesClusterStatus) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *KubernetesClusterStatus) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *KubernetesClusterStatus) SetMessage(v string) {
	o.Message = &v
}

// GetLastHeartbeatTimestamp returns the LastHeartbeatTimestamp field value if set, zero value otherwise.
func (o *KubernetesClusterStatus) GetLastHeartbeatTimestamp() time.Time {
	if o == nil || o.LastHeartbeatTimestamp == nil {
		var ret time.Time
		return ret
	}
	return *o.LastHeartbeatTimestamp
}

// GetLastHeartbeatTimestampOk returns a tuple with the LastHeartbeatTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesClusterStatus) GetLastHeartbeatTimestampOk() (*time.Time, bool) {
	if o == nil || o.LastHeartbeatTimestamp == nil {
		return nil, false
	}
	return o.LastHeartbeatTimestamp, true
}

// HasLastHeartbeatTimestamp returns a boolean if a field has been set.
func (o *KubernetesClusterStatus) HasLastHeartbeatTimestamp() bool {
	if o != nil && o.LastHeartbeatTimestamp != nil {
		return true
	}

	return false
}

// SetLastHeartbeatTimestamp gets a reference to the given time.Time and assigns it to the LastHeartbeatTimestamp field.
func (o *KubernetesClusterStatus) SetLastHeartbeatTimestamp(v time.Time) {
	o.LastHeartbeatTimestamp = &v
}

// GetKubernetesVersion returns the KubernetesVersion field value if set, zero value otherwise.
func (o *KubernetesClusterStatus) GetKubernetesVersion() string {
	if o == nil || o.KubernetesVersion == nil {
		var ret string
		return ret
	}
	return *o.KubernetesVersion
}

// GetKubernetesVersionOk returns a tuple with the KubernetesVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesClusterStatus) GetKubernetesVersionOk() (*string, bool) {
	if o == nil || o.KubernetesVersion == nil {
		return nil, false
	}
	return o.KubernetesVersion, true
}

// HasKubernetesVersion returns a boolean if a field has been set.
func (o *KubernetesClusterStatus) HasKubernetesVersion() bool {
	if o != nil && o.KubernetesVersion != nil {
		return true
	}

	return false
}

// SetKubernetesVersion gets a reference to the given string and assigns it to the KubernetesVersion field.
func (o *KubernetesClusterStatus) SetKubernetesVersion(v string) {
	o.KubernetesVersion = &v
}

func (o KubernetesClusterStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.State != nil {
		toSerialize["state"] = o.State
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.LastHeartbeatTimestamp != nil {
		toSerialize["lastHeartbeatTimestamp"] = o.LastHeartbeatTimestamp
	}
	if o.KubernetesVersion != nil {
		toSerialize["kubernetesVersion"] = o.KubernetesVersion
	}
	return json.Marshal(toSerialize)
}

type NullableKubernetesClusterStatus struct {
	value *KubernetesClusterStatus
	isSet bool
}

func (v NullableKubernetesClusterStatus) Get() *KubernetesClusterStatus {
	return v.value
}

func (v *NullableKubernetesClusterStatus) Set(val *KubernetesClusterStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableKubernetesClusterStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableKubernetesClusterStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubernetesClusterStatus(val *KubernetesClusterStatus) *NullableKubernetesClusterStatus {
	return &NullableKubernetesClusterStatus{value: val, isSet: true}
}

func (v NullableKubernetesClusterStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubernetesClusterStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


