/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// KafkaDatabaseSpecKafkaCluster Details about the Kafka cluster of the database
type KafkaDatabaseSpecKafkaCluster struct {
	// connection options for the Kafka client
	ConnectionConfig map[string]string `json:"connectionConfig"`
	// an identifier to look up a secret that contains the connection credentials
	ConnectionSecretId *string `json:"connectionSecretId,omitempty"`
}

// NewKafkaDatabaseSpecKafkaCluster instantiates a new KafkaDatabaseSpecKafkaCluster object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaDatabaseSpecKafkaCluster(connectionConfig map[string]string) *KafkaDatabaseSpecKafkaCluster {
	this := KafkaDatabaseSpecKafkaCluster{}
	this.ConnectionConfig = connectionConfig
	return &this
}

// NewKafkaDatabaseSpecKafkaClusterWithDefaults instantiates a new KafkaDatabaseSpecKafkaCluster object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaDatabaseSpecKafkaClusterWithDefaults() *KafkaDatabaseSpecKafkaCluster {
	this := KafkaDatabaseSpecKafkaCluster{}
	return &this
}

// GetConnectionConfig returns the ConnectionConfig field value
func (o *KafkaDatabaseSpecKafkaCluster) GetConnectionConfig() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.ConnectionConfig
}

// GetConnectionConfigOk returns a tuple with the ConnectionConfig field value
// and a boolean to check if the value has been set.
func (o *KafkaDatabaseSpecKafkaCluster) GetConnectionConfigOk() (*map[string]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ConnectionConfig, true
}

// SetConnectionConfig sets field value
func (o *KafkaDatabaseSpecKafkaCluster) SetConnectionConfig(v map[string]string) {
	o.ConnectionConfig = v
}

// GetConnectionSecretId returns the ConnectionSecretId field value if set, zero value otherwise.
func (o *KafkaDatabaseSpecKafkaCluster) GetConnectionSecretId() string {
	if o == nil || o.ConnectionSecretId == nil {
		var ret string
		return ret
	}
	return *o.ConnectionSecretId
}

// GetConnectionSecretIdOk returns a tuple with the ConnectionSecretId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaDatabaseSpecKafkaCluster) GetConnectionSecretIdOk() (*string, bool) {
	if o == nil || o.ConnectionSecretId == nil {
		return nil, false
	}
	return o.ConnectionSecretId, true
}

// HasConnectionSecretId returns a boolean if a field has been set.
func (o *KafkaDatabaseSpecKafkaCluster) HasConnectionSecretId() bool {
	if o != nil && o.ConnectionSecretId != nil {
		return true
	}

	return false
}

// SetConnectionSecretId gets a reference to the given string and assigns it to the ConnectionSecretId field.
func (o *KafkaDatabaseSpecKafkaCluster) SetConnectionSecretId(v string) {
	o.ConnectionSecretId = &v
}

func (o KafkaDatabaseSpecKafkaCluster) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["connectionConfig"] = o.ConnectionConfig
	}
	if o.ConnectionSecretId != nil {
		toSerialize["connectionSecretId"] = o.ConnectionSecretId
	}
	return json.Marshal(toSerialize)
}

type NullableKafkaDatabaseSpecKafkaCluster struct {
	value *KafkaDatabaseSpecKafkaCluster
	isSet bool
}

func (v NullableKafkaDatabaseSpecKafkaCluster) Get() *KafkaDatabaseSpecKafkaCluster {
	return v.value
}

func (v *NullableKafkaDatabaseSpecKafkaCluster) Set(val *KafkaDatabaseSpecKafkaCluster) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaDatabaseSpecKafkaCluster) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaDatabaseSpecKafkaCluster) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaDatabaseSpecKafkaCluster(val *KafkaDatabaseSpecKafkaCluster) *NullableKafkaDatabaseSpecKafkaCluster {
	return &NullableKafkaDatabaseSpecKafkaCluster{value: val, isSet: true}
}

func (v NullableKafkaDatabaseSpecKafkaCluster) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaDatabaseSpecKafkaCluster) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


