/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// KubernetesClusterName struct for KubernetesClusterName
type KubernetesClusterName struct {
	KubernetesClusterName *string `json:"kubernetesClusterName,omitempty"`
}

// NewKubernetesClusterName instantiates a new KubernetesClusterName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKubernetesClusterName() *KubernetesClusterName {
	this := KubernetesClusterName{}
	return &this
}

// NewKubernetesClusterNameWithDefaults instantiates a new KubernetesClusterName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKubernetesClusterNameWithDefaults() *KubernetesClusterName {
	this := KubernetesClusterName{}
	return &this
}

// GetKubernetesClusterName returns the KubernetesClusterName field value if set, zero value otherwise.
func (o *KubernetesClusterName) GetKubernetesClusterName() string {
	if o == nil || o.KubernetesClusterName == nil {
		var ret string
		return ret
	}
	return *o.KubernetesClusterName
}

// GetKubernetesClusterNameOk returns a tuple with the KubernetesClusterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KubernetesClusterName) GetKubernetesClusterNameOk() (*string, bool) {
	if o == nil || o.KubernetesClusterName == nil {
		return nil, false
	}
	return o.KubernetesClusterName, true
}

// HasKubernetesClusterName returns a boolean if a field has been set.
func (o *KubernetesClusterName) HasKubernetesClusterName() bool {
	if o != nil && o.KubernetesClusterName != nil {
		return true
	}

	return false
}

// SetKubernetesClusterName gets a reference to the given string and assigns it to the KubernetesClusterName field.
func (o *KubernetesClusterName) SetKubernetesClusterName(v string) {
	o.KubernetesClusterName = &v
}

func (o KubernetesClusterName) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.KubernetesClusterName != nil {
		toSerialize["kubernetesClusterName"] = o.KubernetesClusterName
	}
	return json.Marshal(toSerialize)
}

type NullableKubernetesClusterName struct {
	value *KubernetesClusterName
	isSet bool
}

func (v NullableKubernetesClusterName) Get() *KubernetesClusterName {
	return v.value
}

func (v *NullableKubernetesClusterName) Set(val *KubernetesClusterName) {
	v.value = val
	v.isSet = true
}

func (v NullableKubernetesClusterName) IsSet() bool {
	return v.isSet
}

func (v *NullableKubernetesClusterName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKubernetesClusterName(val *KubernetesClusterName) *NullableKubernetesClusterName {
	return &NullableKubernetesClusterName{value: val, isSet: true}
}

func (v NullableKubernetesClusterName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKubernetesClusterName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


