/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// KafkaDatabase Represents a the configuration of a Kafka Database
type KafkaDatabase struct {
	// API version for spec
	ApiVersion string `json:"apiVersion"`
	// Kind of resource - set to resource type
	Kind string `json:"kind"`
	Metadata DatabaseMetadata `json:"metadata"`
	Spec KafkaDatabaseSpec `json:"spec"`
}

// NewKafkaDatabase instantiates a new KafkaDatabase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaDatabase(apiVersion string, kind string, metadata DatabaseMetadata, spec KafkaDatabaseSpec) *KafkaDatabase {
	this := KafkaDatabase{}
	this.ApiVersion = apiVersion
	this.Kind = kind
	this.Metadata = metadata
	this.Spec = spec
	return &this
}

// NewKafkaDatabaseWithDefaults instantiates a new KafkaDatabase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaDatabaseWithDefaults() *KafkaDatabase {
	this := KafkaDatabase{}
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *KafkaDatabase) GetApiVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *KafkaDatabase) GetApiVersionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *KafkaDatabase) SetApiVersion(v string) {
	o.ApiVersion = v
}

// GetKind returns the Kind field value
func (o *KafkaDatabase) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *KafkaDatabase) GetKindOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *KafkaDatabase) SetKind(v string) {
	o.Kind = v
}

// GetMetadata returns the Metadata field value
func (o *KafkaDatabase) GetMetadata() DatabaseMetadata {
	if o == nil {
		var ret DatabaseMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *KafkaDatabase) GetMetadataOk() (*DatabaseMetadata, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *KafkaDatabase) SetMetadata(v DatabaseMetadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value
func (o *KafkaDatabase) GetSpec() KafkaDatabaseSpec {
	if o == nil {
		var ret KafkaDatabaseSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *KafkaDatabase) GetSpecOk() (*KafkaDatabaseSpec, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *KafkaDatabase) SetSpec(v KafkaDatabaseSpec) {
	o.Spec = v
}

func (o KafkaDatabase) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if true {
		toSerialize["kind"] = o.Kind
	}
	if true {
		toSerialize["metadata"] = o.Metadata
	}
	if true {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableKafkaDatabase struct {
	value *KafkaDatabase
	isSet bool
}

func (v NullableKafkaDatabase) Get() *KafkaDatabase {
	return v.value
}

func (v *NullableKafkaDatabase) Set(val *KafkaDatabase) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaDatabase) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaDatabase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaDatabase(val *KafkaDatabase) *NullableKafkaDatabase {
	return &NullableKafkaDatabase{value: val, isSet: true}
}

func (v NullableKafkaDatabase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaDatabase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


