/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// ArtifactStatus Server-managed status for a specific version of the Artifact.
type ArtifactStatus struct {
	// Version number (starts at 1, auto-incremented on each new binary upload).
	Version *int32 `json:"version,omitempty"`
	// Timestamp when this version was created (when its binary was uploaded). For version 1 this equals the Artifact's `metadata.creationTimestamp`; later versions each carry their own upload time.
	CreationTimestamp *string `json:"creationTimestamp,omitempty"`
	// Full path to the artifact in blob storage.
	Path *string `json:"path,omitempty"`
	// File size in bytes. Omitted from the response while the version is in `UPLOADING` phase.
	Size *int64 `json:"size,omitempty"`
	// SHA-256 checksum of the artifact content (e.g. `sha256:abc...`). Omitted from the response while the version is in `UPLOADING` phase.
	Checksum *string `json:"checksum,omitempty"`
	// Lifecycle phase of this version. `UPLOADING`: content is still being uploaded. `READY`: content is uploaded and available. `FILE_MISSING`: the backing file is absent from storage. `STORE_UNREACHABLE`: artifact storage could not be reached, so the file's presence could not be verified.
	Phase *string `json:"phase,omitempty"`
	// Human-readable status message, populated on error states such as `FILE_MISSING` and `STORE_UNREACHABLE`.
	Message *string `json:"message,omitempty"`
}

// NewArtifactStatus instantiates a new ArtifactStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtifactStatus() *ArtifactStatus {
	this := ArtifactStatus{}
	return &this
}

// NewArtifactStatusWithDefaults instantiates a new ArtifactStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtifactStatusWithDefaults() *ArtifactStatus {
	this := ArtifactStatus{}
	return &this
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ArtifactStatus) GetVersion() int32 {
	if o == nil || o.Version == nil {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactStatus) GetVersionOk() (*int32, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ArtifactStatus) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *ArtifactStatus) SetVersion(v int32) {
	o.Version = &v
}

// GetCreationTimestamp returns the CreationTimestamp field value if set, zero value otherwise.
func (o *ArtifactStatus) GetCreationTimestamp() string {
	if o == nil || o.CreationTimestamp == nil {
		var ret string
		return ret
	}
	return *o.CreationTimestamp
}

// GetCreationTimestampOk returns a tuple with the CreationTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactStatus) GetCreationTimestampOk() (*string, bool) {
	if o == nil || o.CreationTimestamp == nil {
		return nil, false
	}
	return o.CreationTimestamp, true
}

// HasCreationTimestamp returns a boolean if a field has been set.
func (o *ArtifactStatus) HasCreationTimestamp() bool {
	if o != nil && o.CreationTimestamp != nil {
		return true
	}

	return false
}

// SetCreationTimestamp gets a reference to the given string and assigns it to the CreationTimestamp field.
func (o *ArtifactStatus) SetCreationTimestamp(v string) {
	o.CreationTimestamp = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ArtifactStatus) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactStatus) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ArtifactStatus) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ArtifactStatus) SetPath(v string) {
	o.Path = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ArtifactStatus) GetSize() int64 {
	if o == nil || o.Size == nil {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactStatus) GetSizeOk() (*int64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ArtifactStatus) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *ArtifactStatus) SetSize(v int64) {
	o.Size = &v
}

// GetChecksum returns the Checksum field value if set, zero value otherwise.
func (o *ArtifactStatus) GetChecksum() string {
	if o == nil || o.Checksum == nil {
		var ret string
		return ret
	}
	return *o.Checksum
}

// GetChecksumOk returns a tuple with the Checksum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactStatus) GetChecksumOk() (*string, bool) {
	if o == nil || o.Checksum == nil {
		return nil, false
	}
	return o.Checksum, true
}

// HasChecksum returns a boolean if a field has been set.
func (o *ArtifactStatus) HasChecksum() bool {
	if o != nil && o.Checksum != nil {
		return true
	}

	return false
}

// SetChecksum gets a reference to the given string and assigns it to the Checksum field.
func (o *ArtifactStatus) SetChecksum(v string) {
	o.Checksum = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *ArtifactStatus) GetPhase() string {
	if o == nil || o.Phase == nil {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactStatus) GetPhaseOk() (*string, bool) {
	if o == nil || o.Phase == nil {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *ArtifactStatus) HasPhase() bool {
	if o != nil && o.Phase != nil {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *ArtifactStatus) SetPhase(v string) {
	o.Phase = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ArtifactStatus) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactStatus) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ArtifactStatus) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ArtifactStatus) SetMessage(v string) {
	o.Message = &v
}

func (o ArtifactStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.CreationTimestamp != nil {
		toSerialize["creationTimestamp"] = o.CreationTimestamp
	}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	if o.Checksum != nil {
		toSerialize["checksum"] = o.Checksum
	}
	if o.Phase != nil {
		toSerialize["phase"] = o.Phase
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	return json.Marshal(toSerialize)
}

type NullableArtifactStatus struct {
	value *ArtifactStatus
	isSet bool
}

func (v NullableArtifactStatus) Get() *ArtifactStatus {
	return v.value
}

func (v *NullableArtifactStatus) Set(val *ArtifactStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableArtifactStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableArtifactStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtifactStatus(val *ArtifactStatus) *NullableArtifactStatus {
	return &NullableArtifactStatus{value: val, isSet: true}
}

func (v NullableArtifactStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtifactStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


