/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// EnvironmentsPage struct for EnvironmentsPage
type EnvironmentsPage struct {
	Pageable *Pageable `json:"pageable,omitempty"`
	Metadata *EnvironmentsPageMetadata `json:"metadata,omitempty"`
	Items *[]Environment `json:"items,omitempty"`
}

// NewEnvironmentsPage instantiates a new EnvironmentsPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentsPage() *EnvironmentsPage {
	this := EnvironmentsPage{}
	return &this
}

// NewEnvironmentsPageWithDefaults instantiates a new EnvironmentsPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentsPageWithDefaults() *EnvironmentsPage {
	this := EnvironmentsPage{}
	return &this
}

// GetPageable returns the Pageable field value if set, zero value otherwise.
func (o *EnvironmentsPage) GetPageable() Pageable {
	if o == nil || o.Pageable == nil {
		var ret Pageable
		return ret
	}
	return *o.Pageable
}

// GetPageableOk returns a tuple with the Pageable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentsPage) GetPageableOk() (*Pageable, bool) {
	if o == nil || o.Pageable == nil {
		return nil, false
	}
	return o.Pageable, true
}

// HasPageable returns a boolean if a field has been set.
func (o *EnvironmentsPage) HasPageable() bool {
	if o != nil && o.Pageable != nil {
		return true
	}

	return false
}

// SetPageable gets a reference to the given Pageable and assigns it to the Pageable field.
func (o *EnvironmentsPage) SetPageable(v Pageable) {
	o.Pageable = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *EnvironmentsPage) GetMetadata() EnvironmentsPageMetadata {
	if o == nil || o.Metadata == nil {
		var ret EnvironmentsPageMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentsPage) GetMetadataOk() (*EnvironmentsPageMetadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *EnvironmentsPage) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given EnvironmentsPageMetadata and assigns it to the Metadata field.
func (o *EnvironmentsPage) SetMetadata(v EnvironmentsPageMetadata) {
	o.Metadata = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *EnvironmentsPage) GetItems() []Environment {
	if o == nil || o.Items == nil {
		var ret []Environment
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentsPage) GetItemsOk() (*[]Environment, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *EnvironmentsPage) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Environment and assigns it to the Items field.
func (o *EnvironmentsPage) SetItems(v []Environment) {
	o.Items = &v
}

func (o EnvironmentsPage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Pageable != nil {
		toSerialize["pageable"] = o.Pageable
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableEnvironmentsPage struct {
	value *EnvironmentsPage
	isSet bool
}

func (v NullableEnvironmentsPage) Get() *EnvironmentsPage {
	return v.value
}

func (v *NullableEnvironmentsPage) Set(val *EnvironmentsPage) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentsPage) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentsPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentsPage(val *EnvironmentsPage) *NullableEnvironmentsPage {
	return &NullableEnvironmentsPage{value: val, isSet: true}
}

func (v NullableEnvironmentsPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentsPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


