/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// StatementStartFromSavepoint Configuration for resuming a Statement from a savepoint. Works only with update Statement.
type StatementStartFromSavepoint struct {
	// The name of the Savepoint resource to start Statement from. The request will be rejected if savepoint that has not completed is referenced.
	SavepointName *string `json:"savepointName,omitempty"`
	// The uuid of the Savepoint resource to start from.
	Uid *string `json:"uid,omitempty"`
	// The path of the savepoint to start the Statement from. This could be an external path too.
	InitialSavepointPath *string `json:"initialSavepointPath,omitempty"`
	// A boolean flag to allow the job to start even if some state could not be restored.
	AllowNonRestoredState *bool `json:"allowNonRestoredState,omitempty"`
	// Nonce used to trigger a full redeployment of the job from the savepoint. In order to trigger redeployment, change the number to a different non-null value. Rollback is not possible after redeployment.
	SavepointRedeployNonce *int64 `json:"savepointRedeployNonce,omitempty"`
}

// NewStatementStartFromSavepoint instantiates a new StatementStartFromSavepoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatementStartFromSavepoint() *StatementStartFromSavepoint {
	this := StatementStartFromSavepoint{}
	return &this
}

// NewStatementStartFromSavepointWithDefaults instantiates a new StatementStartFromSavepoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatementStartFromSavepointWithDefaults() *StatementStartFromSavepoint {
	this := StatementStartFromSavepoint{}
	return &this
}

// GetSavepointName returns the SavepointName field value if set, zero value otherwise.
func (o *StatementStartFromSavepoint) GetSavepointName() string {
	if o == nil || o.SavepointName == nil {
		var ret string
		return ret
	}
	return *o.SavepointName
}

// GetSavepointNameOk returns a tuple with the SavepointName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementStartFromSavepoint) GetSavepointNameOk() (*string, bool) {
	if o == nil || o.SavepointName == nil {
		return nil, false
	}
	return o.SavepointName, true
}

// HasSavepointName returns a boolean if a field has been set.
func (o *StatementStartFromSavepoint) HasSavepointName() bool {
	if o != nil && o.SavepointName != nil {
		return true
	}

	return false
}

// SetSavepointName gets a reference to the given string and assigns it to the SavepointName field.
func (o *StatementStartFromSavepoint) SetSavepointName(v string) {
	o.SavepointName = &v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *StatementStartFromSavepoint) GetUid() string {
	if o == nil || o.Uid == nil {
		var ret string
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementStartFromSavepoint) GetUidOk() (*string, bool) {
	if o == nil || o.Uid == nil {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *StatementStartFromSavepoint) HasUid() bool {
	if o != nil && o.Uid != nil {
		return true
	}

	return false
}

// SetUid gets a reference to the given string and assigns it to the Uid field.
func (o *StatementStartFromSavepoint) SetUid(v string) {
	o.Uid = &v
}

// GetInitialSavepointPath returns the InitialSavepointPath field value if set, zero value otherwise.
func (o *StatementStartFromSavepoint) GetInitialSavepointPath() string {
	if o == nil || o.InitialSavepointPath == nil {
		var ret string
		return ret
	}
	return *o.InitialSavepointPath
}

// GetInitialSavepointPathOk returns a tuple with the InitialSavepointPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementStartFromSavepoint) GetInitialSavepointPathOk() (*string, bool) {
	if o == nil || o.InitialSavepointPath == nil {
		return nil, false
	}
	return o.InitialSavepointPath, true
}

// HasInitialSavepointPath returns a boolean if a field has been set.
func (o *StatementStartFromSavepoint) HasInitialSavepointPath() bool {
	if o != nil && o.InitialSavepointPath != nil {
		return true
	}

	return false
}

// SetInitialSavepointPath gets a reference to the given string and assigns it to the InitialSavepointPath field.
func (o *StatementStartFromSavepoint) SetInitialSavepointPath(v string) {
	o.InitialSavepointPath = &v
}

// GetAllowNonRestoredState returns the AllowNonRestoredState field value if set, zero value otherwise.
func (o *StatementStartFromSavepoint) GetAllowNonRestoredState() bool {
	if o == nil || o.AllowNonRestoredState == nil {
		var ret bool
		return ret
	}
	return *o.AllowNonRestoredState
}

// GetAllowNonRestoredStateOk returns a tuple with the AllowNonRestoredState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementStartFromSavepoint) GetAllowNonRestoredStateOk() (*bool, bool) {
	if o == nil || o.AllowNonRestoredState == nil {
		return nil, false
	}
	return o.AllowNonRestoredState, true
}

// HasAllowNonRestoredState returns a boolean if a field has been set.
func (o *StatementStartFromSavepoint) HasAllowNonRestoredState() bool {
	if o != nil && o.AllowNonRestoredState != nil {
		return true
	}

	return false
}

// SetAllowNonRestoredState gets a reference to the given bool and assigns it to the AllowNonRestoredState field.
func (o *StatementStartFromSavepoint) SetAllowNonRestoredState(v bool) {
	o.AllowNonRestoredState = &v
}

// GetSavepointRedeployNonce returns the SavepointRedeployNonce field value if set, zero value otherwise.
func (o *StatementStartFromSavepoint) GetSavepointRedeployNonce() int64 {
	if o == nil || o.SavepointRedeployNonce == nil {
		var ret int64
		return ret
	}
	return *o.SavepointRedeployNonce
}

// GetSavepointRedeployNonceOk returns a tuple with the SavepointRedeployNonce field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatementStartFromSavepoint) GetSavepointRedeployNonceOk() (*int64, bool) {
	if o == nil || o.SavepointRedeployNonce == nil {
		return nil, false
	}
	return o.SavepointRedeployNonce, true
}

// HasSavepointRedeployNonce returns a boolean if a field has been set.
func (o *StatementStartFromSavepoint) HasSavepointRedeployNonce() bool {
	if o != nil && o.SavepointRedeployNonce != nil {
		return true
	}

	return false
}

// SetSavepointRedeployNonce gets a reference to the given int64 and assigns it to the SavepointRedeployNonce field.
func (o *StatementStartFromSavepoint) SetSavepointRedeployNonce(v int64) {
	o.SavepointRedeployNonce = &v
}

func (o StatementStartFromSavepoint) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SavepointName != nil {
		toSerialize["savepointName"] = o.SavepointName
	}
	if o.Uid != nil {
		toSerialize["uid"] = o.Uid
	}
	if o.InitialSavepointPath != nil {
		toSerialize["initialSavepointPath"] = o.InitialSavepointPath
	}
	if o.AllowNonRestoredState != nil {
		toSerialize["allowNonRestoredState"] = o.AllowNonRestoredState
	}
	if o.SavepointRedeployNonce != nil {
		toSerialize["savepointRedeployNonce"] = o.SavepointRedeployNonce
	}
	return json.Marshal(toSerialize)
}

type NullableStatementStartFromSavepoint struct {
	value *StatementStartFromSavepoint
	isSet bool
}

func (v NullableStatementStartFromSavepoint) Get() *StatementStartFromSavepoint {
	return v.value
}

func (v *NullableStatementStartFromSavepoint) Set(val *StatementStartFromSavepoint) {
	v.value = val
	v.isSet = true
}

func (v NullableStatementStartFromSavepoint) IsSet() bool {
	return v.isSet
}

func (v *NullableStatementStartFromSavepoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatementStartFromSavepoint(val *StatementStartFromSavepoint) *NullableStatementStartFromSavepoint {
	return &NullableStatementStartFromSavepoint{value: val, isSet: true}
}

func (v NullableStatementStartFromSavepoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatementStartFromSavepoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


