/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// KafkaDatabaseSpec Spec of a Kafka Database
type KafkaDatabaseSpec struct {
	KafkaCluster KafkaDatabaseSpecKafkaCluster `json:"kafkaCluster"`
	// List of environments that have permission to alter the tables of this database
	AlterEnvironments *[]string `json:"alterEnvironments,omitempty"`
}

// NewKafkaDatabaseSpec instantiates a new KafkaDatabaseSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaDatabaseSpec(kafkaCluster KafkaDatabaseSpecKafkaCluster) *KafkaDatabaseSpec {
	this := KafkaDatabaseSpec{}
	this.KafkaCluster = kafkaCluster
	return &this
}

// NewKafkaDatabaseSpecWithDefaults instantiates a new KafkaDatabaseSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaDatabaseSpecWithDefaults() *KafkaDatabaseSpec {
	this := KafkaDatabaseSpec{}
	return &this
}

// GetKafkaCluster returns the KafkaCluster field value
func (o *KafkaDatabaseSpec) GetKafkaCluster() KafkaDatabaseSpecKafkaCluster {
	if o == nil {
		var ret KafkaDatabaseSpecKafkaCluster
		return ret
	}

	return o.KafkaCluster
}

// GetKafkaClusterOk returns a tuple with the KafkaCluster field value
// and a boolean to check if the value has been set.
func (o *KafkaDatabaseSpec) GetKafkaClusterOk() (*KafkaDatabaseSpecKafkaCluster, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.KafkaCluster, true
}

// SetKafkaCluster sets field value
func (o *KafkaDatabaseSpec) SetKafkaCluster(v KafkaDatabaseSpecKafkaCluster) {
	o.KafkaCluster = v
}

// GetAlterEnvironments returns the AlterEnvironments field value if set, zero value otherwise.
func (o *KafkaDatabaseSpec) GetAlterEnvironments() []string {
	if o == nil || o.AlterEnvironments == nil {
		var ret []string
		return ret
	}
	return *o.AlterEnvironments
}

// GetAlterEnvironmentsOk returns a tuple with the AlterEnvironments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KafkaDatabaseSpec) GetAlterEnvironmentsOk() (*[]string, bool) {
	if o == nil || o.AlterEnvironments == nil {
		return nil, false
	}
	return o.AlterEnvironments, true
}

// HasAlterEnvironments returns a boolean if a field has been set.
func (o *KafkaDatabaseSpec) HasAlterEnvironments() bool {
	if o != nil && o.AlterEnvironments != nil {
		return true
	}

	return false
}

// SetAlterEnvironments gets a reference to the given []string and assigns it to the AlterEnvironments field.
func (o *KafkaDatabaseSpec) SetAlterEnvironments(v []string) {
	o.AlterEnvironments = &v
}

func (o KafkaDatabaseSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["kafkaCluster"] = o.KafkaCluster
	}
	if o.AlterEnvironments != nil {
		toSerialize["alterEnvironments"] = o.AlterEnvironments
	}
	return json.Marshal(toSerialize)
}

type NullableKafkaDatabaseSpec struct {
	value *KafkaDatabaseSpec
	isSet bool
}

func (v NullableKafkaDatabaseSpec) Get() *KafkaDatabaseSpec {
	return v.value
}

func (v *NullableKafkaDatabaseSpec) Set(val *KafkaDatabaseSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaDatabaseSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaDatabaseSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaDatabaseSpec(val *KafkaDatabaseSpec) *NullableKafkaDatabaseSpec {
	return &NullableKafkaDatabaseSpec{value: val, isSet: true}
}

func (v NullableKafkaDatabaseSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaDatabaseSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


