/*
 * Confluent Manager for Apache Flink / CMF
 *
 * Apache Flink job lifecycle management component for Confluent Platform.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package v1
// Pageable struct for Pageable
type Pageable struct {
	Page int32 `json:"page,omitempty"`
	// The number of items in a page.
	Size int32 `json:"size,omitempty"`
	Sort Sort `json:"sort,omitempty"`
}
