/*
Confluent Manager for Apache Flink / CMF

Apache Flink job lifecycle management component for Confluent Platform.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1

import (
	"encoding/json"
)

// SecretsPageMetadata struct for SecretsPageMetadata
type SecretsPageMetadata struct {
	Size *int64 `json:"size,omitempty"`
}

// NewSecretsPageMetadata instantiates a new SecretsPageMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretsPageMetadata() *SecretsPageMetadata {
	this := SecretsPageMetadata{}
	var size int64 = 0
	this.Size = &size
	return &this
}

// NewSecretsPageMetadataWithDefaults instantiates a new SecretsPageMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretsPageMetadataWithDefaults() *SecretsPageMetadata {
	this := SecretsPageMetadata{}
	var size int64 = 0
	this.Size = &size
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *SecretsPageMetadata) GetSize() int64 {
	if o == nil || o.Size == nil {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecretsPageMetadata) GetSizeOk() (*int64, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *SecretsPageMetadata) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *SecretsPageMetadata) SetSize(v int64) {
	o.Size = &v
}

func (o SecretsPageMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Size != nil {
		toSerialize["size"] = o.Size
	}
	return json.Marshal(toSerialize)
}

type NullableSecretsPageMetadata struct {
	value *SecretsPageMetadata
	isSet bool
}

func (v NullableSecretsPageMetadata) Get() *SecretsPageMetadata {
	return v.value
}

func (v *NullableSecretsPageMetadata) Set(val *SecretsPageMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretsPageMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretsPageMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretsPageMetadata(val *SecretsPageMetadata) *NullableSecretsPageMetadata {
	return &NullableSecretsPageMetadata{value: val, isSet: true}
}

func (v NullableSecretsPageMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretsPageMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


