name: cmf-sdk-go
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
make:
  enable: true
  enable_updates: true
semaphore:
  enable: true
  pipeline_enable: false
  pipeline_type: cp
codeowners:
  enable: true
