// Code generated by mocker. DO NOT EDIT.
// github.com/travisjeffery/mocker
// Source: api_secrets.go

package mock

import (
	context "context"
	net_http "net/http"
	sync "sync"

	github_com_confluentinc_cmf_sdk_go_v1 "github.com/confluentinc/cmf-sdk-go/v1"
)

// MockSecretsApi is a mock of SecretsApi interface
type MockSecretsApi struct {
	lockCreateSecret sync.Mutex
	CreateSecretFunc func(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSecretRequest

	lockCreateSecretExecute sync.Mutex
	CreateSecretExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSecretRequest) (github_com_confluentinc_cmf_sdk_go_v1.Secret, *net_http.Response, error)

	lockDeleteSecret sync.Mutex
	DeleteSecretFunc func(ctx context.Context, secretName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSecretRequest

	lockDeleteSecretExecute sync.Mutex
	DeleteSecretExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSecretRequest) (*net_http.Response, error)

	lockGetSecret sync.Mutex
	GetSecretFunc func(ctx context.Context, secretName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretRequest

	lockGetSecretExecute sync.Mutex
	GetSecretExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretRequest) (github_com_confluentinc_cmf_sdk_go_v1.Secret, *net_http.Response, error)

	lockGetSecrets sync.Mutex
	GetSecretsFunc func(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretsRequest

	lockGetSecretsExecute sync.Mutex
	GetSecretsExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretsRequest) (github_com_confluentinc_cmf_sdk_go_v1.SecretsPage, *net_http.Response, error)

	lockUpdateSecret sync.Mutex
	UpdateSecretFunc func(ctx context.Context, secretName string) github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSecretRequest

	lockUpdateSecretExecute sync.Mutex
	UpdateSecretExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSecretRequest) (github_com_confluentinc_cmf_sdk_go_v1.Secret, *net_http.Response, error)

	calls struct {
		CreateSecret []struct {
			Ctx context.Context
		}
		CreateSecretExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSecretRequest
		}
		DeleteSecret []struct {
			Ctx        context.Context
			SecretName string
		}
		DeleteSecretExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSecretRequest
		}
		GetSecret []struct {
			Ctx        context.Context
			SecretName string
		}
		GetSecretExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretRequest
		}
		GetSecrets []struct {
			Ctx context.Context
		}
		GetSecretsExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretsRequest
		}
		UpdateSecret []struct {
			Ctx        context.Context
			SecretName string
		}
		UpdateSecretExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSecretRequest
		}
	}
}

// CreateSecret mocks base method by wrapping the associated func.
func (m *MockSecretsApi) CreateSecret(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSecretRequest {
	m.lockCreateSecret.Lock()
	defer m.lockCreateSecret.Unlock()

	if m.CreateSecretFunc == nil {
		panic("mocker: MockSecretsApi.CreateSecretFunc is nil but MockSecretsApi.CreateSecret was called.")
	}

	call := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}

	m.calls.CreateSecret = append(m.calls.CreateSecret, call)

	return m.CreateSecretFunc(ctx)
}

// CreateSecretCalled returns true if CreateSecret was called at least once.
func (m *MockSecretsApi) CreateSecretCalled() bool {
	m.lockCreateSecret.Lock()
	defer m.lockCreateSecret.Unlock()

	return len(m.calls.CreateSecret) > 0
}

// CreateSecretCalls returns the calls made to CreateSecret.
func (m *MockSecretsApi) CreateSecretCalls() []struct {
	Ctx context.Context
} {
	m.lockCreateSecret.Lock()
	defer m.lockCreateSecret.Unlock()

	return m.calls.CreateSecret
}

// CreateSecretExecute mocks base method by wrapping the associated func.
func (m *MockSecretsApi) CreateSecretExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSecretRequest) (github_com_confluentinc_cmf_sdk_go_v1.Secret, *net_http.Response, error) {
	m.lockCreateSecretExecute.Lock()
	defer m.lockCreateSecretExecute.Unlock()

	if m.CreateSecretExecuteFunc == nil {
		panic("mocker: MockSecretsApi.CreateSecretExecuteFunc is nil but MockSecretsApi.CreateSecretExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSecretRequest
	}{
		R: r,
	}

	m.calls.CreateSecretExecute = append(m.calls.CreateSecretExecute, call)

	return m.CreateSecretExecuteFunc(r)
}

// CreateSecretExecuteCalled returns true if CreateSecretExecute was called at least once.
func (m *MockSecretsApi) CreateSecretExecuteCalled() bool {
	m.lockCreateSecretExecute.Lock()
	defer m.lockCreateSecretExecute.Unlock()

	return len(m.calls.CreateSecretExecute) > 0
}

// CreateSecretExecuteCalls returns the calls made to CreateSecretExecute.
func (m *MockSecretsApi) CreateSecretExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSecretRequest
} {
	m.lockCreateSecretExecute.Lock()
	defer m.lockCreateSecretExecute.Unlock()

	return m.calls.CreateSecretExecute
}

// DeleteSecret mocks base method by wrapping the associated func.
func (m *MockSecretsApi) DeleteSecret(ctx context.Context, secretName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSecretRequest {
	m.lockDeleteSecret.Lock()
	defer m.lockDeleteSecret.Unlock()

	if m.DeleteSecretFunc == nil {
		panic("mocker: MockSecretsApi.DeleteSecretFunc is nil but MockSecretsApi.DeleteSecret was called.")
	}

	call := struct {
		Ctx        context.Context
		SecretName string
	}{
		Ctx:        ctx,
		SecretName: secretName,
	}

	m.calls.DeleteSecret = append(m.calls.DeleteSecret, call)

	return m.DeleteSecretFunc(ctx, secretName)
}

// DeleteSecretCalled returns true if DeleteSecret was called at least once.
func (m *MockSecretsApi) DeleteSecretCalled() bool {
	m.lockDeleteSecret.Lock()
	defer m.lockDeleteSecret.Unlock()

	return len(m.calls.DeleteSecret) > 0
}

// DeleteSecretCalls returns the calls made to DeleteSecret.
func (m *MockSecretsApi) DeleteSecretCalls() []struct {
	Ctx        context.Context
	SecretName string
} {
	m.lockDeleteSecret.Lock()
	defer m.lockDeleteSecret.Unlock()

	return m.calls.DeleteSecret
}

// DeleteSecretExecute mocks base method by wrapping the associated func.
func (m *MockSecretsApi) DeleteSecretExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSecretRequest) (*net_http.Response, error) {
	m.lockDeleteSecretExecute.Lock()
	defer m.lockDeleteSecretExecute.Unlock()

	if m.DeleteSecretExecuteFunc == nil {
		panic("mocker: MockSecretsApi.DeleteSecretExecuteFunc is nil but MockSecretsApi.DeleteSecretExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSecretRequest
	}{
		R: r,
	}

	m.calls.DeleteSecretExecute = append(m.calls.DeleteSecretExecute, call)

	return m.DeleteSecretExecuteFunc(r)
}

// DeleteSecretExecuteCalled returns true if DeleteSecretExecute was called at least once.
func (m *MockSecretsApi) DeleteSecretExecuteCalled() bool {
	m.lockDeleteSecretExecute.Lock()
	defer m.lockDeleteSecretExecute.Unlock()

	return len(m.calls.DeleteSecretExecute) > 0
}

// DeleteSecretExecuteCalls returns the calls made to DeleteSecretExecute.
func (m *MockSecretsApi) DeleteSecretExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSecretRequest
} {
	m.lockDeleteSecretExecute.Lock()
	defer m.lockDeleteSecretExecute.Unlock()

	return m.calls.DeleteSecretExecute
}

// GetSecret mocks base method by wrapping the associated func.
func (m *MockSecretsApi) GetSecret(ctx context.Context, secretName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretRequest {
	m.lockGetSecret.Lock()
	defer m.lockGetSecret.Unlock()

	if m.GetSecretFunc == nil {
		panic("mocker: MockSecretsApi.GetSecretFunc is nil but MockSecretsApi.GetSecret was called.")
	}

	call := struct {
		Ctx        context.Context
		SecretName string
	}{
		Ctx:        ctx,
		SecretName: secretName,
	}

	m.calls.GetSecret = append(m.calls.GetSecret, call)

	return m.GetSecretFunc(ctx, secretName)
}

// GetSecretCalled returns true if GetSecret was called at least once.
func (m *MockSecretsApi) GetSecretCalled() bool {
	m.lockGetSecret.Lock()
	defer m.lockGetSecret.Unlock()

	return len(m.calls.GetSecret) > 0
}

// GetSecretCalls returns the calls made to GetSecret.
func (m *MockSecretsApi) GetSecretCalls() []struct {
	Ctx        context.Context
	SecretName string
} {
	m.lockGetSecret.Lock()
	defer m.lockGetSecret.Unlock()

	return m.calls.GetSecret
}

// GetSecretExecute mocks base method by wrapping the associated func.
func (m *MockSecretsApi) GetSecretExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretRequest) (github_com_confluentinc_cmf_sdk_go_v1.Secret, *net_http.Response, error) {
	m.lockGetSecretExecute.Lock()
	defer m.lockGetSecretExecute.Unlock()

	if m.GetSecretExecuteFunc == nil {
		panic("mocker: MockSecretsApi.GetSecretExecuteFunc is nil but MockSecretsApi.GetSecretExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretRequest
	}{
		R: r,
	}

	m.calls.GetSecretExecute = append(m.calls.GetSecretExecute, call)

	return m.GetSecretExecuteFunc(r)
}

// GetSecretExecuteCalled returns true if GetSecretExecute was called at least once.
func (m *MockSecretsApi) GetSecretExecuteCalled() bool {
	m.lockGetSecretExecute.Lock()
	defer m.lockGetSecretExecute.Unlock()

	return len(m.calls.GetSecretExecute) > 0
}

// GetSecretExecuteCalls returns the calls made to GetSecretExecute.
func (m *MockSecretsApi) GetSecretExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretRequest
} {
	m.lockGetSecretExecute.Lock()
	defer m.lockGetSecretExecute.Unlock()

	return m.calls.GetSecretExecute
}

// GetSecrets mocks base method by wrapping the associated func.
func (m *MockSecretsApi) GetSecrets(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretsRequest {
	m.lockGetSecrets.Lock()
	defer m.lockGetSecrets.Unlock()

	if m.GetSecretsFunc == nil {
		panic("mocker: MockSecretsApi.GetSecretsFunc is nil but MockSecretsApi.GetSecrets was called.")
	}

	call := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}

	m.calls.GetSecrets = append(m.calls.GetSecrets, call)

	return m.GetSecretsFunc(ctx)
}

// GetSecretsCalled returns true if GetSecrets was called at least once.
func (m *MockSecretsApi) GetSecretsCalled() bool {
	m.lockGetSecrets.Lock()
	defer m.lockGetSecrets.Unlock()

	return len(m.calls.GetSecrets) > 0
}

// GetSecretsCalls returns the calls made to GetSecrets.
func (m *MockSecretsApi) GetSecretsCalls() []struct {
	Ctx context.Context
} {
	m.lockGetSecrets.Lock()
	defer m.lockGetSecrets.Unlock()

	return m.calls.GetSecrets
}

// GetSecretsExecute mocks base method by wrapping the associated func.
func (m *MockSecretsApi) GetSecretsExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretsRequest) (github_com_confluentinc_cmf_sdk_go_v1.SecretsPage, *net_http.Response, error) {
	m.lockGetSecretsExecute.Lock()
	defer m.lockGetSecretsExecute.Unlock()

	if m.GetSecretsExecuteFunc == nil {
		panic("mocker: MockSecretsApi.GetSecretsExecuteFunc is nil but MockSecretsApi.GetSecretsExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretsRequest
	}{
		R: r,
	}

	m.calls.GetSecretsExecute = append(m.calls.GetSecretsExecute, call)

	return m.GetSecretsExecuteFunc(r)
}

// GetSecretsExecuteCalled returns true if GetSecretsExecute was called at least once.
func (m *MockSecretsApi) GetSecretsExecuteCalled() bool {
	m.lockGetSecretsExecute.Lock()
	defer m.lockGetSecretsExecute.Unlock()

	return len(m.calls.GetSecretsExecute) > 0
}

// GetSecretsExecuteCalls returns the calls made to GetSecretsExecute.
func (m *MockSecretsApi) GetSecretsExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSecretsRequest
} {
	m.lockGetSecretsExecute.Lock()
	defer m.lockGetSecretsExecute.Unlock()

	return m.calls.GetSecretsExecute
}

// UpdateSecret mocks base method by wrapping the associated func.
func (m *MockSecretsApi) UpdateSecret(ctx context.Context, secretName string) github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSecretRequest {
	m.lockUpdateSecret.Lock()
	defer m.lockUpdateSecret.Unlock()

	if m.UpdateSecretFunc == nil {
		panic("mocker: MockSecretsApi.UpdateSecretFunc is nil but MockSecretsApi.UpdateSecret was called.")
	}

	call := struct {
		Ctx        context.Context
		SecretName string
	}{
		Ctx:        ctx,
		SecretName: secretName,
	}

	m.calls.UpdateSecret = append(m.calls.UpdateSecret, call)

	return m.UpdateSecretFunc(ctx, secretName)
}

// UpdateSecretCalled returns true if UpdateSecret was called at least once.
func (m *MockSecretsApi) UpdateSecretCalled() bool {
	m.lockUpdateSecret.Lock()
	defer m.lockUpdateSecret.Unlock()

	return len(m.calls.UpdateSecret) > 0
}

// UpdateSecretCalls returns the calls made to UpdateSecret.
func (m *MockSecretsApi) UpdateSecretCalls() []struct {
	Ctx        context.Context
	SecretName string
} {
	m.lockUpdateSecret.Lock()
	defer m.lockUpdateSecret.Unlock()

	return m.calls.UpdateSecret
}

// UpdateSecretExecute mocks base method by wrapping the associated func.
func (m *MockSecretsApi) UpdateSecretExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSecretRequest) (github_com_confluentinc_cmf_sdk_go_v1.Secret, *net_http.Response, error) {
	m.lockUpdateSecretExecute.Lock()
	defer m.lockUpdateSecretExecute.Unlock()

	if m.UpdateSecretExecuteFunc == nil {
		panic("mocker: MockSecretsApi.UpdateSecretExecuteFunc is nil but MockSecretsApi.UpdateSecretExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSecretRequest
	}{
		R: r,
	}

	m.calls.UpdateSecretExecute = append(m.calls.UpdateSecretExecute, call)

	return m.UpdateSecretExecuteFunc(r)
}

// UpdateSecretExecuteCalled returns true if UpdateSecretExecute was called at least once.
func (m *MockSecretsApi) UpdateSecretExecuteCalled() bool {
	m.lockUpdateSecretExecute.Lock()
	defer m.lockUpdateSecretExecute.Unlock()

	return len(m.calls.UpdateSecretExecute) > 0
}

// UpdateSecretExecuteCalls returns the calls made to UpdateSecretExecute.
func (m *MockSecretsApi) UpdateSecretExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSecretRequest
} {
	m.lockUpdateSecretExecute.Lock()
	defer m.lockUpdateSecretExecute.Unlock()

	return m.calls.UpdateSecretExecute
}

// Reset resets the calls made to the mocked methods.
func (m *MockSecretsApi) Reset() {
	m.lockCreateSecret.Lock()
	m.calls.CreateSecret = nil
	m.lockCreateSecret.Unlock()
	m.lockCreateSecretExecute.Lock()
	m.calls.CreateSecretExecute = nil
	m.lockCreateSecretExecute.Unlock()
	m.lockDeleteSecret.Lock()
	m.calls.DeleteSecret = nil
	m.lockDeleteSecret.Unlock()
	m.lockDeleteSecretExecute.Lock()
	m.calls.DeleteSecretExecute = nil
	m.lockDeleteSecretExecute.Unlock()
	m.lockGetSecret.Lock()
	m.calls.GetSecret = nil
	m.lockGetSecret.Unlock()
	m.lockGetSecretExecute.Lock()
	m.calls.GetSecretExecute = nil
	m.lockGetSecretExecute.Unlock()
	m.lockGetSecrets.Lock()
	m.calls.GetSecrets = nil
	m.lockGetSecrets.Unlock()
	m.lockGetSecretsExecute.Lock()
	m.calls.GetSecretsExecute = nil
	m.lockGetSecretsExecute.Unlock()
	m.lockUpdateSecret.Lock()
	m.calls.UpdateSecret = nil
	m.lockUpdateSecret.Unlock()
	m.lockUpdateSecretExecute.Lock()
	m.calls.UpdateSecretExecute = nil
	m.lockUpdateSecretExecute.Unlock()
}
