// Code generated by mocker. DO NOT EDIT.
// github.com/travisjeffery/mocker
// Source: api_cmf_information.go

package mock

import (
	context "context"
	net_http "net/http"
	sync "sync"

	github_com_confluentinc_cmf_sdk_go_v1 "github.com/confluentinc/cmf-sdk-go/v1"
)

// MockCMFInformationApi is a mock of CMFInformationApi interface
type MockCMFInformationApi struct {
	lockGetResourceInformation sync.Mutex
	GetResourceInformationFunc func(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiGetResourceInformationRequest

	lockGetResourceInformationExecute sync.Mutex
	GetResourceInformationExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetResourceInformationRequest) (github_com_confluentinc_cmf_sdk_go_v1.ResourceInformation, *net_http.Response, error)

	lockGetSystemInformation sync.Mutex
	GetSystemInformationFunc func(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSystemInformationRequest

	lockGetSystemInformationExecute sync.Mutex
	GetSystemInformationExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSystemInformationRequest) (github_com_confluentinc_cmf_sdk_go_v1.SystemInformation, *net_http.Response, error)

	calls struct {
		GetResourceInformation []struct {
			Ctx context.Context
		}
		GetResourceInformationExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiGetResourceInformationRequest
		}
		GetSystemInformation []struct {
			Ctx context.Context
		}
		GetSystemInformationExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSystemInformationRequest
		}
	}
}

// GetResourceInformation mocks base method by wrapping the associated func.
func (m *MockCMFInformationApi) GetResourceInformation(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiGetResourceInformationRequest {
	m.lockGetResourceInformation.Lock()
	defer m.lockGetResourceInformation.Unlock()

	if m.GetResourceInformationFunc == nil {
		panic("mocker: MockCMFInformationApi.GetResourceInformationFunc is nil but MockCMFInformationApi.GetResourceInformation was called.")
	}

	call := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}

	m.calls.GetResourceInformation = append(m.calls.GetResourceInformation, call)

	return m.GetResourceInformationFunc(ctx)
}

// GetResourceInformationCalled returns true if GetResourceInformation was called at least once.
func (m *MockCMFInformationApi) GetResourceInformationCalled() bool {
	m.lockGetResourceInformation.Lock()
	defer m.lockGetResourceInformation.Unlock()

	return len(m.calls.GetResourceInformation) > 0
}

// GetResourceInformationCalls returns the calls made to GetResourceInformation.
func (m *MockCMFInformationApi) GetResourceInformationCalls() []struct {
	Ctx context.Context
} {
	m.lockGetResourceInformation.Lock()
	defer m.lockGetResourceInformation.Unlock()

	return m.calls.GetResourceInformation
}

// GetResourceInformationExecute mocks base method by wrapping the associated func.
func (m *MockCMFInformationApi) GetResourceInformationExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetResourceInformationRequest) (github_com_confluentinc_cmf_sdk_go_v1.ResourceInformation, *net_http.Response, error) {
	m.lockGetResourceInformationExecute.Lock()
	defer m.lockGetResourceInformationExecute.Unlock()

	if m.GetResourceInformationExecuteFunc == nil {
		panic("mocker: MockCMFInformationApi.GetResourceInformationExecuteFunc is nil but MockCMFInformationApi.GetResourceInformationExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiGetResourceInformationRequest
	}{
		R: r,
	}

	m.calls.GetResourceInformationExecute = append(m.calls.GetResourceInformationExecute, call)

	return m.GetResourceInformationExecuteFunc(r)
}

// GetResourceInformationExecuteCalled returns true if GetResourceInformationExecute was called at least once.
func (m *MockCMFInformationApi) GetResourceInformationExecuteCalled() bool {
	m.lockGetResourceInformationExecute.Lock()
	defer m.lockGetResourceInformationExecute.Unlock()

	return len(m.calls.GetResourceInformationExecute) > 0
}

// GetResourceInformationExecuteCalls returns the calls made to GetResourceInformationExecute.
func (m *MockCMFInformationApi) GetResourceInformationExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiGetResourceInformationRequest
} {
	m.lockGetResourceInformationExecute.Lock()
	defer m.lockGetResourceInformationExecute.Unlock()

	return m.calls.GetResourceInformationExecute
}

// GetSystemInformation mocks base method by wrapping the associated func.
func (m *MockCMFInformationApi) GetSystemInformation(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSystemInformationRequest {
	m.lockGetSystemInformation.Lock()
	defer m.lockGetSystemInformation.Unlock()

	if m.GetSystemInformationFunc == nil {
		panic("mocker: MockCMFInformationApi.GetSystemInformationFunc is nil but MockCMFInformationApi.GetSystemInformation was called.")
	}

	call := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}

	m.calls.GetSystemInformation = append(m.calls.GetSystemInformation, call)

	return m.GetSystemInformationFunc(ctx)
}

// GetSystemInformationCalled returns true if GetSystemInformation was called at least once.
func (m *MockCMFInformationApi) GetSystemInformationCalled() bool {
	m.lockGetSystemInformation.Lock()
	defer m.lockGetSystemInformation.Unlock()

	return len(m.calls.GetSystemInformation) > 0
}

// GetSystemInformationCalls returns the calls made to GetSystemInformation.
func (m *MockCMFInformationApi) GetSystemInformationCalls() []struct {
	Ctx context.Context
} {
	m.lockGetSystemInformation.Lock()
	defer m.lockGetSystemInformation.Unlock()

	return m.calls.GetSystemInformation
}

// GetSystemInformationExecute mocks base method by wrapping the associated func.
func (m *MockCMFInformationApi) GetSystemInformationExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSystemInformationRequest) (github_com_confluentinc_cmf_sdk_go_v1.SystemInformation, *net_http.Response, error) {
	m.lockGetSystemInformationExecute.Lock()
	defer m.lockGetSystemInformationExecute.Unlock()

	if m.GetSystemInformationExecuteFunc == nil {
		panic("mocker: MockCMFInformationApi.GetSystemInformationExecuteFunc is nil but MockCMFInformationApi.GetSystemInformationExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSystemInformationRequest
	}{
		R: r,
	}

	m.calls.GetSystemInformationExecute = append(m.calls.GetSystemInformationExecute, call)

	return m.GetSystemInformationExecuteFunc(r)
}

// GetSystemInformationExecuteCalled returns true if GetSystemInformationExecute was called at least once.
func (m *MockCMFInformationApi) GetSystemInformationExecuteCalled() bool {
	m.lockGetSystemInformationExecute.Lock()
	defer m.lockGetSystemInformationExecute.Unlock()

	return len(m.calls.GetSystemInformationExecute) > 0
}

// GetSystemInformationExecuteCalls returns the calls made to GetSystemInformationExecute.
func (m *MockCMFInformationApi) GetSystemInformationExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSystemInformationRequest
} {
	m.lockGetSystemInformationExecute.Lock()
	defer m.lockGetSystemInformationExecute.Unlock()

	return m.calls.GetSystemInformationExecute
}

// Reset resets the calls made to the mocked methods.
func (m *MockCMFInformationApi) Reset() {
	m.lockGetResourceInformation.Lock()
	m.calls.GetResourceInformation = nil
	m.lockGetResourceInformation.Unlock()
	m.lockGetResourceInformationExecute.Lock()
	m.calls.GetResourceInformationExecute = nil
	m.lockGetResourceInformationExecute.Unlock()
	m.lockGetSystemInformation.Lock()
	m.calls.GetSystemInformation = nil
	m.lockGetSystemInformation.Unlock()
	m.lockGetSystemInformationExecute.Lock()
	m.calls.GetSystemInformationExecute = nil
	m.lockGetSystemInformationExecute.Unlock()
}
