// Code generated by mocker. DO NOT EDIT.
// github.com/travisjeffery/mocker
// Source: api_savepoints.go

package mock

import (
	context "context"
	net_http "net/http"
	sync "sync"

	github_com_confluentinc_cmf_sdk_go_v1 "github.com/confluentinc/cmf-sdk-go/v1"
)

// MockSavepointsApi is a mock of SavepointsApi interface
type MockSavepointsApi struct {
	lockBulkDeleteSavepointsForFlinkApplication sync.Mutex
	BulkDeleteSavepointsForFlinkApplicationFunc func(ctx context.Context, envName, appName string) github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkApplicationRequest

	lockBulkDeleteSavepointsForFlinkApplicationExecute sync.Mutex
	BulkDeleteSavepointsForFlinkApplicationExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsBulkDeleteResult, *net_http.Response, error)

	lockBulkDeleteSavepointsForFlinkStatement sync.Mutex
	BulkDeleteSavepointsForFlinkStatementFunc func(ctx context.Context, envName, stmtName string) github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkStatementRequest

	lockBulkDeleteSavepointsForFlinkStatementExecute sync.Mutex
	BulkDeleteSavepointsForFlinkStatementExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsBulkDeleteResult, *net_http.Response, error)

	lockCreateSavepointForFlinkApplication sync.Mutex
	CreateSavepointForFlinkApplicationFunc func(ctx context.Context, envName, appName string) github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkApplicationRequest

	lockCreateSavepointForFlinkApplicationExecute sync.Mutex
	CreateSavepointForFlinkApplicationExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error)

	lockCreateSavepointForFlinkStatement sync.Mutex
	CreateSavepointForFlinkStatementFunc func(ctx context.Context, envName, stmtName string) github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkStatementRequest

	lockCreateSavepointForFlinkStatementExecute sync.Mutex
	CreateSavepointForFlinkStatementExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error)

	lockDeleteSavepointForFlinkApplication sync.Mutex
	DeleteSavepointForFlinkApplicationFunc func(ctx context.Context, envName, appName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkApplicationRequest

	lockDeleteSavepointForFlinkApplicationExecute sync.Mutex
	DeleteSavepointForFlinkApplicationExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkApplicationRequest) (*net_http.Response, error)

	lockDeleteSavepointForFlinkStatement sync.Mutex
	DeleteSavepointForFlinkStatementFunc func(ctx context.Context, envName, stmtName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkStatementRequest

	lockDeleteSavepointForFlinkStatementExecute sync.Mutex
	DeleteSavepointForFlinkStatementExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkStatementRequest) (*net_http.Response, error)

	lockDetachSavepointFromFlinkApplication sync.Mutex
	DetachSavepointFromFlinkApplicationFunc func(ctx context.Context, envName, appName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDetachSavepointFromFlinkApplicationRequest

	lockDetachSavepointFromFlinkApplicationExecute sync.Mutex
	DetachSavepointFromFlinkApplicationExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiDetachSavepointFromFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error)

	lockGetSavepointForFlinkApplication sync.Mutex
	GetSavepointForFlinkApplicationFunc func(ctx context.Context, envName, appName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkApplicationRequest

	lockGetSavepointForFlinkApplicationExecute sync.Mutex
	GetSavepointForFlinkApplicationExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error)

	lockGetSavepointForFlinkStatement sync.Mutex
	GetSavepointForFlinkStatementFunc func(ctx context.Context, envName, stmtName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkStatementRequest

	lockGetSavepointForFlinkStatementExecute sync.Mutex
	GetSavepointForFlinkStatementExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error)

	lockGetSavepointsForFlinkApplication sync.Mutex
	GetSavepointsForFlinkApplicationFunc func(ctx context.Context, envName, appName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkApplicationRequest

	lockGetSavepointsForFlinkApplicationExecute sync.Mutex
	GetSavepointsForFlinkApplicationExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsPage, *net_http.Response, error)

	lockGetSavepointsForFlinkStatement sync.Mutex
	GetSavepointsForFlinkStatementFunc func(ctx context.Context, envName, stmtName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkStatementRequest

	lockGetSavepointsForFlinkStatementExecute sync.Mutex
	GetSavepointsForFlinkStatementExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsPage, *net_http.Response, error)

	lockUpdateSavepointForFlinkApplication sync.Mutex
	UpdateSavepointForFlinkApplicationFunc func(ctx context.Context, envName, appName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkApplicationRequest

	lockUpdateSavepointForFlinkApplicationExecute sync.Mutex
	UpdateSavepointForFlinkApplicationExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error)

	lockUpdateSavepointForFlinkStatement sync.Mutex
	UpdateSavepointForFlinkStatementFunc func(ctx context.Context, envName, stmtName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkStatementRequest

	lockUpdateSavepointForFlinkStatementExecute sync.Mutex
	UpdateSavepointForFlinkStatementExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error)

	calls struct {
		BulkDeleteSavepointsForFlinkApplication []struct {
			Ctx     context.Context
			EnvName string
			AppName string
		}
		BulkDeleteSavepointsForFlinkApplicationExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkApplicationRequest
		}
		BulkDeleteSavepointsForFlinkStatement []struct {
			Ctx      context.Context
			EnvName  string
			StmtName string
		}
		BulkDeleteSavepointsForFlinkStatementExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkStatementRequest
		}
		CreateSavepointForFlinkApplication []struct {
			Ctx     context.Context
			EnvName string
			AppName string
		}
		CreateSavepointForFlinkApplicationExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkApplicationRequest
		}
		CreateSavepointForFlinkStatement []struct {
			Ctx      context.Context
			EnvName  string
			StmtName string
		}
		CreateSavepointForFlinkStatementExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkStatementRequest
		}
		DeleteSavepointForFlinkApplication []struct {
			Ctx           context.Context
			EnvName       string
			AppName       string
			SavepointName string
		}
		DeleteSavepointForFlinkApplicationExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkApplicationRequest
		}
		DeleteSavepointForFlinkStatement []struct {
			Ctx           context.Context
			EnvName       string
			StmtName      string
			SavepointName string
		}
		DeleteSavepointForFlinkStatementExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkStatementRequest
		}
		DetachSavepointFromFlinkApplication []struct {
			Ctx           context.Context
			EnvName       string
			AppName       string
			SavepointName string
		}
		DetachSavepointFromFlinkApplicationExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiDetachSavepointFromFlinkApplicationRequest
		}
		GetSavepointForFlinkApplication []struct {
			Ctx           context.Context
			EnvName       string
			AppName       string
			SavepointName string
		}
		GetSavepointForFlinkApplicationExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkApplicationRequest
		}
		GetSavepointForFlinkStatement []struct {
			Ctx           context.Context
			EnvName       string
			StmtName      string
			SavepointName string
		}
		GetSavepointForFlinkStatementExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkStatementRequest
		}
		GetSavepointsForFlinkApplication []struct {
			Ctx     context.Context
			EnvName string
			AppName string
		}
		GetSavepointsForFlinkApplicationExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkApplicationRequest
		}
		GetSavepointsForFlinkStatement []struct {
			Ctx      context.Context
			EnvName  string
			StmtName string
		}
		GetSavepointsForFlinkStatementExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkStatementRequest
		}
		UpdateSavepointForFlinkApplication []struct {
			Ctx           context.Context
			EnvName       string
			AppName       string
			SavepointName string
		}
		UpdateSavepointForFlinkApplicationExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkApplicationRequest
		}
		UpdateSavepointForFlinkStatement []struct {
			Ctx           context.Context
			EnvName       string
			StmtName      string
			SavepointName string
		}
		UpdateSavepointForFlinkStatementExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkStatementRequest
		}
	}
}

// BulkDeleteSavepointsForFlinkApplication mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkApplication(ctx context.Context, envName, appName string) github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkApplicationRequest {
	m.lockBulkDeleteSavepointsForFlinkApplication.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkApplication.Unlock()

	if m.BulkDeleteSavepointsForFlinkApplicationFunc == nil {
		panic("mocker: MockSavepointsApi.BulkDeleteSavepointsForFlinkApplicationFunc is nil but MockSavepointsApi.BulkDeleteSavepointsForFlinkApplication was called.")
	}

	call := struct {
		Ctx     context.Context
		EnvName string
		AppName string
	}{
		Ctx:     ctx,
		EnvName: envName,
		AppName: appName,
	}

	m.calls.BulkDeleteSavepointsForFlinkApplication = append(m.calls.BulkDeleteSavepointsForFlinkApplication, call)

	return m.BulkDeleteSavepointsForFlinkApplicationFunc(ctx, envName, appName)
}

// BulkDeleteSavepointsForFlinkApplicationCalled returns true if BulkDeleteSavepointsForFlinkApplication was called at least once.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkApplicationCalled() bool {
	m.lockBulkDeleteSavepointsForFlinkApplication.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkApplication.Unlock()

	return len(m.calls.BulkDeleteSavepointsForFlinkApplication) > 0
}

// BulkDeleteSavepointsForFlinkApplicationCalls returns the calls made to BulkDeleteSavepointsForFlinkApplication.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkApplicationCalls() []struct {
	Ctx     context.Context
	EnvName string
	AppName string
} {
	m.lockBulkDeleteSavepointsForFlinkApplication.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkApplication.Unlock()

	return m.calls.BulkDeleteSavepointsForFlinkApplication
}

// BulkDeleteSavepointsForFlinkApplicationExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkApplicationExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsBulkDeleteResult, *net_http.Response, error) {
	m.lockBulkDeleteSavepointsForFlinkApplicationExecute.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkApplicationExecute.Unlock()

	if m.BulkDeleteSavepointsForFlinkApplicationExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.BulkDeleteSavepointsForFlinkApplicationExecuteFunc is nil but MockSavepointsApi.BulkDeleteSavepointsForFlinkApplicationExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkApplicationRequest
	}{
		R: r,
	}

	m.calls.BulkDeleteSavepointsForFlinkApplicationExecute = append(m.calls.BulkDeleteSavepointsForFlinkApplicationExecute, call)

	return m.BulkDeleteSavepointsForFlinkApplicationExecuteFunc(r)
}

// BulkDeleteSavepointsForFlinkApplicationExecuteCalled returns true if BulkDeleteSavepointsForFlinkApplicationExecute was called at least once.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkApplicationExecuteCalled() bool {
	m.lockBulkDeleteSavepointsForFlinkApplicationExecute.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkApplicationExecute.Unlock()

	return len(m.calls.BulkDeleteSavepointsForFlinkApplicationExecute) > 0
}

// BulkDeleteSavepointsForFlinkApplicationExecuteCalls returns the calls made to BulkDeleteSavepointsForFlinkApplicationExecute.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkApplicationExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkApplicationRequest
} {
	m.lockBulkDeleteSavepointsForFlinkApplicationExecute.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkApplicationExecute.Unlock()

	return m.calls.BulkDeleteSavepointsForFlinkApplicationExecute
}

// BulkDeleteSavepointsForFlinkStatement mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkStatement(ctx context.Context, envName, stmtName string) github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkStatementRequest {
	m.lockBulkDeleteSavepointsForFlinkStatement.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkStatement.Unlock()

	if m.BulkDeleteSavepointsForFlinkStatementFunc == nil {
		panic("mocker: MockSavepointsApi.BulkDeleteSavepointsForFlinkStatementFunc is nil but MockSavepointsApi.BulkDeleteSavepointsForFlinkStatement was called.")
	}

	call := struct {
		Ctx      context.Context
		EnvName  string
		StmtName string
	}{
		Ctx:      ctx,
		EnvName:  envName,
		StmtName: stmtName,
	}

	m.calls.BulkDeleteSavepointsForFlinkStatement = append(m.calls.BulkDeleteSavepointsForFlinkStatement, call)

	return m.BulkDeleteSavepointsForFlinkStatementFunc(ctx, envName, stmtName)
}

// BulkDeleteSavepointsForFlinkStatementCalled returns true if BulkDeleteSavepointsForFlinkStatement was called at least once.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkStatementCalled() bool {
	m.lockBulkDeleteSavepointsForFlinkStatement.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkStatement.Unlock()

	return len(m.calls.BulkDeleteSavepointsForFlinkStatement) > 0
}

// BulkDeleteSavepointsForFlinkStatementCalls returns the calls made to BulkDeleteSavepointsForFlinkStatement.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkStatementCalls() []struct {
	Ctx      context.Context
	EnvName  string
	StmtName string
} {
	m.lockBulkDeleteSavepointsForFlinkStatement.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkStatement.Unlock()

	return m.calls.BulkDeleteSavepointsForFlinkStatement
}

// BulkDeleteSavepointsForFlinkStatementExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkStatementExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsBulkDeleteResult, *net_http.Response, error) {
	m.lockBulkDeleteSavepointsForFlinkStatementExecute.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkStatementExecute.Unlock()

	if m.BulkDeleteSavepointsForFlinkStatementExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.BulkDeleteSavepointsForFlinkStatementExecuteFunc is nil but MockSavepointsApi.BulkDeleteSavepointsForFlinkStatementExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkStatementRequest
	}{
		R: r,
	}

	m.calls.BulkDeleteSavepointsForFlinkStatementExecute = append(m.calls.BulkDeleteSavepointsForFlinkStatementExecute, call)

	return m.BulkDeleteSavepointsForFlinkStatementExecuteFunc(r)
}

// BulkDeleteSavepointsForFlinkStatementExecuteCalled returns true if BulkDeleteSavepointsForFlinkStatementExecute was called at least once.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkStatementExecuteCalled() bool {
	m.lockBulkDeleteSavepointsForFlinkStatementExecute.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkStatementExecute.Unlock()

	return len(m.calls.BulkDeleteSavepointsForFlinkStatementExecute) > 0
}

// BulkDeleteSavepointsForFlinkStatementExecuteCalls returns the calls made to BulkDeleteSavepointsForFlinkStatementExecute.
func (m *MockSavepointsApi) BulkDeleteSavepointsForFlinkStatementExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiBulkDeleteSavepointsForFlinkStatementRequest
} {
	m.lockBulkDeleteSavepointsForFlinkStatementExecute.Lock()
	defer m.lockBulkDeleteSavepointsForFlinkStatementExecute.Unlock()

	return m.calls.BulkDeleteSavepointsForFlinkStatementExecute
}

// CreateSavepointForFlinkApplication mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) CreateSavepointForFlinkApplication(ctx context.Context, envName, appName string) github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkApplicationRequest {
	m.lockCreateSavepointForFlinkApplication.Lock()
	defer m.lockCreateSavepointForFlinkApplication.Unlock()

	if m.CreateSavepointForFlinkApplicationFunc == nil {
		panic("mocker: MockSavepointsApi.CreateSavepointForFlinkApplicationFunc is nil but MockSavepointsApi.CreateSavepointForFlinkApplication was called.")
	}

	call := struct {
		Ctx     context.Context
		EnvName string
		AppName string
	}{
		Ctx:     ctx,
		EnvName: envName,
		AppName: appName,
	}

	m.calls.CreateSavepointForFlinkApplication = append(m.calls.CreateSavepointForFlinkApplication, call)

	return m.CreateSavepointForFlinkApplicationFunc(ctx, envName, appName)
}

// CreateSavepointForFlinkApplicationCalled returns true if CreateSavepointForFlinkApplication was called at least once.
func (m *MockSavepointsApi) CreateSavepointForFlinkApplicationCalled() bool {
	m.lockCreateSavepointForFlinkApplication.Lock()
	defer m.lockCreateSavepointForFlinkApplication.Unlock()

	return len(m.calls.CreateSavepointForFlinkApplication) > 0
}

// CreateSavepointForFlinkApplicationCalls returns the calls made to CreateSavepointForFlinkApplication.
func (m *MockSavepointsApi) CreateSavepointForFlinkApplicationCalls() []struct {
	Ctx     context.Context
	EnvName string
	AppName string
} {
	m.lockCreateSavepointForFlinkApplication.Lock()
	defer m.lockCreateSavepointForFlinkApplication.Unlock()

	return m.calls.CreateSavepointForFlinkApplication
}

// CreateSavepointForFlinkApplicationExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) CreateSavepointForFlinkApplicationExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error) {
	m.lockCreateSavepointForFlinkApplicationExecute.Lock()
	defer m.lockCreateSavepointForFlinkApplicationExecute.Unlock()

	if m.CreateSavepointForFlinkApplicationExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.CreateSavepointForFlinkApplicationExecuteFunc is nil but MockSavepointsApi.CreateSavepointForFlinkApplicationExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkApplicationRequest
	}{
		R: r,
	}

	m.calls.CreateSavepointForFlinkApplicationExecute = append(m.calls.CreateSavepointForFlinkApplicationExecute, call)

	return m.CreateSavepointForFlinkApplicationExecuteFunc(r)
}

// CreateSavepointForFlinkApplicationExecuteCalled returns true if CreateSavepointForFlinkApplicationExecute was called at least once.
func (m *MockSavepointsApi) CreateSavepointForFlinkApplicationExecuteCalled() bool {
	m.lockCreateSavepointForFlinkApplicationExecute.Lock()
	defer m.lockCreateSavepointForFlinkApplicationExecute.Unlock()

	return len(m.calls.CreateSavepointForFlinkApplicationExecute) > 0
}

// CreateSavepointForFlinkApplicationExecuteCalls returns the calls made to CreateSavepointForFlinkApplicationExecute.
func (m *MockSavepointsApi) CreateSavepointForFlinkApplicationExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkApplicationRequest
} {
	m.lockCreateSavepointForFlinkApplicationExecute.Lock()
	defer m.lockCreateSavepointForFlinkApplicationExecute.Unlock()

	return m.calls.CreateSavepointForFlinkApplicationExecute
}

// CreateSavepointForFlinkStatement mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) CreateSavepointForFlinkStatement(ctx context.Context, envName, stmtName string) github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkStatementRequest {
	m.lockCreateSavepointForFlinkStatement.Lock()
	defer m.lockCreateSavepointForFlinkStatement.Unlock()

	if m.CreateSavepointForFlinkStatementFunc == nil {
		panic("mocker: MockSavepointsApi.CreateSavepointForFlinkStatementFunc is nil but MockSavepointsApi.CreateSavepointForFlinkStatement was called.")
	}

	call := struct {
		Ctx      context.Context
		EnvName  string
		StmtName string
	}{
		Ctx:      ctx,
		EnvName:  envName,
		StmtName: stmtName,
	}

	m.calls.CreateSavepointForFlinkStatement = append(m.calls.CreateSavepointForFlinkStatement, call)

	return m.CreateSavepointForFlinkStatementFunc(ctx, envName, stmtName)
}

// CreateSavepointForFlinkStatementCalled returns true if CreateSavepointForFlinkStatement was called at least once.
func (m *MockSavepointsApi) CreateSavepointForFlinkStatementCalled() bool {
	m.lockCreateSavepointForFlinkStatement.Lock()
	defer m.lockCreateSavepointForFlinkStatement.Unlock()

	return len(m.calls.CreateSavepointForFlinkStatement) > 0
}

// CreateSavepointForFlinkStatementCalls returns the calls made to CreateSavepointForFlinkStatement.
func (m *MockSavepointsApi) CreateSavepointForFlinkStatementCalls() []struct {
	Ctx      context.Context
	EnvName  string
	StmtName string
} {
	m.lockCreateSavepointForFlinkStatement.Lock()
	defer m.lockCreateSavepointForFlinkStatement.Unlock()

	return m.calls.CreateSavepointForFlinkStatement
}

// CreateSavepointForFlinkStatementExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) CreateSavepointForFlinkStatementExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error) {
	m.lockCreateSavepointForFlinkStatementExecute.Lock()
	defer m.lockCreateSavepointForFlinkStatementExecute.Unlock()

	if m.CreateSavepointForFlinkStatementExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.CreateSavepointForFlinkStatementExecuteFunc is nil but MockSavepointsApi.CreateSavepointForFlinkStatementExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkStatementRequest
	}{
		R: r,
	}

	m.calls.CreateSavepointForFlinkStatementExecute = append(m.calls.CreateSavepointForFlinkStatementExecute, call)

	return m.CreateSavepointForFlinkStatementExecuteFunc(r)
}

// CreateSavepointForFlinkStatementExecuteCalled returns true if CreateSavepointForFlinkStatementExecute was called at least once.
func (m *MockSavepointsApi) CreateSavepointForFlinkStatementExecuteCalled() bool {
	m.lockCreateSavepointForFlinkStatementExecute.Lock()
	defer m.lockCreateSavepointForFlinkStatementExecute.Unlock()

	return len(m.calls.CreateSavepointForFlinkStatementExecute) > 0
}

// CreateSavepointForFlinkStatementExecuteCalls returns the calls made to CreateSavepointForFlinkStatementExecute.
func (m *MockSavepointsApi) CreateSavepointForFlinkStatementExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateSavepointForFlinkStatementRequest
} {
	m.lockCreateSavepointForFlinkStatementExecute.Lock()
	defer m.lockCreateSavepointForFlinkStatementExecute.Unlock()

	return m.calls.CreateSavepointForFlinkStatementExecute
}

// DeleteSavepointForFlinkApplication mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) DeleteSavepointForFlinkApplication(ctx context.Context, envName, appName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkApplicationRequest {
	m.lockDeleteSavepointForFlinkApplication.Lock()
	defer m.lockDeleteSavepointForFlinkApplication.Unlock()

	if m.DeleteSavepointForFlinkApplicationFunc == nil {
		panic("mocker: MockSavepointsApi.DeleteSavepointForFlinkApplicationFunc is nil but MockSavepointsApi.DeleteSavepointForFlinkApplication was called.")
	}

	call := struct {
		Ctx           context.Context
		EnvName       string
		AppName       string
		SavepointName string
	}{
		Ctx:           ctx,
		EnvName:       envName,
		AppName:       appName,
		SavepointName: savepointName,
	}

	m.calls.DeleteSavepointForFlinkApplication = append(m.calls.DeleteSavepointForFlinkApplication, call)

	return m.DeleteSavepointForFlinkApplicationFunc(ctx, envName, appName, savepointName)
}

// DeleteSavepointForFlinkApplicationCalled returns true if DeleteSavepointForFlinkApplication was called at least once.
func (m *MockSavepointsApi) DeleteSavepointForFlinkApplicationCalled() bool {
	m.lockDeleteSavepointForFlinkApplication.Lock()
	defer m.lockDeleteSavepointForFlinkApplication.Unlock()

	return len(m.calls.DeleteSavepointForFlinkApplication) > 0
}

// DeleteSavepointForFlinkApplicationCalls returns the calls made to DeleteSavepointForFlinkApplication.
func (m *MockSavepointsApi) DeleteSavepointForFlinkApplicationCalls() []struct {
	Ctx           context.Context
	EnvName       string
	AppName       string
	SavepointName string
} {
	m.lockDeleteSavepointForFlinkApplication.Lock()
	defer m.lockDeleteSavepointForFlinkApplication.Unlock()

	return m.calls.DeleteSavepointForFlinkApplication
}

// DeleteSavepointForFlinkApplicationExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) DeleteSavepointForFlinkApplicationExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkApplicationRequest) (*net_http.Response, error) {
	m.lockDeleteSavepointForFlinkApplicationExecute.Lock()
	defer m.lockDeleteSavepointForFlinkApplicationExecute.Unlock()

	if m.DeleteSavepointForFlinkApplicationExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.DeleteSavepointForFlinkApplicationExecuteFunc is nil but MockSavepointsApi.DeleteSavepointForFlinkApplicationExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkApplicationRequest
	}{
		R: r,
	}

	m.calls.DeleteSavepointForFlinkApplicationExecute = append(m.calls.DeleteSavepointForFlinkApplicationExecute, call)

	return m.DeleteSavepointForFlinkApplicationExecuteFunc(r)
}

// DeleteSavepointForFlinkApplicationExecuteCalled returns true if DeleteSavepointForFlinkApplicationExecute was called at least once.
func (m *MockSavepointsApi) DeleteSavepointForFlinkApplicationExecuteCalled() bool {
	m.lockDeleteSavepointForFlinkApplicationExecute.Lock()
	defer m.lockDeleteSavepointForFlinkApplicationExecute.Unlock()

	return len(m.calls.DeleteSavepointForFlinkApplicationExecute) > 0
}

// DeleteSavepointForFlinkApplicationExecuteCalls returns the calls made to DeleteSavepointForFlinkApplicationExecute.
func (m *MockSavepointsApi) DeleteSavepointForFlinkApplicationExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkApplicationRequest
} {
	m.lockDeleteSavepointForFlinkApplicationExecute.Lock()
	defer m.lockDeleteSavepointForFlinkApplicationExecute.Unlock()

	return m.calls.DeleteSavepointForFlinkApplicationExecute
}

// DeleteSavepointForFlinkStatement mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) DeleteSavepointForFlinkStatement(ctx context.Context, envName, stmtName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkStatementRequest {
	m.lockDeleteSavepointForFlinkStatement.Lock()
	defer m.lockDeleteSavepointForFlinkStatement.Unlock()

	if m.DeleteSavepointForFlinkStatementFunc == nil {
		panic("mocker: MockSavepointsApi.DeleteSavepointForFlinkStatementFunc is nil but MockSavepointsApi.DeleteSavepointForFlinkStatement was called.")
	}

	call := struct {
		Ctx           context.Context
		EnvName       string
		StmtName      string
		SavepointName string
	}{
		Ctx:           ctx,
		EnvName:       envName,
		StmtName:      stmtName,
		SavepointName: savepointName,
	}

	m.calls.DeleteSavepointForFlinkStatement = append(m.calls.DeleteSavepointForFlinkStatement, call)

	return m.DeleteSavepointForFlinkStatementFunc(ctx, envName, stmtName, savepointName)
}

// DeleteSavepointForFlinkStatementCalled returns true if DeleteSavepointForFlinkStatement was called at least once.
func (m *MockSavepointsApi) DeleteSavepointForFlinkStatementCalled() bool {
	m.lockDeleteSavepointForFlinkStatement.Lock()
	defer m.lockDeleteSavepointForFlinkStatement.Unlock()

	return len(m.calls.DeleteSavepointForFlinkStatement) > 0
}

// DeleteSavepointForFlinkStatementCalls returns the calls made to DeleteSavepointForFlinkStatement.
func (m *MockSavepointsApi) DeleteSavepointForFlinkStatementCalls() []struct {
	Ctx           context.Context
	EnvName       string
	StmtName      string
	SavepointName string
} {
	m.lockDeleteSavepointForFlinkStatement.Lock()
	defer m.lockDeleteSavepointForFlinkStatement.Unlock()

	return m.calls.DeleteSavepointForFlinkStatement
}

// DeleteSavepointForFlinkStatementExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) DeleteSavepointForFlinkStatementExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkStatementRequest) (*net_http.Response, error) {
	m.lockDeleteSavepointForFlinkStatementExecute.Lock()
	defer m.lockDeleteSavepointForFlinkStatementExecute.Unlock()

	if m.DeleteSavepointForFlinkStatementExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.DeleteSavepointForFlinkStatementExecuteFunc is nil but MockSavepointsApi.DeleteSavepointForFlinkStatementExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkStatementRequest
	}{
		R: r,
	}

	m.calls.DeleteSavepointForFlinkStatementExecute = append(m.calls.DeleteSavepointForFlinkStatementExecute, call)

	return m.DeleteSavepointForFlinkStatementExecuteFunc(r)
}

// DeleteSavepointForFlinkStatementExecuteCalled returns true if DeleteSavepointForFlinkStatementExecute was called at least once.
func (m *MockSavepointsApi) DeleteSavepointForFlinkStatementExecuteCalled() bool {
	m.lockDeleteSavepointForFlinkStatementExecute.Lock()
	defer m.lockDeleteSavepointForFlinkStatementExecute.Unlock()

	return len(m.calls.DeleteSavepointForFlinkStatementExecute) > 0
}

// DeleteSavepointForFlinkStatementExecuteCalls returns the calls made to DeleteSavepointForFlinkStatementExecute.
func (m *MockSavepointsApi) DeleteSavepointForFlinkStatementExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteSavepointForFlinkStatementRequest
} {
	m.lockDeleteSavepointForFlinkStatementExecute.Lock()
	defer m.lockDeleteSavepointForFlinkStatementExecute.Unlock()

	return m.calls.DeleteSavepointForFlinkStatementExecute
}

// DetachSavepointFromFlinkApplication mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) DetachSavepointFromFlinkApplication(ctx context.Context, envName, appName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDetachSavepointFromFlinkApplicationRequest {
	m.lockDetachSavepointFromFlinkApplication.Lock()
	defer m.lockDetachSavepointFromFlinkApplication.Unlock()

	if m.DetachSavepointFromFlinkApplicationFunc == nil {
		panic("mocker: MockSavepointsApi.DetachSavepointFromFlinkApplicationFunc is nil but MockSavepointsApi.DetachSavepointFromFlinkApplication was called.")
	}

	call := struct {
		Ctx           context.Context
		EnvName       string
		AppName       string
		SavepointName string
	}{
		Ctx:           ctx,
		EnvName:       envName,
		AppName:       appName,
		SavepointName: savepointName,
	}

	m.calls.DetachSavepointFromFlinkApplication = append(m.calls.DetachSavepointFromFlinkApplication, call)

	return m.DetachSavepointFromFlinkApplicationFunc(ctx, envName, appName, savepointName)
}

// DetachSavepointFromFlinkApplicationCalled returns true if DetachSavepointFromFlinkApplication was called at least once.
func (m *MockSavepointsApi) DetachSavepointFromFlinkApplicationCalled() bool {
	m.lockDetachSavepointFromFlinkApplication.Lock()
	defer m.lockDetachSavepointFromFlinkApplication.Unlock()

	return len(m.calls.DetachSavepointFromFlinkApplication) > 0
}

// DetachSavepointFromFlinkApplicationCalls returns the calls made to DetachSavepointFromFlinkApplication.
func (m *MockSavepointsApi) DetachSavepointFromFlinkApplicationCalls() []struct {
	Ctx           context.Context
	EnvName       string
	AppName       string
	SavepointName string
} {
	m.lockDetachSavepointFromFlinkApplication.Lock()
	defer m.lockDetachSavepointFromFlinkApplication.Unlock()

	return m.calls.DetachSavepointFromFlinkApplication
}

// DetachSavepointFromFlinkApplicationExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) DetachSavepointFromFlinkApplicationExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiDetachSavepointFromFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error) {
	m.lockDetachSavepointFromFlinkApplicationExecute.Lock()
	defer m.lockDetachSavepointFromFlinkApplicationExecute.Unlock()

	if m.DetachSavepointFromFlinkApplicationExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.DetachSavepointFromFlinkApplicationExecuteFunc is nil but MockSavepointsApi.DetachSavepointFromFlinkApplicationExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiDetachSavepointFromFlinkApplicationRequest
	}{
		R: r,
	}

	m.calls.DetachSavepointFromFlinkApplicationExecute = append(m.calls.DetachSavepointFromFlinkApplicationExecute, call)

	return m.DetachSavepointFromFlinkApplicationExecuteFunc(r)
}

// DetachSavepointFromFlinkApplicationExecuteCalled returns true if DetachSavepointFromFlinkApplicationExecute was called at least once.
func (m *MockSavepointsApi) DetachSavepointFromFlinkApplicationExecuteCalled() bool {
	m.lockDetachSavepointFromFlinkApplicationExecute.Lock()
	defer m.lockDetachSavepointFromFlinkApplicationExecute.Unlock()

	return len(m.calls.DetachSavepointFromFlinkApplicationExecute) > 0
}

// DetachSavepointFromFlinkApplicationExecuteCalls returns the calls made to DetachSavepointFromFlinkApplicationExecute.
func (m *MockSavepointsApi) DetachSavepointFromFlinkApplicationExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiDetachSavepointFromFlinkApplicationRequest
} {
	m.lockDetachSavepointFromFlinkApplicationExecute.Lock()
	defer m.lockDetachSavepointFromFlinkApplicationExecute.Unlock()

	return m.calls.DetachSavepointFromFlinkApplicationExecute
}

// GetSavepointForFlinkApplication mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) GetSavepointForFlinkApplication(ctx context.Context, envName, appName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkApplicationRequest {
	m.lockGetSavepointForFlinkApplication.Lock()
	defer m.lockGetSavepointForFlinkApplication.Unlock()

	if m.GetSavepointForFlinkApplicationFunc == nil {
		panic("mocker: MockSavepointsApi.GetSavepointForFlinkApplicationFunc is nil but MockSavepointsApi.GetSavepointForFlinkApplication was called.")
	}

	call := struct {
		Ctx           context.Context
		EnvName       string
		AppName       string
		SavepointName string
	}{
		Ctx:           ctx,
		EnvName:       envName,
		AppName:       appName,
		SavepointName: savepointName,
	}

	m.calls.GetSavepointForFlinkApplication = append(m.calls.GetSavepointForFlinkApplication, call)

	return m.GetSavepointForFlinkApplicationFunc(ctx, envName, appName, savepointName)
}

// GetSavepointForFlinkApplicationCalled returns true if GetSavepointForFlinkApplication was called at least once.
func (m *MockSavepointsApi) GetSavepointForFlinkApplicationCalled() bool {
	m.lockGetSavepointForFlinkApplication.Lock()
	defer m.lockGetSavepointForFlinkApplication.Unlock()

	return len(m.calls.GetSavepointForFlinkApplication) > 0
}

// GetSavepointForFlinkApplicationCalls returns the calls made to GetSavepointForFlinkApplication.
func (m *MockSavepointsApi) GetSavepointForFlinkApplicationCalls() []struct {
	Ctx           context.Context
	EnvName       string
	AppName       string
	SavepointName string
} {
	m.lockGetSavepointForFlinkApplication.Lock()
	defer m.lockGetSavepointForFlinkApplication.Unlock()

	return m.calls.GetSavepointForFlinkApplication
}

// GetSavepointForFlinkApplicationExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) GetSavepointForFlinkApplicationExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error) {
	m.lockGetSavepointForFlinkApplicationExecute.Lock()
	defer m.lockGetSavepointForFlinkApplicationExecute.Unlock()

	if m.GetSavepointForFlinkApplicationExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.GetSavepointForFlinkApplicationExecuteFunc is nil but MockSavepointsApi.GetSavepointForFlinkApplicationExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkApplicationRequest
	}{
		R: r,
	}

	m.calls.GetSavepointForFlinkApplicationExecute = append(m.calls.GetSavepointForFlinkApplicationExecute, call)

	return m.GetSavepointForFlinkApplicationExecuteFunc(r)
}

// GetSavepointForFlinkApplicationExecuteCalled returns true if GetSavepointForFlinkApplicationExecute was called at least once.
func (m *MockSavepointsApi) GetSavepointForFlinkApplicationExecuteCalled() bool {
	m.lockGetSavepointForFlinkApplicationExecute.Lock()
	defer m.lockGetSavepointForFlinkApplicationExecute.Unlock()

	return len(m.calls.GetSavepointForFlinkApplicationExecute) > 0
}

// GetSavepointForFlinkApplicationExecuteCalls returns the calls made to GetSavepointForFlinkApplicationExecute.
func (m *MockSavepointsApi) GetSavepointForFlinkApplicationExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkApplicationRequest
} {
	m.lockGetSavepointForFlinkApplicationExecute.Lock()
	defer m.lockGetSavepointForFlinkApplicationExecute.Unlock()

	return m.calls.GetSavepointForFlinkApplicationExecute
}

// GetSavepointForFlinkStatement mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) GetSavepointForFlinkStatement(ctx context.Context, envName, stmtName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkStatementRequest {
	m.lockGetSavepointForFlinkStatement.Lock()
	defer m.lockGetSavepointForFlinkStatement.Unlock()

	if m.GetSavepointForFlinkStatementFunc == nil {
		panic("mocker: MockSavepointsApi.GetSavepointForFlinkStatementFunc is nil but MockSavepointsApi.GetSavepointForFlinkStatement was called.")
	}

	call := struct {
		Ctx           context.Context
		EnvName       string
		StmtName      string
		SavepointName string
	}{
		Ctx:           ctx,
		EnvName:       envName,
		StmtName:      stmtName,
		SavepointName: savepointName,
	}

	m.calls.GetSavepointForFlinkStatement = append(m.calls.GetSavepointForFlinkStatement, call)

	return m.GetSavepointForFlinkStatementFunc(ctx, envName, stmtName, savepointName)
}

// GetSavepointForFlinkStatementCalled returns true if GetSavepointForFlinkStatement was called at least once.
func (m *MockSavepointsApi) GetSavepointForFlinkStatementCalled() bool {
	m.lockGetSavepointForFlinkStatement.Lock()
	defer m.lockGetSavepointForFlinkStatement.Unlock()

	return len(m.calls.GetSavepointForFlinkStatement) > 0
}

// GetSavepointForFlinkStatementCalls returns the calls made to GetSavepointForFlinkStatement.
func (m *MockSavepointsApi) GetSavepointForFlinkStatementCalls() []struct {
	Ctx           context.Context
	EnvName       string
	StmtName      string
	SavepointName string
} {
	m.lockGetSavepointForFlinkStatement.Lock()
	defer m.lockGetSavepointForFlinkStatement.Unlock()

	return m.calls.GetSavepointForFlinkStatement
}

// GetSavepointForFlinkStatementExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) GetSavepointForFlinkStatementExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error) {
	m.lockGetSavepointForFlinkStatementExecute.Lock()
	defer m.lockGetSavepointForFlinkStatementExecute.Unlock()

	if m.GetSavepointForFlinkStatementExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.GetSavepointForFlinkStatementExecuteFunc is nil but MockSavepointsApi.GetSavepointForFlinkStatementExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkStatementRequest
	}{
		R: r,
	}

	m.calls.GetSavepointForFlinkStatementExecute = append(m.calls.GetSavepointForFlinkStatementExecute, call)

	return m.GetSavepointForFlinkStatementExecuteFunc(r)
}

// GetSavepointForFlinkStatementExecuteCalled returns true if GetSavepointForFlinkStatementExecute was called at least once.
func (m *MockSavepointsApi) GetSavepointForFlinkStatementExecuteCalled() bool {
	m.lockGetSavepointForFlinkStatementExecute.Lock()
	defer m.lockGetSavepointForFlinkStatementExecute.Unlock()

	return len(m.calls.GetSavepointForFlinkStatementExecute) > 0
}

// GetSavepointForFlinkStatementExecuteCalls returns the calls made to GetSavepointForFlinkStatementExecute.
func (m *MockSavepointsApi) GetSavepointForFlinkStatementExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointForFlinkStatementRequest
} {
	m.lockGetSavepointForFlinkStatementExecute.Lock()
	defer m.lockGetSavepointForFlinkStatementExecute.Unlock()

	return m.calls.GetSavepointForFlinkStatementExecute
}

// GetSavepointsForFlinkApplication mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) GetSavepointsForFlinkApplication(ctx context.Context, envName, appName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkApplicationRequest {
	m.lockGetSavepointsForFlinkApplication.Lock()
	defer m.lockGetSavepointsForFlinkApplication.Unlock()

	if m.GetSavepointsForFlinkApplicationFunc == nil {
		panic("mocker: MockSavepointsApi.GetSavepointsForFlinkApplicationFunc is nil but MockSavepointsApi.GetSavepointsForFlinkApplication was called.")
	}

	call := struct {
		Ctx     context.Context
		EnvName string
		AppName string
	}{
		Ctx:     ctx,
		EnvName: envName,
		AppName: appName,
	}

	m.calls.GetSavepointsForFlinkApplication = append(m.calls.GetSavepointsForFlinkApplication, call)

	return m.GetSavepointsForFlinkApplicationFunc(ctx, envName, appName)
}

// GetSavepointsForFlinkApplicationCalled returns true if GetSavepointsForFlinkApplication was called at least once.
func (m *MockSavepointsApi) GetSavepointsForFlinkApplicationCalled() bool {
	m.lockGetSavepointsForFlinkApplication.Lock()
	defer m.lockGetSavepointsForFlinkApplication.Unlock()

	return len(m.calls.GetSavepointsForFlinkApplication) > 0
}

// GetSavepointsForFlinkApplicationCalls returns the calls made to GetSavepointsForFlinkApplication.
func (m *MockSavepointsApi) GetSavepointsForFlinkApplicationCalls() []struct {
	Ctx     context.Context
	EnvName string
	AppName string
} {
	m.lockGetSavepointsForFlinkApplication.Lock()
	defer m.lockGetSavepointsForFlinkApplication.Unlock()

	return m.calls.GetSavepointsForFlinkApplication
}

// GetSavepointsForFlinkApplicationExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) GetSavepointsForFlinkApplicationExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsPage, *net_http.Response, error) {
	m.lockGetSavepointsForFlinkApplicationExecute.Lock()
	defer m.lockGetSavepointsForFlinkApplicationExecute.Unlock()

	if m.GetSavepointsForFlinkApplicationExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.GetSavepointsForFlinkApplicationExecuteFunc is nil but MockSavepointsApi.GetSavepointsForFlinkApplicationExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkApplicationRequest
	}{
		R: r,
	}

	m.calls.GetSavepointsForFlinkApplicationExecute = append(m.calls.GetSavepointsForFlinkApplicationExecute, call)

	return m.GetSavepointsForFlinkApplicationExecuteFunc(r)
}

// GetSavepointsForFlinkApplicationExecuteCalled returns true if GetSavepointsForFlinkApplicationExecute was called at least once.
func (m *MockSavepointsApi) GetSavepointsForFlinkApplicationExecuteCalled() bool {
	m.lockGetSavepointsForFlinkApplicationExecute.Lock()
	defer m.lockGetSavepointsForFlinkApplicationExecute.Unlock()

	return len(m.calls.GetSavepointsForFlinkApplicationExecute) > 0
}

// GetSavepointsForFlinkApplicationExecuteCalls returns the calls made to GetSavepointsForFlinkApplicationExecute.
func (m *MockSavepointsApi) GetSavepointsForFlinkApplicationExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkApplicationRequest
} {
	m.lockGetSavepointsForFlinkApplicationExecute.Lock()
	defer m.lockGetSavepointsForFlinkApplicationExecute.Unlock()

	return m.calls.GetSavepointsForFlinkApplicationExecute
}

// GetSavepointsForFlinkStatement mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) GetSavepointsForFlinkStatement(ctx context.Context, envName, stmtName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkStatementRequest {
	m.lockGetSavepointsForFlinkStatement.Lock()
	defer m.lockGetSavepointsForFlinkStatement.Unlock()

	if m.GetSavepointsForFlinkStatementFunc == nil {
		panic("mocker: MockSavepointsApi.GetSavepointsForFlinkStatementFunc is nil but MockSavepointsApi.GetSavepointsForFlinkStatement was called.")
	}

	call := struct {
		Ctx      context.Context
		EnvName  string
		StmtName string
	}{
		Ctx:      ctx,
		EnvName:  envName,
		StmtName: stmtName,
	}

	m.calls.GetSavepointsForFlinkStatement = append(m.calls.GetSavepointsForFlinkStatement, call)

	return m.GetSavepointsForFlinkStatementFunc(ctx, envName, stmtName)
}

// GetSavepointsForFlinkStatementCalled returns true if GetSavepointsForFlinkStatement was called at least once.
func (m *MockSavepointsApi) GetSavepointsForFlinkStatementCalled() bool {
	m.lockGetSavepointsForFlinkStatement.Lock()
	defer m.lockGetSavepointsForFlinkStatement.Unlock()

	return len(m.calls.GetSavepointsForFlinkStatement) > 0
}

// GetSavepointsForFlinkStatementCalls returns the calls made to GetSavepointsForFlinkStatement.
func (m *MockSavepointsApi) GetSavepointsForFlinkStatementCalls() []struct {
	Ctx      context.Context
	EnvName  string
	StmtName string
} {
	m.lockGetSavepointsForFlinkStatement.Lock()
	defer m.lockGetSavepointsForFlinkStatement.Unlock()

	return m.calls.GetSavepointsForFlinkStatement
}

// GetSavepointsForFlinkStatementExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) GetSavepointsForFlinkStatementExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsPage, *net_http.Response, error) {
	m.lockGetSavepointsForFlinkStatementExecute.Lock()
	defer m.lockGetSavepointsForFlinkStatementExecute.Unlock()

	if m.GetSavepointsForFlinkStatementExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.GetSavepointsForFlinkStatementExecuteFunc is nil but MockSavepointsApi.GetSavepointsForFlinkStatementExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkStatementRequest
	}{
		R: r,
	}

	m.calls.GetSavepointsForFlinkStatementExecute = append(m.calls.GetSavepointsForFlinkStatementExecute, call)

	return m.GetSavepointsForFlinkStatementExecuteFunc(r)
}

// GetSavepointsForFlinkStatementExecuteCalled returns true if GetSavepointsForFlinkStatementExecute was called at least once.
func (m *MockSavepointsApi) GetSavepointsForFlinkStatementExecuteCalled() bool {
	m.lockGetSavepointsForFlinkStatementExecute.Lock()
	defer m.lockGetSavepointsForFlinkStatementExecute.Unlock()

	return len(m.calls.GetSavepointsForFlinkStatementExecute) > 0
}

// GetSavepointsForFlinkStatementExecuteCalls returns the calls made to GetSavepointsForFlinkStatementExecute.
func (m *MockSavepointsApi) GetSavepointsForFlinkStatementExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiGetSavepointsForFlinkStatementRequest
} {
	m.lockGetSavepointsForFlinkStatementExecute.Lock()
	defer m.lockGetSavepointsForFlinkStatementExecute.Unlock()

	return m.calls.GetSavepointsForFlinkStatementExecute
}

// UpdateSavepointForFlinkApplication mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) UpdateSavepointForFlinkApplication(ctx context.Context, envName, appName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkApplicationRequest {
	m.lockUpdateSavepointForFlinkApplication.Lock()
	defer m.lockUpdateSavepointForFlinkApplication.Unlock()

	if m.UpdateSavepointForFlinkApplicationFunc == nil {
		panic("mocker: MockSavepointsApi.UpdateSavepointForFlinkApplicationFunc is nil but MockSavepointsApi.UpdateSavepointForFlinkApplication was called.")
	}

	call := struct {
		Ctx           context.Context
		EnvName       string
		AppName       string
		SavepointName string
	}{
		Ctx:           ctx,
		EnvName:       envName,
		AppName:       appName,
		SavepointName: savepointName,
	}

	m.calls.UpdateSavepointForFlinkApplication = append(m.calls.UpdateSavepointForFlinkApplication, call)

	return m.UpdateSavepointForFlinkApplicationFunc(ctx, envName, appName, savepointName)
}

// UpdateSavepointForFlinkApplicationCalled returns true if UpdateSavepointForFlinkApplication was called at least once.
func (m *MockSavepointsApi) UpdateSavepointForFlinkApplicationCalled() bool {
	m.lockUpdateSavepointForFlinkApplication.Lock()
	defer m.lockUpdateSavepointForFlinkApplication.Unlock()

	return len(m.calls.UpdateSavepointForFlinkApplication) > 0
}

// UpdateSavepointForFlinkApplicationCalls returns the calls made to UpdateSavepointForFlinkApplication.
func (m *MockSavepointsApi) UpdateSavepointForFlinkApplicationCalls() []struct {
	Ctx           context.Context
	EnvName       string
	AppName       string
	SavepointName string
} {
	m.lockUpdateSavepointForFlinkApplication.Lock()
	defer m.lockUpdateSavepointForFlinkApplication.Unlock()

	return m.calls.UpdateSavepointForFlinkApplication
}

// UpdateSavepointForFlinkApplicationExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) UpdateSavepointForFlinkApplicationExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkApplicationRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error) {
	m.lockUpdateSavepointForFlinkApplicationExecute.Lock()
	defer m.lockUpdateSavepointForFlinkApplicationExecute.Unlock()

	if m.UpdateSavepointForFlinkApplicationExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.UpdateSavepointForFlinkApplicationExecuteFunc is nil but MockSavepointsApi.UpdateSavepointForFlinkApplicationExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkApplicationRequest
	}{
		R: r,
	}

	m.calls.UpdateSavepointForFlinkApplicationExecute = append(m.calls.UpdateSavepointForFlinkApplicationExecute, call)

	return m.UpdateSavepointForFlinkApplicationExecuteFunc(r)
}

// UpdateSavepointForFlinkApplicationExecuteCalled returns true if UpdateSavepointForFlinkApplicationExecute was called at least once.
func (m *MockSavepointsApi) UpdateSavepointForFlinkApplicationExecuteCalled() bool {
	m.lockUpdateSavepointForFlinkApplicationExecute.Lock()
	defer m.lockUpdateSavepointForFlinkApplicationExecute.Unlock()

	return len(m.calls.UpdateSavepointForFlinkApplicationExecute) > 0
}

// UpdateSavepointForFlinkApplicationExecuteCalls returns the calls made to UpdateSavepointForFlinkApplicationExecute.
func (m *MockSavepointsApi) UpdateSavepointForFlinkApplicationExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkApplicationRequest
} {
	m.lockUpdateSavepointForFlinkApplicationExecute.Lock()
	defer m.lockUpdateSavepointForFlinkApplicationExecute.Unlock()

	return m.calls.UpdateSavepointForFlinkApplicationExecute
}

// UpdateSavepointForFlinkStatement mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) UpdateSavepointForFlinkStatement(ctx context.Context, envName, stmtName, savepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkStatementRequest {
	m.lockUpdateSavepointForFlinkStatement.Lock()
	defer m.lockUpdateSavepointForFlinkStatement.Unlock()

	if m.UpdateSavepointForFlinkStatementFunc == nil {
		panic("mocker: MockSavepointsApi.UpdateSavepointForFlinkStatementFunc is nil but MockSavepointsApi.UpdateSavepointForFlinkStatement was called.")
	}

	call := struct {
		Ctx           context.Context
		EnvName       string
		StmtName      string
		SavepointName string
	}{
		Ctx:           ctx,
		EnvName:       envName,
		StmtName:      stmtName,
		SavepointName: savepointName,
	}

	m.calls.UpdateSavepointForFlinkStatement = append(m.calls.UpdateSavepointForFlinkStatement, call)

	return m.UpdateSavepointForFlinkStatementFunc(ctx, envName, stmtName, savepointName)
}

// UpdateSavepointForFlinkStatementCalled returns true if UpdateSavepointForFlinkStatement was called at least once.
func (m *MockSavepointsApi) UpdateSavepointForFlinkStatementCalled() bool {
	m.lockUpdateSavepointForFlinkStatement.Lock()
	defer m.lockUpdateSavepointForFlinkStatement.Unlock()

	return len(m.calls.UpdateSavepointForFlinkStatement) > 0
}

// UpdateSavepointForFlinkStatementCalls returns the calls made to UpdateSavepointForFlinkStatement.
func (m *MockSavepointsApi) UpdateSavepointForFlinkStatementCalls() []struct {
	Ctx           context.Context
	EnvName       string
	StmtName      string
	SavepointName string
} {
	m.lockUpdateSavepointForFlinkStatement.Lock()
	defer m.lockUpdateSavepointForFlinkStatement.Unlock()

	return m.calls.UpdateSavepointForFlinkStatement
}

// UpdateSavepointForFlinkStatementExecute mocks base method by wrapping the associated func.
func (m *MockSavepointsApi) UpdateSavepointForFlinkStatementExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkStatementRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error) {
	m.lockUpdateSavepointForFlinkStatementExecute.Lock()
	defer m.lockUpdateSavepointForFlinkStatementExecute.Unlock()

	if m.UpdateSavepointForFlinkStatementExecuteFunc == nil {
		panic("mocker: MockSavepointsApi.UpdateSavepointForFlinkStatementExecuteFunc is nil but MockSavepointsApi.UpdateSavepointForFlinkStatementExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkStatementRequest
	}{
		R: r,
	}

	m.calls.UpdateSavepointForFlinkStatementExecute = append(m.calls.UpdateSavepointForFlinkStatementExecute, call)

	return m.UpdateSavepointForFlinkStatementExecuteFunc(r)
}

// UpdateSavepointForFlinkStatementExecuteCalled returns true if UpdateSavepointForFlinkStatementExecute was called at least once.
func (m *MockSavepointsApi) UpdateSavepointForFlinkStatementExecuteCalled() bool {
	m.lockUpdateSavepointForFlinkStatementExecute.Lock()
	defer m.lockUpdateSavepointForFlinkStatementExecute.Unlock()

	return len(m.calls.UpdateSavepointForFlinkStatementExecute) > 0
}

// UpdateSavepointForFlinkStatementExecuteCalls returns the calls made to UpdateSavepointForFlinkStatementExecute.
func (m *MockSavepointsApi) UpdateSavepointForFlinkStatementExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiUpdateSavepointForFlinkStatementRequest
} {
	m.lockUpdateSavepointForFlinkStatementExecute.Lock()
	defer m.lockUpdateSavepointForFlinkStatementExecute.Unlock()

	return m.calls.UpdateSavepointForFlinkStatementExecute
}

// Reset resets the calls made to the mocked methods.
func (m *MockSavepointsApi) Reset() {
	m.lockBulkDeleteSavepointsForFlinkApplication.Lock()
	m.calls.BulkDeleteSavepointsForFlinkApplication = nil
	m.lockBulkDeleteSavepointsForFlinkApplication.Unlock()
	m.lockBulkDeleteSavepointsForFlinkApplicationExecute.Lock()
	m.calls.BulkDeleteSavepointsForFlinkApplicationExecute = nil
	m.lockBulkDeleteSavepointsForFlinkApplicationExecute.Unlock()
	m.lockBulkDeleteSavepointsForFlinkStatement.Lock()
	m.calls.BulkDeleteSavepointsForFlinkStatement = nil
	m.lockBulkDeleteSavepointsForFlinkStatement.Unlock()
	m.lockBulkDeleteSavepointsForFlinkStatementExecute.Lock()
	m.calls.BulkDeleteSavepointsForFlinkStatementExecute = nil
	m.lockBulkDeleteSavepointsForFlinkStatementExecute.Unlock()
	m.lockCreateSavepointForFlinkApplication.Lock()
	m.calls.CreateSavepointForFlinkApplication = nil
	m.lockCreateSavepointForFlinkApplication.Unlock()
	m.lockCreateSavepointForFlinkApplicationExecute.Lock()
	m.calls.CreateSavepointForFlinkApplicationExecute = nil
	m.lockCreateSavepointForFlinkApplicationExecute.Unlock()
	m.lockCreateSavepointForFlinkStatement.Lock()
	m.calls.CreateSavepointForFlinkStatement = nil
	m.lockCreateSavepointForFlinkStatement.Unlock()
	m.lockCreateSavepointForFlinkStatementExecute.Lock()
	m.calls.CreateSavepointForFlinkStatementExecute = nil
	m.lockCreateSavepointForFlinkStatementExecute.Unlock()
	m.lockDeleteSavepointForFlinkApplication.Lock()
	m.calls.DeleteSavepointForFlinkApplication = nil
	m.lockDeleteSavepointForFlinkApplication.Unlock()
	m.lockDeleteSavepointForFlinkApplicationExecute.Lock()
	m.calls.DeleteSavepointForFlinkApplicationExecute = nil
	m.lockDeleteSavepointForFlinkApplicationExecute.Unlock()
	m.lockDeleteSavepointForFlinkStatement.Lock()
	m.calls.DeleteSavepointForFlinkStatement = nil
	m.lockDeleteSavepointForFlinkStatement.Unlock()
	m.lockDeleteSavepointForFlinkStatementExecute.Lock()
	m.calls.DeleteSavepointForFlinkStatementExecute = nil
	m.lockDeleteSavepointForFlinkStatementExecute.Unlock()
	m.lockDetachSavepointFromFlinkApplication.Lock()
	m.calls.DetachSavepointFromFlinkApplication = nil
	m.lockDetachSavepointFromFlinkApplication.Unlock()
	m.lockDetachSavepointFromFlinkApplicationExecute.Lock()
	m.calls.DetachSavepointFromFlinkApplicationExecute = nil
	m.lockDetachSavepointFromFlinkApplicationExecute.Unlock()
	m.lockGetSavepointForFlinkApplication.Lock()
	m.calls.GetSavepointForFlinkApplication = nil
	m.lockGetSavepointForFlinkApplication.Unlock()
	m.lockGetSavepointForFlinkApplicationExecute.Lock()
	m.calls.GetSavepointForFlinkApplicationExecute = nil
	m.lockGetSavepointForFlinkApplicationExecute.Unlock()
	m.lockGetSavepointForFlinkStatement.Lock()
	m.calls.GetSavepointForFlinkStatement = nil
	m.lockGetSavepointForFlinkStatement.Unlock()
	m.lockGetSavepointForFlinkStatementExecute.Lock()
	m.calls.GetSavepointForFlinkStatementExecute = nil
	m.lockGetSavepointForFlinkStatementExecute.Unlock()
	m.lockGetSavepointsForFlinkApplication.Lock()
	m.calls.GetSavepointsForFlinkApplication = nil
	m.lockGetSavepointsForFlinkApplication.Unlock()
	m.lockGetSavepointsForFlinkApplicationExecute.Lock()
	m.calls.GetSavepointsForFlinkApplicationExecute = nil
	m.lockGetSavepointsForFlinkApplicationExecute.Unlock()
	m.lockGetSavepointsForFlinkStatement.Lock()
	m.calls.GetSavepointsForFlinkStatement = nil
	m.lockGetSavepointsForFlinkStatement.Unlock()
	m.lockGetSavepointsForFlinkStatementExecute.Lock()
	m.calls.GetSavepointsForFlinkStatementExecute = nil
	m.lockGetSavepointsForFlinkStatementExecute.Unlock()
	m.lockUpdateSavepointForFlinkApplication.Lock()
	m.calls.UpdateSavepointForFlinkApplication = nil
	m.lockUpdateSavepointForFlinkApplication.Unlock()
	m.lockUpdateSavepointForFlinkApplicationExecute.Lock()
	m.calls.UpdateSavepointForFlinkApplicationExecute = nil
	m.lockUpdateSavepointForFlinkApplicationExecute.Unlock()
	m.lockUpdateSavepointForFlinkStatement.Lock()
	m.calls.UpdateSavepointForFlinkStatement = nil
	m.lockUpdateSavepointForFlinkStatement.Unlock()
	m.lockUpdateSavepointForFlinkStatementExecute.Lock()
	m.calls.UpdateSavepointForFlinkStatementExecute = nil
	m.lockUpdateSavepointForFlinkStatementExecute.Unlock()
}
