// Code generated by mocker. DO NOT EDIT.
// github.com/travisjeffery/mocker
// Source: api_detached_savepoints.go

package mock

import (
	context "context"
	net_http "net/http"
	sync "sync"

	github_com_confluentinc_cmf_sdk_go_v1 "github.com/confluentinc/cmf-sdk-go/v1"
)

// MockDetachedSavepointsApi is a mock of DetachedSavepointsApi interface
type MockDetachedSavepointsApi struct {
	lockCreateDetachedSavepoint sync.Mutex
	CreateDetachedSavepointFunc func(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiCreateDetachedSavepointRequest

	lockCreateDetachedSavepointExecute sync.Mutex
	CreateDetachedSavepointExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiCreateDetachedSavepointRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error)

	lockDeleteDetachedSavepoint sync.Mutex
	DeleteDetachedSavepointFunc func(ctx context.Context, detachedSavepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteDetachedSavepointRequest

	lockDeleteDetachedSavepointExecute sync.Mutex
	DeleteDetachedSavepointExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteDetachedSavepointRequest) (*net_http.Response, error)

	lockGetDetachedSavepoint sync.Mutex
	GetDetachedSavepointFunc func(ctx context.Context, detachedSavepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetDetachedSavepointRequest

	lockGetDetachedSavepointExecute sync.Mutex
	GetDetachedSavepointExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetDetachedSavepointRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error)

	lockListDetachedSavepoints sync.Mutex
	ListDetachedSavepointsFunc func(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiListDetachedSavepointsRequest

	lockListDetachedSavepointsExecute sync.Mutex
	ListDetachedSavepointsExecuteFunc func(r github_com_confluentinc_cmf_sdk_go_v1.ApiListDetachedSavepointsRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsPage, *net_http.Response, error)

	calls struct {
		CreateDetachedSavepoint []struct {
			Ctx context.Context
		}
		CreateDetachedSavepointExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateDetachedSavepointRequest
		}
		DeleteDetachedSavepoint []struct {
			Ctx                   context.Context
			DetachedSavepointName string
		}
		DeleteDetachedSavepointExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteDetachedSavepointRequest
		}
		GetDetachedSavepoint []struct {
			Ctx                   context.Context
			DetachedSavepointName string
		}
		GetDetachedSavepointExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiGetDetachedSavepointRequest
		}
		ListDetachedSavepoints []struct {
			Ctx context.Context
		}
		ListDetachedSavepointsExecute []struct {
			R github_com_confluentinc_cmf_sdk_go_v1.ApiListDetachedSavepointsRequest
		}
	}
}

// CreateDetachedSavepoint mocks base method by wrapping the associated func.
func (m *MockDetachedSavepointsApi) CreateDetachedSavepoint(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiCreateDetachedSavepointRequest {
	m.lockCreateDetachedSavepoint.Lock()
	defer m.lockCreateDetachedSavepoint.Unlock()

	if m.CreateDetachedSavepointFunc == nil {
		panic("mocker: MockDetachedSavepointsApi.CreateDetachedSavepointFunc is nil but MockDetachedSavepointsApi.CreateDetachedSavepoint was called.")
	}

	call := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}

	m.calls.CreateDetachedSavepoint = append(m.calls.CreateDetachedSavepoint, call)

	return m.CreateDetachedSavepointFunc(ctx)
}

// CreateDetachedSavepointCalled returns true if CreateDetachedSavepoint was called at least once.
func (m *MockDetachedSavepointsApi) CreateDetachedSavepointCalled() bool {
	m.lockCreateDetachedSavepoint.Lock()
	defer m.lockCreateDetachedSavepoint.Unlock()

	return len(m.calls.CreateDetachedSavepoint) > 0
}

// CreateDetachedSavepointCalls returns the calls made to CreateDetachedSavepoint.
func (m *MockDetachedSavepointsApi) CreateDetachedSavepointCalls() []struct {
	Ctx context.Context
} {
	m.lockCreateDetachedSavepoint.Lock()
	defer m.lockCreateDetachedSavepoint.Unlock()

	return m.calls.CreateDetachedSavepoint
}

// CreateDetachedSavepointExecute mocks base method by wrapping the associated func.
func (m *MockDetachedSavepointsApi) CreateDetachedSavepointExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiCreateDetachedSavepointRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error) {
	m.lockCreateDetachedSavepointExecute.Lock()
	defer m.lockCreateDetachedSavepointExecute.Unlock()

	if m.CreateDetachedSavepointExecuteFunc == nil {
		panic("mocker: MockDetachedSavepointsApi.CreateDetachedSavepointExecuteFunc is nil but MockDetachedSavepointsApi.CreateDetachedSavepointExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateDetachedSavepointRequest
	}{
		R: r,
	}

	m.calls.CreateDetachedSavepointExecute = append(m.calls.CreateDetachedSavepointExecute, call)

	return m.CreateDetachedSavepointExecuteFunc(r)
}

// CreateDetachedSavepointExecuteCalled returns true if CreateDetachedSavepointExecute was called at least once.
func (m *MockDetachedSavepointsApi) CreateDetachedSavepointExecuteCalled() bool {
	m.lockCreateDetachedSavepointExecute.Lock()
	defer m.lockCreateDetachedSavepointExecute.Unlock()

	return len(m.calls.CreateDetachedSavepointExecute) > 0
}

// CreateDetachedSavepointExecuteCalls returns the calls made to CreateDetachedSavepointExecute.
func (m *MockDetachedSavepointsApi) CreateDetachedSavepointExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiCreateDetachedSavepointRequest
} {
	m.lockCreateDetachedSavepointExecute.Lock()
	defer m.lockCreateDetachedSavepointExecute.Unlock()

	return m.calls.CreateDetachedSavepointExecute
}

// DeleteDetachedSavepoint mocks base method by wrapping the associated func.
func (m *MockDetachedSavepointsApi) DeleteDetachedSavepoint(ctx context.Context, detachedSavepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteDetachedSavepointRequest {
	m.lockDeleteDetachedSavepoint.Lock()
	defer m.lockDeleteDetachedSavepoint.Unlock()

	if m.DeleteDetachedSavepointFunc == nil {
		panic("mocker: MockDetachedSavepointsApi.DeleteDetachedSavepointFunc is nil but MockDetachedSavepointsApi.DeleteDetachedSavepoint was called.")
	}

	call := struct {
		Ctx                   context.Context
		DetachedSavepointName string
	}{
		Ctx:                   ctx,
		DetachedSavepointName: detachedSavepointName,
	}

	m.calls.DeleteDetachedSavepoint = append(m.calls.DeleteDetachedSavepoint, call)

	return m.DeleteDetachedSavepointFunc(ctx, detachedSavepointName)
}

// DeleteDetachedSavepointCalled returns true if DeleteDetachedSavepoint was called at least once.
func (m *MockDetachedSavepointsApi) DeleteDetachedSavepointCalled() bool {
	m.lockDeleteDetachedSavepoint.Lock()
	defer m.lockDeleteDetachedSavepoint.Unlock()

	return len(m.calls.DeleteDetachedSavepoint) > 0
}

// DeleteDetachedSavepointCalls returns the calls made to DeleteDetachedSavepoint.
func (m *MockDetachedSavepointsApi) DeleteDetachedSavepointCalls() []struct {
	Ctx                   context.Context
	DetachedSavepointName string
} {
	m.lockDeleteDetachedSavepoint.Lock()
	defer m.lockDeleteDetachedSavepoint.Unlock()

	return m.calls.DeleteDetachedSavepoint
}

// DeleteDetachedSavepointExecute mocks base method by wrapping the associated func.
func (m *MockDetachedSavepointsApi) DeleteDetachedSavepointExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteDetachedSavepointRequest) (*net_http.Response, error) {
	m.lockDeleteDetachedSavepointExecute.Lock()
	defer m.lockDeleteDetachedSavepointExecute.Unlock()

	if m.DeleteDetachedSavepointExecuteFunc == nil {
		panic("mocker: MockDetachedSavepointsApi.DeleteDetachedSavepointExecuteFunc is nil but MockDetachedSavepointsApi.DeleteDetachedSavepointExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteDetachedSavepointRequest
	}{
		R: r,
	}

	m.calls.DeleteDetachedSavepointExecute = append(m.calls.DeleteDetachedSavepointExecute, call)

	return m.DeleteDetachedSavepointExecuteFunc(r)
}

// DeleteDetachedSavepointExecuteCalled returns true if DeleteDetachedSavepointExecute was called at least once.
func (m *MockDetachedSavepointsApi) DeleteDetachedSavepointExecuteCalled() bool {
	m.lockDeleteDetachedSavepointExecute.Lock()
	defer m.lockDeleteDetachedSavepointExecute.Unlock()

	return len(m.calls.DeleteDetachedSavepointExecute) > 0
}

// DeleteDetachedSavepointExecuteCalls returns the calls made to DeleteDetachedSavepointExecute.
func (m *MockDetachedSavepointsApi) DeleteDetachedSavepointExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiDeleteDetachedSavepointRequest
} {
	m.lockDeleteDetachedSavepointExecute.Lock()
	defer m.lockDeleteDetachedSavepointExecute.Unlock()

	return m.calls.DeleteDetachedSavepointExecute
}

// GetDetachedSavepoint mocks base method by wrapping the associated func.
func (m *MockDetachedSavepointsApi) GetDetachedSavepoint(ctx context.Context, detachedSavepointName string) github_com_confluentinc_cmf_sdk_go_v1.ApiGetDetachedSavepointRequest {
	m.lockGetDetachedSavepoint.Lock()
	defer m.lockGetDetachedSavepoint.Unlock()

	if m.GetDetachedSavepointFunc == nil {
		panic("mocker: MockDetachedSavepointsApi.GetDetachedSavepointFunc is nil but MockDetachedSavepointsApi.GetDetachedSavepoint was called.")
	}

	call := struct {
		Ctx                   context.Context
		DetachedSavepointName string
	}{
		Ctx:                   ctx,
		DetachedSavepointName: detachedSavepointName,
	}

	m.calls.GetDetachedSavepoint = append(m.calls.GetDetachedSavepoint, call)

	return m.GetDetachedSavepointFunc(ctx, detachedSavepointName)
}

// GetDetachedSavepointCalled returns true if GetDetachedSavepoint was called at least once.
func (m *MockDetachedSavepointsApi) GetDetachedSavepointCalled() bool {
	m.lockGetDetachedSavepoint.Lock()
	defer m.lockGetDetachedSavepoint.Unlock()

	return len(m.calls.GetDetachedSavepoint) > 0
}

// GetDetachedSavepointCalls returns the calls made to GetDetachedSavepoint.
func (m *MockDetachedSavepointsApi) GetDetachedSavepointCalls() []struct {
	Ctx                   context.Context
	DetachedSavepointName string
} {
	m.lockGetDetachedSavepoint.Lock()
	defer m.lockGetDetachedSavepoint.Unlock()

	return m.calls.GetDetachedSavepoint
}

// GetDetachedSavepointExecute mocks base method by wrapping the associated func.
func (m *MockDetachedSavepointsApi) GetDetachedSavepointExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiGetDetachedSavepointRequest) (github_com_confluentinc_cmf_sdk_go_v1.Savepoint, *net_http.Response, error) {
	m.lockGetDetachedSavepointExecute.Lock()
	defer m.lockGetDetachedSavepointExecute.Unlock()

	if m.GetDetachedSavepointExecuteFunc == nil {
		panic("mocker: MockDetachedSavepointsApi.GetDetachedSavepointExecuteFunc is nil but MockDetachedSavepointsApi.GetDetachedSavepointExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiGetDetachedSavepointRequest
	}{
		R: r,
	}

	m.calls.GetDetachedSavepointExecute = append(m.calls.GetDetachedSavepointExecute, call)

	return m.GetDetachedSavepointExecuteFunc(r)
}

// GetDetachedSavepointExecuteCalled returns true if GetDetachedSavepointExecute was called at least once.
func (m *MockDetachedSavepointsApi) GetDetachedSavepointExecuteCalled() bool {
	m.lockGetDetachedSavepointExecute.Lock()
	defer m.lockGetDetachedSavepointExecute.Unlock()

	return len(m.calls.GetDetachedSavepointExecute) > 0
}

// GetDetachedSavepointExecuteCalls returns the calls made to GetDetachedSavepointExecute.
func (m *MockDetachedSavepointsApi) GetDetachedSavepointExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiGetDetachedSavepointRequest
} {
	m.lockGetDetachedSavepointExecute.Lock()
	defer m.lockGetDetachedSavepointExecute.Unlock()

	return m.calls.GetDetachedSavepointExecute
}

// ListDetachedSavepoints mocks base method by wrapping the associated func.
func (m *MockDetachedSavepointsApi) ListDetachedSavepoints(ctx context.Context) github_com_confluentinc_cmf_sdk_go_v1.ApiListDetachedSavepointsRequest {
	m.lockListDetachedSavepoints.Lock()
	defer m.lockListDetachedSavepoints.Unlock()

	if m.ListDetachedSavepointsFunc == nil {
		panic("mocker: MockDetachedSavepointsApi.ListDetachedSavepointsFunc is nil but MockDetachedSavepointsApi.ListDetachedSavepoints was called.")
	}

	call := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}

	m.calls.ListDetachedSavepoints = append(m.calls.ListDetachedSavepoints, call)

	return m.ListDetachedSavepointsFunc(ctx)
}

// ListDetachedSavepointsCalled returns true if ListDetachedSavepoints was called at least once.
func (m *MockDetachedSavepointsApi) ListDetachedSavepointsCalled() bool {
	m.lockListDetachedSavepoints.Lock()
	defer m.lockListDetachedSavepoints.Unlock()

	return len(m.calls.ListDetachedSavepoints) > 0
}

// ListDetachedSavepointsCalls returns the calls made to ListDetachedSavepoints.
func (m *MockDetachedSavepointsApi) ListDetachedSavepointsCalls() []struct {
	Ctx context.Context
} {
	m.lockListDetachedSavepoints.Lock()
	defer m.lockListDetachedSavepoints.Unlock()

	return m.calls.ListDetachedSavepoints
}

// ListDetachedSavepointsExecute mocks base method by wrapping the associated func.
func (m *MockDetachedSavepointsApi) ListDetachedSavepointsExecute(r github_com_confluentinc_cmf_sdk_go_v1.ApiListDetachedSavepointsRequest) (github_com_confluentinc_cmf_sdk_go_v1.SavepointsPage, *net_http.Response, error) {
	m.lockListDetachedSavepointsExecute.Lock()
	defer m.lockListDetachedSavepointsExecute.Unlock()

	if m.ListDetachedSavepointsExecuteFunc == nil {
		panic("mocker: MockDetachedSavepointsApi.ListDetachedSavepointsExecuteFunc is nil but MockDetachedSavepointsApi.ListDetachedSavepointsExecute was called.")
	}

	call := struct {
		R github_com_confluentinc_cmf_sdk_go_v1.ApiListDetachedSavepointsRequest
	}{
		R: r,
	}

	m.calls.ListDetachedSavepointsExecute = append(m.calls.ListDetachedSavepointsExecute, call)

	return m.ListDetachedSavepointsExecuteFunc(r)
}

// ListDetachedSavepointsExecuteCalled returns true if ListDetachedSavepointsExecute was called at least once.
func (m *MockDetachedSavepointsApi) ListDetachedSavepointsExecuteCalled() bool {
	m.lockListDetachedSavepointsExecute.Lock()
	defer m.lockListDetachedSavepointsExecute.Unlock()

	return len(m.calls.ListDetachedSavepointsExecute) > 0
}

// ListDetachedSavepointsExecuteCalls returns the calls made to ListDetachedSavepointsExecute.
func (m *MockDetachedSavepointsApi) ListDetachedSavepointsExecuteCalls() []struct {
	R github_com_confluentinc_cmf_sdk_go_v1.ApiListDetachedSavepointsRequest
} {
	m.lockListDetachedSavepointsExecute.Lock()
	defer m.lockListDetachedSavepointsExecute.Unlock()

	return m.calls.ListDetachedSavepointsExecute
}

// Reset resets the calls made to the mocked methods.
func (m *MockDetachedSavepointsApi) Reset() {
	m.lockCreateDetachedSavepoint.Lock()
	m.calls.CreateDetachedSavepoint = nil
	m.lockCreateDetachedSavepoint.Unlock()
	m.lockCreateDetachedSavepointExecute.Lock()
	m.calls.CreateDetachedSavepointExecute = nil
	m.lockCreateDetachedSavepointExecute.Unlock()
	m.lockDeleteDetachedSavepoint.Lock()
	m.calls.DeleteDetachedSavepoint = nil
	m.lockDeleteDetachedSavepoint.Unlock()
	m.lockDeleteDetachedSavepointExecute.Lock()
	m.calls.DeleteDetachedSavepointExecute = nil
	m.lockDeleteDetachedSavepointExecute.Unlock()
	m.lockGetDetachedSavepoint.Lock()
	m.calls.GetDetachedSavepoint = nil
	m.lockGetDetachedSavepoint.Unlock()
	m.lockGetDetachedSavepointExecute.Lock()
	m.calls.GetDetachedSavepointExecute = nil
	m.lockGetDetachedSavepointExecute.Unlock()
	m.lockListDetachedSavepoints.Lock()
	m.calls.ListDetachedSavepoints = nil
	m.lockListDetachedSavepoints.Unlock()
	m.lockListDetachedSavepointsExecute.Lock()
	m.calls.ListDetachedSavepointsExecute = nil
	m.lockListDetachedSavepointsExecute.Unlock()
}
